project:
  type: book
  output-dir: docs

lang: ja

book:
  title: "私たちのR"
  subtitle: "ベストプラクティスの探求"
  author: 
    - name: "宋財泫（Jaehyun Song）"
      affiliation: "関西大学"
      url: https://www.jaysong.net
    - name: "矢内勇生（Yuki Yanai）"
      affiliation: "高知工科大学"
      url: https://yukiyanai.github.io
  date: "2020/6/22"
  page-footer: 
    center: "Copyright 2024, [Jaehyun Song](https://www.jaysong.net) and [Yuki Yanai](https://yukiyanai.github.io/)"
    border: true
  search: true
  repo-url: https://github.com/JaehyunSong/RBook/
  site-url: "https://www.jaysong.net/RBook/"
  #downloads: [pdf]
  sharing: [twitter, facebook]
  output-file: "RN4E"
  sidebar: 
    style: docked
    pinned: true
  page-navigation: true
  chapters:
    - index.qmd
    - part: "Rの導入"
      chapters:
        - aboutr.qmd
        - installation.qmd
        - ide.qmd
        - r_customize.qmd
        - packages.qmd
    - part: "Rの基礎"
      chapters:
        - project.qmd
        - r_basic.qmd
        - io.qmd
        - datatype.qmd
        - datastructure.qmd
        - programming.qmd
        - functions.qmd
    - part: "データハンドリング"
      chapters:
        - datahandling1.qmd
        - datahandling2.qmd
        - datahandling3.qmd
        - factor.qmd
        - tidydata.qmd
        - string.qmd
    - part: "可視化"
      chapters:
        - visualization1.qmd
        - visualization2.qmd
        - visualization3.qmd
        - visualization4.qmd
        - table.qmd
    - part: "再現可能な研究"
      chapters:
        - rmarkdown.qmd
        - rmarkdown2.qmd
        - quarto.qmd
        - renv.qmd
    - part: "中級者向け"
      chapters:
        - iteration.qmd
        - oop.qmd
        - monte.qmd
        - scraping.qmd
  appendices:
    - dataset.qmd # PDF renderingの際はコメントアウト
    - filesystem.qmd
    - tips.qmd
    - session.qmd # PDF renderingの際はコメントアウト
    - references.qmd # PDF renderingの際はコメントアウト
    - quarto1.qmd
    - quarto2.qmd
    - quarto3.qmd
    - quarto4.qmd
  cover-image: "Figs/Cover.png"
  favicon: "Figs/favicon.png"
  google-analytics: 
    tracking-id: "G-CEHS4C056W"
    anonymize-ip: false
  twitter-card:
    title: "私たちのR: ベストプラクティスの探求"
    description: "R Not for Everyone: An Esoteric Guide"
    card-style: summary
    image: "Figs/favicon.png"
  open-graph:
    title: "私たちのR: ベストプラクティスの探求"
    description: "R Not for Everyone: An Esoteric Guide"
    image: "Figs/favicon.png"

knitr:
  opts_chunk: 
    dev: "ragg_png"
    fig.align: "center"
    dpi: 300
    fig.pos: "H"

format:
  html:
    theme: 
      - cosmo
      - rn4e.scss
    grid:
      sidebar-width: 375px
    number-sections: true
    code-line-numbers: true
    highlight-style: a11y
    html-math-method: mathjax
    toc: true
    toc-depth: 3
    link-external-newwindow: true
    code-annotations: hover
    header-includes: |
      <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet"> 
      <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Mono&display=swap" rel="stylesheet"> 
    mainfont: "Noto Sans JP"
    monofont: "Noto Sans Mono"
  pdf:
    keep-tex: true
    latex-auto-mk: false
    pdf-engine: latexmk
    pdf-engine-opts: 
      - -lualatex
      - -outdir=output
      - -f
    documentclass: ltjsbook
    classoption:
      - 10pt
      - a4paper
    include-in-header: 
      text: |
        \usepackage[nomarginpar]{geometry}
        %verbatim環境における自動改行
        %\usepackage{fvextra}
        %\DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        %\DefineVerbatimEnvironment{OutputCode}{Verbatim}{breaklines,commandchars=\\\{\}}
    cite-method: natbib
    code-line-numbers: true
    mainfont: "Noto Serif JP"
    sansfont: "Noto Sans JP"
    monofont: "Noto Sans Mono"
    #highlight-style: a11y # 個人的にはこのスタイルは好みだが、PDFの場合、背景が白になる

bibliography: tex/references.bib
biblio-style: tex/jecon.bst

excute:
  freeze: auto
