project:
  type: book
  output-dir: docs

lang: ja

book:
  title: "私たちのR"
  subtitle: "ベストプラクティスの探求"
  author: 
    - name: "宋財泫（Jaehyun Song）"
      affiliation: "関西大学"
      url: https://www.jaysong.net
    - name: "矢内勇生（Yuki Yanai）"
      affiliation: "高知工科大学"
      url: https://yukiyanai.github.io
  date: "2020/6/22"
  page-footer: "Copyright 2023, Jaehyun Song and Yuki Yanai"
  search: true
  repo-url: https://github.com/JaehyunSong/RBook/
  site-url: "https://www.jaysong.net/RBook/"
  #downloads: [pdf]
  sharing: [twitter, facebook]
  output-file: "RN4E"
  sidebar: 
    style: docked
    background: light
    pinned: true
  page-navigation: true
  chapters:
    - index.qmd
    - part: "Rの導入"
      chapters:
        - aboutr.qmd
        - installation.qmd
        - ide.qmd
        - r_customize.qmd
        - packages.qmd
    - part: "Rの基礎"
      chapters:
        - project.qmd
        - r_basic.qmd
        - io.qmd
        - datatype.qmd
        - datastructure.qmd
        - programming.qmd
        - functions.qmd
    - part: "データハンドリング"
      chapters:
        - datahandling1.qmd
        - datahandling2.qmd
        - factor.qmd
        - tidydata.qmd
        - string.qmd
    - part: "可視化"
      chapters:
        - visualization1.qmd
        - visualization2.qmd
        - visualization3.qmd
        - visualization4.qmd
        - table.qmd
    - part: "再現可能な研究"
      chapters:
        - rmarkdown.qmd
        - rmarkdown2.qmd
        - quarto.qmd
        - renv.qmd
    - part: "中級者向け"
      chapters:
        - iteration.qmd
        - oop.qmd
        - monte.qmd
        - scraping.qmd
    - part: "付録"
      chapters:
        - dataset.qmd
        - filesystem.qmd
        - tips.qmd
        - session.qmd
        - references.qmd
  cover-image: "Figs/Cover.png"
  favicon: "Figs/favicon.png"
  google-analytics: 
    tracking-id: "G-CEHS4C056W"
    anonymize-ip: false
  twitter-card:
    title: "私たちのR: ベストプラクティスの探求"
    description: "R Not for Everyone: An Esoteric Guide"
    card-style: summary
    image: "Figs/favicon.png"
  open-graph:
    title: "私たちのR: ベストプラクティスの探求"
    description: "R Not for Everyone: An Esoteric Guide"
    image: "Figs/favicon.png"

format:
  html:
    theme: 
      - cosmo
      - rn4e.scss
    number-sections: true
    highlight-style: a11y
    html-math-method: mathjax
    toc: true
    toc-depth: 3
    link-external-newwindow: true
    mainfont: "Noto Sans CJK JP"
#  pdf:
#    documentclass: bxjsbook
#    classoption:
#      - pandoc
#      - ja=standard
#      - jafont=haranoaji
#    papersize: A4
#    cite-method: natbib
#    keep-tex: true

#pdf-engine: lualatex
#latex-output-dir: pdf
bibliography: tex/references.bib
#biblio-style: tex/jecon.bst # なぜかjecon.bstはうまくいかない...

excute:
  freeze: auto