project:
  type: book
  output-dir: docs

language: _language.yml

book:
  title: "私たちのR"
  subtitle: "ベストプラクティスの探求"
  author: "Jaehyun Song and Yuki Yanai"
  #date: "改訂: `r Sys.Date()`" # inline codeが使えない?
  page-footer: "Copyright 2022, Jaehyun Song and Yuki Yanai"
  search: true
  repo-url: https://github.com/JaehyunSong/RBook/
  site-url: "https://www.jaysong.net/RBook/"
  #downloads: [pdf]
  sharing: [twitter, facebook]
  output-file: "RN4E"
  sidebar: 
    style: docked
    background: none
    pinned: true
  page-navigation: true
  chapters:
    - index.qmd
    - part: "Rの導入"
      chapters:
        - aboutR.qmd
        - installation.qmd
        - ide.qmd
        - r_customize.qmd
        - packages.qmd
    - part: "Rの基礎"
      chapters:
        - r_basic.qmd
        - io.qmd
        - datatype.qmd
        - datastructure.qmd
        - programming.qmd
        - functions.qmd
    - part: "データハンドリング"
      chapters:
        - datahandling1.qmd
        - datahandling2.qmd
        - factor.qmd
        - tidydata.qmd
        - string.qmd
    - part: "可視化"
      chapters:
        - visualization1.qmd
        - visualization2.qmd
        - visualization3.qmd
        - visualization4.qmd
        - visualization5.qmd
    - part: "再現可能な研究"
      chapters:
        - rmarkdown.qmd
        - rmarkdown2.qmd
        - quarto.qmd
        - table.qmd
        - renv.qmd
    - part: "中級者向け"
      chapters:
        - iteration.qmd
        - oop.qmd
        - monte.qmd
        - scraping.qmd
        - api.qmd
    - part: "付録"
      chapters:
        - tips.qmd
        - session.qmd
        - references.qmd
  cover-image: "Figs/Cover.png"
  favicon: "Figs/favicon.png"
  open-graph: 
    title: "R Not for Everyone"
    description: "An Esoteric Guide"
    image: "Figs/Cover.png"
  google-analytics: 
    tracking-id: "UA-165592410-1"
    anonymize-ip: false

format:
  html:
    theme: 
      - cosmo
      - rn4e.scss
    identifier-prefix: 'RN4E'
    number-sections: true
    #mainfont: "Noto Sans CJK JP"
    filters:
      - add-target-attr.lua
#  pdf:
#    documentclass: bxjsbook
#    classoption:
#      - pandoc
#      - ja=standard
#      - jafont=haranoaji
#    papersize: A4
#    cite-method: natbib
#    keep-tex: true

#pdf-engine: lualatex
#latex-output-dir: pdf
bibliography: tex/references.bib
#biblio-style: tex/jecon.bst # なぜかjecon.bstはうまくいかない...

crossref:
  ref-hyperlink: true