---
filters: 
  - d-btn
---

# データセット {.unnumbered}

#### 第7章：データの入出力

::: {.center-table50}
|ファイル名          |ダウンロード                    |
|:-------------------|:------------------------------:|
|`FIFA_Women.csv`    |{{< d-btn FIFA_Women.csv >}}    |
|`Vote_ShiftJIS.csv` |{{< d-btn Vote_ShiftJIS.csv >}} |
|`Vote.csv`          |{{< d-btn Vote.csv >}}          |
|`Soccer.xlsx`       |{{< d-btn Soccer.xlsx >}}       |
|`Soccer.dta`        |{{< d-btn Soccer.dta >}}        |
|`Scores.RData`      |{{< d-btn Scores.RData >}}      |

: {tbl-colwidths="[65,35]"}
:::

#### 第9章：データ構造

::: {.center-table50}
|ファイル名          |ダウンロード                    |
|:-------------------|:------------------------------:|
|`Vote.csv`          |{{< d-btn Vote.csv >}}          |
|`FIFA_Women.csv`    |{{< d-btn FIFA_Women.csv >}}    |
|`FIFA_Men.csv`      |{{< d-btn FIFA_Men.csv >}}      |

: {tbl-colwidths="[65,35]"}
:::

#### 第10章：Rプログラミングの基礎

::: {.center-table50}
|ファイル名          |ダウンロード                    |
|:-------------------|:------------------------------:|
|`FIFA_Men.csv`      |{{< d-btn FIFA_Men.csv >}}      |

: {tbl-colwidths="[65,35]"}
:::

#### 第12章：データハンドリング [抽出]

::: {.center-table50}
|ファイル名          |ダウンロード                    |
|:-------------------|:------------------------------:|
|`Ramen.csv`         |{{< d-btn Ramen.csv >}}         |

: {tbl-colwidths="[65,35]"}
:::

#### 第13章：データハンドリング [拡張]

::: {.center-table50}
|ファイル名          |ダウンロード                    |
|:-------------------|:------------------------------:|
|`Ramen.csv`         |{{< d-btn Ramen.csv >}}         |
|`Ramen2.csv`        |{{< d-btn Ramen2.csv >}}        |

: {tbl-colwidths="[65,35]"}
:::

#### 第14章：データハンドリング [拡張]

::: {.center-table50}
|ファイル名          |ダウンロード                    |
|:-------------------|:------------------------------:|
|`Ramen.csv`         |{{< d-btn Ramen.csv >}}         |
|`COVID19.csv`       |{{< d-btn COVID19.csv >}}       |

: {tbl-colwidths="[65,35]"}
:::

#### 第15章：整然データ構造

::: {.center-table50}
|ファイル名           |ダウンロード                     |
|:--------------------|:-------------------------------:|
|`Population2015.csv` |{{< d-btn Population2015.csv >}} |
|`COVID19_JK.csv`     |{{< d-btn COVID19_JK.csv >}}     |

: {tbl-colwidths="[65,35]"}
:::

#### 第18章：可視化 [基礎]

::: {.center-table50}
|ファイル名              |ダウンロード                        |
|:-----------------------|:----------------------------------:|
|`Countries.csv`         |{{< d-btn Countries.csv >}}         |
|`COVID19_Worldwide.csv` |{{< d-btn COVID19_Worldwide.csv >}} |

: {tbl-colwidths="[65,35]"}
:::

#### 第19章：可視化 [応用]

::: {.center-table50}
|ファイル名              |ダウンロード                        |
|:-----------------------|:----------------------------------:|
|`Countries.csv`         |{{< d-btn Countries.csv >}}         |
|`COVID19_Worldwide.csv` |{{< d-btn COVID19_Worldwide.csv >}} |

: {tbl-colwidths="[65,35]"}
:::

#### 第20章：可視化 [発展]

::: {.center-table50}
|ファイル名              |ダウンロード                        |
|:-----------------------|:----------------------------------:|
|`Countries.csv`         |{{< d-btn Countries.csv >}}         |
|`COVID19_Worldwide.csv` |{{< d-btn COVID19_Worldwide.csv >}} |
|`Japan_Density.csv`     |{{< d-btn Japan_Density.csv >}}     |
|`Osaka_Student.csv`     |{{< d-btn Osaka_Student.csv >}}     |
|`Bumpchart.csv`         |{{< d-btn Bumpchart.csv >}}         |
|`Vote_20_21.csv`        |{{< d-btn Vote_20_21.csv >}}        |

: {tbl-colwidths="[65,35]"}
:::

#### 第25章：表の作成

::: {.center-table50}
|ファイル名              |ダウンロード                        |
|:-----------------------|:----------------------------------:|
|`countries_desc1.csv`   |{{< d-btn countries_desc1.csv >}}   |
|`countries_desc2.csv`   |{{< d-btn countries_desc2.csv >}}   |
|`countries_desc3.csv`   |{{< d-btn countries_desc3.csv >}}   |

: {tbl-colwidths="[65,35]"}
:::

#### 第27章：反復処理

::: {.center-table50}
|ファイル名              |ダウンロード                        |
|:-----------------------|:----------------------------------:|
|`Countries.csv`         |{{< d-btn Countries.csv >}}         |

: {tbl-colwidths="[65,35]"}
:::