<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>11. データハンドリング [基礎編: 拡張] | 私たちのR: あなたのために書いたわけじゃない</title>
  <meta name="description" content="R Not for Everyone: It’s not for you." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="11. データハンドリング [基礎編: 拡張] | 私たちのR: あなたのために書いたわけじゃない" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="R Not for Everyone: It’s not for you." />
  <meta name="github-repo" content="JaehyunSong/RBook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="11. データハンドリング [基礎編: 拡張] | 私たちのR: あなたのために書いたわけじゃない" />
  
  <meta name="twitter:description" content="R Not for Everyone: It’s not for you." />
  

<meta name="author" content="宋財泫 (Jaehyun Song)・矢内勇生 (Yuki Yanai)" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="HTML/apple-favicon.png" />
  <link rel="shortcut icon" href="HTML/favicon.png" type="image/x-icon" />
<link rel="prev" href="datahandling1.html"/>
<link rel="next" href="factor.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-165592410-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-165592410-1');
  gtag('set', {'user_id': 'USER_ID'}); 
</script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="HTML/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">私たちのR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> 紹介</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#progress"><i class="fa fa-check"></i><b>1.1</b> 進捗状況</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#about-purpose"><i class="fa fa-check"></i><b>1.2</b> 本書の目的と対象</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#about-author"><i class="fa fa-check"></i><b>1.3</b> 著者たち</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#about-toc"><i class="fa fa-check"></i><b>1.4</b> 本書の構成</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#about-download"><i class="fa fa-check"></i><b>1.5</b> データのダウンロード</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#about-copyright"><i class="fa fa-check"></i><b>1.6</b> 著作権</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="aboutR.html"><a href="aboutR.html"><i class="fa fa-check"></i><b>2</b> R?</a><ul>
<li class="chapter" data-level="2.1" data-path="aboutR.html"><a href="aboutR.html#WhatIsR"><i class="fa fa-check"></i><b>2.1</b> Rとは</a></li>
<li class="chapter" data-level="2.2" data-path="aboutR.html"><a href="aboutR.html#WhyR"><i class="fa fa-check"></i><b>2.2</b> Why R?</a></li>
<li class="chapter" data-level="2.3" data-path="aboutR.html"><a href="aboutR.html#GUI_IDE"><i class="fa fa-check"></i><b>2.3</b> GUIとIDE</a><ul>
<li class="chapter" data-level="2.3.1" data-path="aboutR.html"><a href="aboutR.html#gui"><i class="fa fa-check"></i><b>2.3.1</b> GUI</a></li>
<li class="chapter" data-level="2.3.2" data-path="aboutR.html"><a href="aboutR.html#aboutR-IDE"><i class="fa fa-check"></i><b>2.3.2</b> IDE</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="installation.html"><a href="installation.html"><i class="fa fa-check"></i><b>3</b> Rのインストール</a><ul>
<li class="chapter" data-level="3.1" data-path="installation.html"><a href="installation.html#install-R"><i class="fa fa-check"></i><b>3.1</b> Rのインストール</a><ul>
<li class="chapter" data-level="3.1.1" data-path="installation.html"><a href="installation.html#macosの場合"><i class="fa fa-check"></i><b>3.1.1</b> macOSの場合</a></li>
<li class="chapter" data-level="3.1.2" data-path="installation.html"><a href="installation.html#linuxの場合"><i class="fa fa-check"></i><b>3.1.2</b> Linuxの場合</a></li>
<li class="chapter" data-level="3.1.3" data-path="installation.html"><a href="installation.html#windowsの場合"><i class="fa fa-check"></i><b>3.1.3</b> Windowsの場合</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="installation.html"><a href="installation.html#rbasic-profile"><i class="fa fa-check"></i><b>3.2</b> .Rprofileの設定</a></li>
<li class="chapter" data-level="3.3" data-path="installation.html"><a href="installation.html#install-rstudio"><i class="fa fa-check"></i><b>3.3</b> RStudio</a><ul>
<li class="chapter" data-level="3.3.1" data-path="installation.html"><a href="installation.html#rstudioのインストール"><i class="fa fa-check"></i><b>3.3.1</b> RStudioのインストール</a></li>
<li class="chapter" data-level="3.3.2" data-path="installation.html"><a href="installation.html#rstudioの起動と設定"><i class="fa fa-check"></i><b>3.3.2</b> RStudioの起動と設定</a></li>
<li class="chapter" data-level="3.3.3" data-path="installation.html"><a href="installation.html#rstudioの設定"><i class="fa fa-check"></i><b>3.3.3</b> RStudioの設定</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="installation.html"><a href="installation.html#install-package"><i class="fa fa-check"></i><b>3.4</b> パッケージのインストール</a><ul>
<li class="chapter" data-level="3.4.1" data-path="installation.html"><a href="installation.html#パッケージのインストール"><i class="fa fa-check"></i><b>3.4.1</b> パッケージのインストール</a></li>
<li class="chapter" data-level="3.4.2" data-path="installation.html"><a href="installation.html#パッケージの読み込み"><i class="fa fa-check"></i><b>3.4.2</b> パッケージの読み込み</a></li>
<li class="chapter" data-level="3.4.3" data-path="installation.html"><a href="installation.html#必須パッケージのインストール"><i class="fa fa-check"></i><b>3.4.3</b> 必須パッケージのインストール</a></li>
<li class="chapter" data-level="3.4.4" data-path="installation.html"><a href="installation.html#パッケージのインストールが出来ない場合-ubuntu"><i class="fa fa-check"></i><b>3.4.4</b> パッケージのインストールが出来ない場合 (Ubuntu)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="ide.html"><a href="ide.html"><i class="fa fa-check"></i><b>4</b> IDEの導入</a><ul>
<li class="chapter" data-level="4.1" data-path="ide.html"><a href="ide.html#ide-install"><i class="fa fa-check"></i><b>4.1</b> RStudioのインストールと起動</a><ul>
<li class="chapter" data-level="4.1.1" data-path="installation.html"><a href="installation.html#macosの場合"><i class="fa fa-check"></i><b>4.1.1</b> macOSの場合</a></li>
<li class="chapter" data-level="4.1.2" data-path="ide.html"><a href="ide.html#linux-ubuntuの場合"><i class="fa fa-check"></i><b>4.1.2</b> Linux (Ubuntu)の場合</a></li>
<li class="chapter" data-level="4.1.3" data-path="installation.html"><a href="installation.html#windowsの場合"><i class="fa fa-check"></i><b>4.1.3</b> Windowsの場合</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="ide.html"><a href="ide.html#ide-setting"><i class="fa fa-check"></i><b>4.2</b> RStudioの設定</a><ul>
<li class="chapter" data-level="4.2.1" data-path="ide.html"><a href="ide.html#設定画面の開き方"><i class="fa fa-check"></i><b>4.2.1</b> 設定画面の開き方</a></li>
<li class="chapter" data-level="4.2.2" data-path="ide.html"><a href="ide.html#私たちのrstudio"><i class="fa fa-check"></i><b>4.2.2</b> 私たちのRStudio</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="ide.html"><a href="ide.html#rstudio-cloudについて"><i class="fa fa-check"></i><b>4.3</b> RStudio Cloudについて</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="process.html"><a href="process.html"><i class="fa fa-check"></i><b>5</b> 分析の手順</a></li>
<li class="chapter" data-level="6" data-path="rbasic.html"><a href="rbasic.html"><i class="fa fa-check"></i><b>6</b> 基本的な操作</a><ul>
<li class="chapter" data-level="6.1" data-path="rbasic.html"><a href="rbasic.html#rbasic-project"><i class="fa fa-check"></i><b>6.1</b> 「プロジェクト」のすゝめ</a></li>
<li class="chapter" data-level="6.2" data-path="rbasic.html"><a href="rbasic.html#rbasic-calc"><i class="fa fa-check"></i><b>6.2</b> 電卓としてのR</a><ul>
<li class="chapter" data-level="6.2.1" data-path="rbasic.html"><a href="rbasic.html#算術演算子"><i class="fa fa-check"></i><b>6.2.1</b> 算術演算子</a></li>
<li class="chapter" data-level="6.2.2" data-path="rbasic.html"><a href="rbasic.html#論理演算子"><i class="fa fa-check"></i><b>6.2.2</b> 論理演算子</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="rbasic.html"><a href="rbasic.html#rbasic-input"><i class="fa fa-check"></i><b>6.3</b> 格納（代入）</a></li>
<li class="chapter" data-level="6.4" data-path="rbasic.html"><a href="rbasic.html#rbasic-extract"><i class="fa fa-check"></i><b>6.4</b> 要素の抽出</a></li>
<li class="chapter" data-level="6.5" data-path="rbasic.html"><a href="rbasic.html#rbasic-read"><i class="fa fa-check"></i><b>6.5</b> データの読み込み</a><ul>
<li class="chapter" data-level="6.5.1" data-path="rbasic.html"><a href="rbasic.html#csvファイルの場合"><i class="fa fa-check"></i><b>6.5.1</b> csvファイルの場合</a></li>
<li class="chapter" data-level="6.5.2" data-path="rbasic.html"><a href="rbasic.html#その他のフォーマット"><i class="fa fa-check"></i><b>6.5.2</b> その他のフォーマット</a></li>
<li class="chapter" data-level="6.5.3" data-path="rbasic.html"><a href="rbasic.html#rdataファイルの場合"><i class="fa fa-check"></i><b>6.5.3</b> RDataファイルの場合</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="rbasic.html"><a href="rbasic.html#rbasic-export"><i class="fa fa-check"></i><b>6.6</b> データの書き出し</a><ul>
<li class="chapter" data-level="6.6.1" data-path="rbasic.html"><a href="rbasic.html#csvファイル"><i class="fa fa-check"></i><b>6.6.1</b> csvファイル</a></li>
<li class="chapter" data-level="6.6.2" data-path="rbasic.html"><a href="rbasic.html#rdataファイル"><i class="fa fa-check"></i><b>6.6.2</b> RDataファイル</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="rbasic.html"><a href="rbasic.html#rbasic-exercise"><i class="fa fa-check"></i><b>6.7</b> 演習問題</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="datatype.html"><a href="datatype.html"><i class="fa fa-check"></i><b>7</b> データの型</a><ul>
<li class="chapter" data-level="7.1" data-path="datatype.html"><a href="datatype.html#WhatIsDatatype"><i class="fa fa-check"></i><b>7.1</b> データ型とは</a></li>
<li class="chapter" data-level="7.2" data-path="datatype.html"><a href="datatype.html#type-logical"><i class="fa fa-check"></i><b>7.2</b> Logical</a></li>
<li class="chapter" data-level="7.3" data-path="datatype.html"><a href="datatype.html#type-numeric"><i class="fa fa-check"></i><b>7.3</b> Numeric</a></li>
<li class="chapter" data-level="7.4" data-path="datatype.html"><a href="datatype.html#type-complex"><i class="fa fa-check"></i><b>7.4</b> Complex</a></li>
<li class="chapter" data-level="7.5" data-path="datatype.html"><a href="datatype.html#type-character"><i class="fa fa-check"></i><b>7.5</b> Character</a></li>
<li class="chapter" data-level="7.6" data-path="datatype.html"><a href="datatype.html#type-factor"><i class="fa fa-check"></i><b>7.6</b> Factor</a></li>
<li class="chapter" data-level="7.7" data-path="datatype.html"><a href="datatype.html#type-date"><i class="fa fa-check"></i><b>7.7</b> Date</a><ul>
<li class="chapter" data-level="7.7.1" data-path="datatype.html"><a href="datatype.html#なぜdate型があるのか"><i class="fa fa-check"></i><b>7.7.1</b> なぜDate型があるのか</a></li>
<li class="chapter" data-level="7.7.2" data-path="datatype.html"><a href="datatype.html#date型の作り方"><i class="fa fa-check"></i><b>7.7.2</b> Date型の作り方</a></li>
<li class="chapter" data-level="7.7.3" data-path="datatype.html"><a href="datatype.html#posixctposixlt型について"><i class="fa fa-check"></i><b>7.7.3</b> POSIXct、POSIXlt型について</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="datatype.html"><a href="datatype.html#type-na"><i class="fa fa-check"></i><b>7.8</b> NA</a></li>
<li class="chapter" data-level="7.9" data-path="datatype.html"><a href="datatype.html#type-null"><i class="fa fa-check"></i><b>7.9</b> NULL</a></li>
<li class="chapter" data-level="7.10" data-path="datatype.html"><a href="datatype.html#type-nan"><i class="fa fa-check"></i><b>7.10</b> NaN</a></li>
<li class="chapter" data-level="7.11" data-path="datatype.html"><a href="datatype.html#type-inf"><i class="fa fa-check"></i><b>7.11</b> Inf</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="datastructure.html"><a href="datastructure.html"><i class="fa fa-check"></i><b>8</b> データの構造</a><ul>
<li class="chapter" data-level="8.1" data-path="datastructure.html"><a href="datastructure.html#WhatIsDatastructure"><i class="fa fa-check"></i><b>8.1</b> データ構造とは</a></li>
<li class="chapter" data-level="8.2" data-path="datastructure.html"><a href="datastructure.html#structure-vector"><i class="fa fa-check"></i><b>8.2</b> ベクトル (vector)</a><ul>
<li class="chapter" data-level="8.2.1" data-path="datastructure.html"><a href="datastructure.html#ベクトルの作り方"><i class="fa fa-check"></i><b>8.2.1</b> ベクトルの作り方</a></li>
<li class="chapter" data-level="8.2.2" data-path="datastructure.html"><a href="datastructure.html#ベクトルの操作"><i class="fa fa-check"></i><b>8.2.2</b> ベクトルの操作</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="datastructure.html"><a href="datastructure.html#structure-matrix"><i class="fa fa-check"></i><b>8.3</b> 行列 (matrix)</a><ul>
<li class="chapter" data-level="8.3.1" data-path="datastructure.html"><a href="datastructure.html#行列の作り方"><i class="fa fa-check"></i><b>8.3.1</b> 行列の作り方</a></li>
<li class="chapter" data-level="8.3.2" data-path="datastructure.html"><a href="datastructure.html#行列の操作"><i class="fa fa-check"></i><b>8.3.2</b> 行列の操作</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="datastructure.html"><a href="datastructure.html#structure-dataframe"><i class="fa fa-check"></i><b>8.4</b> データフレーム (data.frame)</a><ul>
<li class="chapter" data-level="8.4.1" data-path="datastructure.html"><a href="datastructure.html#データフレームの作成"><i class="fa fa-check"></i><b>8.4.1</b> データフレームの作成</a></li>
<li class="chapter" data-level="8.4.2" data-path="datastructure.html"><a href="datastructure.html#データフレームの操作"><i class="fa fa-check"></i><b>8.4.2</b> データフレームの操作</a></li>
<li class="chapter" data-level="8.4.3" data-path="datastructure.html"><a href="datastructure.html#tibble型"><i class="fa fa-check"></i><b>8.4.3</b> tibble型</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="datastructure.html"><a href="datastructure.html#structure-list"><i class="fa fa-check"></i><b>8.5</b> リスト (list)</a><ul>
<li class="chapter" data-level="8.5.1" data-path="datastructure.html"><a href="datastructure.html#リスト型データの作成"><i class="fa fa-check"></i><b>8.5.1</b> リスト型データの作成</a></li>
<li class="chapter" data-level="8.5.2" data-path="datastructure.html"><a href="datastructure.html#リスト型データの操作"><i class="fa fa-check"></i><b>8.5.2</b> リスト型データの操作</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="datastructure.html"><a href="datastructure.html#structure-array"><i class="fa fa-check"></i><b>8.6</b> 配列 (array)</a><ul>
<li class="chapter" data-level="8.6.1" data-path="datastructure.html"><a href="datastructure.html#配列型データの作成"><i class="fa fa-check"></i><b>8.6.1</b> 配列型データの作成</a></li>
<li class="chapter" data-level="8.6.2" data-path="datastructure.html"><a href="datastructure.html#配列型データの操作"><i class="fa fa-check"></i><b>8.6.2</b> 配列型データの操作</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="datastructure.html"><a href="datastructure.html#structure-exercise"><i class="fa fa-check"></i><b>8.7</b> 練習問題</a><ul>
<li class="chapter" data-level="8.7.1" data-path="datastructure.html"><a href="datastructure.html#ベクトル"><i class="fa fa-check"></i><b>8.7.1</b> ベクトル</a></li>
<li class="chapter" data-level="8.7.2" data-path="datastructure.html"><a href="datastructure.html#行列"><i class="fa fa-check"></i><b>8.7.2</b> 行列</a></li>
<li class="chapter" data-level="8.7.3" data-path="datastructure.html"><a href="datastructure.html#データフレーム"><i class="fa fa-check"></i><b>8.7.3</b> データフレーム</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="programming.html"><a href="programming.html"><i class="fa fa-check"></i><b>9</b> Rプログラミングの基礎</a><ul>
<li class="chapter" data-level="9.1" data-path="programming.html"><a href="programming.html#programming-intro"><i class="fa fa-check"></i><b>9.1</b> R言語の基礎概念</a></li>
<li class="chapter" data-level="9.2" data-path="programming.html"><a href="programming.html#programming-style"><i class="fa fa-check"></i><b>9.2</b> スクリプトの書き方</a><ul>
<li class="chapter" data-level="9.2.1" data-path="programming.html"><a href="programming.html#オブジェクト名"><i class="fa fa-check"></i><b>9.2.1</b> オブジェクト名</a></li>
<li class="chapter" data-level="9.2.2" data-path="programming.html"><a href="programming.html#改行"><i class="fa fa-check"></i><b>9.2.2</b> 改行</a></li>
<li class="chapter" data-level="9.2.3" data-path="programming.html"><a href="programming.html#スペースとインデント"><i class="fa fa-check"></i><b>9.2.3</b> スペースとインデント</a></li>
<li class="chapter" data-level="9.2.4" data-path="programming.html"><a href="programming.html#代入"><i class="fa fa-check"></i><b>9.2.4</b> 代入</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="programming.html"><a href="programming.html#programming-iteration"><i class="fa fa-check"></i><b>9.3</b> 反復</a><ul>
<li class="chapter" data-level="9.3.1" data-path="programming.html"><a href="programming.html#forによる反復"><i class="fa fa-check"></i><b>9.3.1</b> <code>for()</code>による反復</a></li>
<li class="chapter" data-level="9.3.2" data-path="programming.html"><a href="programming.html#whileによる反復"><i class="fa fa-check"></i><b>9.3.2</b> <code>while()</code>による反復</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="programming.html"><a href="programming.html#programming-condition"><i class="fa fa-check"></i><b>9.4</b> 条件分岐</a><ul>
<li class="chapter" data-level="9.4.1" data-path="programming.html"><a href="programming.html#ifelse-ifelseによる条件分岐"><i class="fa fa-check"></i><b>9.4.1</b> <code>if()</code>、<code>else if()</code>、<code>else()</code>による条件分岐</a></li>
<li class="chapter" data-level="9.4.2" data-path="programming.html"><a href="programming.html#ifelseによる条件分岐"><i class="fa fa-check"></i><b>9.4.2</b> <code>ifelse()</code>による条件分岐</a></li>
<li class="chapter" data-level="9.4.3" data-path="programming.html"><a href="programming.html#switchによる条件分岐"><i class="fa fa-check"></i><b>9.4.3</b> <code>switch()</code>による条件分岐</a></li>
<li class="chapter" data-level="9.4.4" data-path="programming.html"><a href="programming.html#上級者向け"><i class="fa fa-check"></i><b>9.4.4</b> 上級者向け</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="programming.html"><a href="programming.html#programming-function"><i class="fa fa-check"></i><b>9.5</b> 関数の作成</a><ul>
<li class="chapter" data-level="9.5.1" data-path="programming.html"><a href="programming.html#関数-in-関数"><i class="fa fa-check"></i><b>9.5.1</b> 関数 in 関数</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="programming.html"><a href="programming.html#programming-exercise"><i class="fa fa-check"></i><b>9.6</b> 練習問題</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="datahandling1.html"><a href="datahandling1.html"><i class="fa fa-check"></i><b>10</b> データハンドリング [基礎編: 抽出]</a><ul>
<li class="chapter" data-level="10.1" data-path="datahandling1.html"><a href="datahandling1.html#handling1-intro"><i class="fa fa-check"></i><b>10.1</b> データハンドリングとtidyverse</a></li>
<li class="chapter" data-level="10.2" data-path="datahandling1.html"><a href="datahandling1.html#handling1-pipe"><i class="fa fa-check"></i><b>10.2</b> パイプ演算子 (<code>%&gt;%</code>)</a></li>
<li class="chapter" data-level="10.3" data-path="datahandling1.html"><a href="datahandling1.html#handling1-select"><i class="fa fa-check"></i><b>10.3</b> 列の抽出</a><ul>
<li class="chapter" data-level="10.3.1" data-path="datahandling1.html"><a href="datahandling1.html#特定の列を抽出する"><i class="fa fa-check"></i><b>10.3.1</b> 特定の列を抽出する</a></li>
<li class="chapter" data-level="10.3.2" data-path="datahandling1.html"><a href="datahandling1.html#特定の列を抽出し列名を変更する"><i class="fa fa-check"></i><b>10.3.2</b> 特定の列を抽出し、列名を変更する</a></li>
<li class="chapter" data-level="10.3.3" data-path="datahandling1.html"><a href="datahandling1.html#特定の列を除外する"><i class="fa fa-check"></i><b>10.3.3</b> 特定の列を除外する</a></li>
<li class="chapter" data-level="10.3.4" data-path="datahandling1.html"><a href="datahandling1.html#隣接した列を指定する"><i class="fa fa-check"></i><b>10.3.4</b> 隣接した列を指定する</a></li>
<li class="chapter" data-level="10.3.5" data-path="datahandling1.html"><a href="datahandling1.html#一部の列の順番だけを変える"><i class="fa fa-check"></i><b>10.3.5</b> 一部の列の順番だけを変える</a></li>
<li class="chapter" data-level="10.3.6" data-path="datahandling1.html"><a href="datahandling1.html#selectの便利な機能"><i class="fa fa-check"></i><b>10.3.6</b> <code>select()</code>の便利な機能</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="datahandling1.html"><a href="datahandling1.html#handling1-filter"><i class="fa fa-check"></i><b>10.4</b> 行の抽出</a><ul>
<li class="chapter" data-level="10.4.1" data-path="datahandling1.html"><a href="datahandling1.html#指定した行を抽出する"><i class="fa fa-check"></i><b>10.4.1</b> 指定した行を抽出する</a></li>
<li class="chapter" data-level="10.4.2" data-path="datahandling1.html"><a href="datahandling1.html#条件に合致する行を抽出する"><i class="fa fa-check"></i><b>10.4.2</b> 条件に合致する行を抽出する</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="datahandling1.html"><a href="datahandling1.html#handling1-arrange"><i class="fa fa-check"></i><b>10.5</b> 行のソート</a></li>
<li class="chapter" data-level="10.6" data-path="datahandling1.html"><a href="datahandling1.html#handling1-exercise"><i class="fa fa-check"></i><b>10.6</b> 練習問題</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="datahandling2.html"><a href="datahandling2.html"><i class="fa fa-check"></i><b>11</b> データハンドリング [基礎編: 拡張]</a><ul>
<li class="chapter" data-level="11.1" data-path="datahandling2.html"><a href="datahandling2.html#handling2-summarise"><i class="fa fa-check"></i><b>11.1</b> 記述統計量の計算</a><ul>
<li class="chapter" data-level="11.1.1" data-path="datahandling2.html"><a href="datahandling2.html#summariseによる記述統計量の計算"><i class="fa fa-check"></i><b>11.1.1</b> <code>summarise()</code>による記述統計量の計算</a></li>
<li class="chapter" data-level="11.1.2" data-path="datahandling2.html"><a href="datahandling2.html#summariseに使える便利な関数"><i class="fa fa-check"></i><b>11.1.2</b> <code>summarise()</code>に使える便利な関数</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="datahandling2.html"><a href="datahandling2.html#handling2-group"><i class="fa fa-check"></i><b>11.2</b> グルーピング</a><ul>
<li class="chapter" data-level="11.2.1" data-path="datahandling2.html"><a href="datahandling2.html#group_byによるグループ化"><i class="fa fa-check"></i><b>11.2.1</b> <code>group_by()</code>によるグループ化</a></li>
<li class="chapter" data-level="11.2.2" data-path="datahandling2.html"><a href="datahandling2.html#複数の変数を用いたグループ化"><i class="fa fa-check"></i><b>11.2.2</b> 複数の変数を用いたグループ化</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="datahandling2.html"><a href="datahandling2.html#handling2-mutate"><i class="fa fa-check"></i><b>11.3</b> 変数の計算</a><ul>
<li class="chapter" data-level="11.3.1" data-path="datahandling2.html"><a href="datahandling2.html#mutate関数の使い方"><i class="fa fa-check"></i><b>11.3.1</b> <code>mutate()</code>関数の使い方</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="datahandling2.html"><a href="datahandling2.html#handling2-rowwise"><i class="fa fa-check"></i><b>11.4</b> 行単位の操作</a></li>
<li class="chapter" data-level="11.5" data-path="datahandling2.html"><a href="datahandling2.html#handling2-merge"><i class="fa fa-check"></i><b>11.5</b> データの結合</a><ul>
<li class="chapter" data-level="11.5.1" data-path="datahandling2.html"><a href="datahandling2.html#行の結合"><i class="fa fa-check"></i><b>11.5.1</b> 行の結合</a></li>
<li class="chapter" data-level="11.5.2" data-path="datahandling2.html"><a href="datahandling2.html#列の結合"><i class="fa fa-check"></i><b>11.5.2</b> 列の結合</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="datahandling2.html"><a href="datahandling2.html#handling2-exercise"><i class="fa fa-check"></i><b>11.6</b> 練習問題</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="factor.html"><a href="factor.html"><i class="fa fa-check"></i><b>12</b> データハンドリング [基礎編: factor型]</a><ul>
<li class="chapter" data-level="12.1" data-path="factor.html"><a href="factor.html#名目変数を含むグラフを作成する際の注意点"><i class="fa fa-check"></i><b>12.1</b> 名目変数を含むグラフを作成する際の注意点</a></li>
<li class="chapter" data-level="12.2" data-path="factor.html"><a href="factor.html#forcatsパッケージについて"><i class="fa fa-check"></i><b>12.2</b> <code>forcats</code>パッケージについて</a><ul>
<li class="chapter" data-level="12.2.1" data-path="factor.html"><a href="factor.html#fct_relevel-水準の順番を変更する"><i class="fa fa-check"></i><b>12.2.1</b> <code>fct_relevel()</code>: 水準の順番を変更する</a></li>
<li class="chapter" data-level="12.2.2" data-path="factor.html"><a href="factor.html#fct_recode-水準のラベルを変更する"><i class="fa fa-check"></i><b>12.2.2</b> <code>fct_recode()</code>: 水準のラベルを変更する</a></li>
<li class="chapter" data-level="12.2.3" data-path="factor.html"><a href="factor.html#fct_rev-水準の順番を反転させる"><i class="fa fa-check"></i><b>12.2.3</b> <code>fct_rev()</code>: 水準の順番を反転させる</a></li>
<li class="chapter" data-level="12.2.4" data-path="factor.html"><a href="factor.html#fct_infreq-頻度順に順番を変更する"><i class="fa fa-check"></i><b>12.2.4</b> <code>fct_infreq()</code>: 頻度順に順番を変更する</a></li>
<li class="chapter" data-level="12.2.5" data-path="factor.html"><a href="factor.html#fct_inorder-データ内の出現順番に順番を変更する"><i class="fa fa-check"></i><b>12.2.5</b> <code>fct_inorder()</code>: データ内の出現順番に順番を変更する</a></li>
<li class="chapter" data-level="12.2.6" data-path="factor.html"><a href="factor.html#fct_shift-水準の順番をずらす"><i class="fa fa-check"></i><b>12.2.6</b> <code>fct_shift()</code>: 水準の順番をずらす</a></li>
<li class="chapter" data-level="12.2.7" data-path="factor.html"><a href="factor.html#fct_shuffle-水準の順番をランダム化する"><i class="fa fa-check"></i><b>12.2.7</b> <code>fct_shuffle()</code>: 水準の順番をランダム化する</a></li>
<li class="chapter" data-level="12.2.8" data-path="factor.html"><a href="factor.html#fct_reorder-別の1変数の値を基準に水準の順番を変更する"><i class="fa fa-check"></i><b>12.2.8</b> <code>fct_reorder()</code>: 別の1変数の値を基準に水準の順番を変更する</a></li>
<li class="chapter" data-level="12.2.9" data-path="factor.html"><a href="factor.html#fct_reorder2-別の2変数の値を基準に水準の順番を変更する"><i class="fa fa-check"></i><b>12.2.9</b> <code>fct_reorder2()</code>: 別の2変数の値を基準に水準の順番を変更する</a></li>
<li class="chapter" data-level="12.2.10" data-path="factor.html"><a href="factor.html#fct_collapse-水準を統合する"><i class="fa fa-check"></i><b>12.2.10</b> <code>fct_collapse()</code>: 水準を統合する</a></li>
<li class="chapter" data-level="12.2.11" data-path="factor.html"><a href="factor.html#fct_drop-使われていない水準を除去する"><i class="fa fa-check"></i><b>12.2.11</b> <code>fct_drop()</code>: 使われていない水準を除去する</a></li>
<li class="chapter" data-level="12.2.12" data-path="factor.html"><a href="factor.html#fct_expand-水準を追加する"><i class="fa fa-check"></i><b>12.2.12</b> <code>fct_expand()</code>: 水準を追加する</a></li>
<li class="chapter" data-level="12.2.13" data-path="factor.html"><a href="factor.html#fct_explicit_na-欠損値に水準を与える"><i class="fa fa-check"></i><b>12.2.13</b> <code>fct_explicit_na()</code>: 欠損値に水準を与える</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="factor.html"><a href="factor.html#factor-excersie"><i class="fa fa-check"></i><b>12.3</b> 練習問題</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="tidydata.html"><a href="tidydata.html"><i class="fa fa-check"></i><b>13</b> 簡潔データ構造</a><ul>
<li class="chapter" data-level="13.1" data-path="tidydata.html"><a href="tidydata.html#tidydata-intro"><i class="fa fa-check"></i><b>13.1</b> 簡潔データ (tidy data)とは</a></li>
<li class="chapter" data-level="13.2" data-path="tidydata.html"><a href="tidydata.html#tidydata-gather"><i class="fa fa-check"></i><b>13.2</b> Wide型からLong型へ</a></li>
<li class="chapter" data-level="13.3" data-path="tidydata.html"><a href="tidydata.html#tidydata-spread"><i class="fa fa-check"></i><b>13.3</b> Long型からWide型へ</a></li>
<li class="chapter" data-level="13.4" data-path="tidydata.html"><a href="tidydata.html#tidydata-separate"><i class="fa fa-check"></i><b>13.4</b> 列の分割</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="visualization.html"><a href="visualization.html"><i class="fa fa-check"></i><b>14</b> 可視化</a><ul>
<li class="chapter" data-level="14.1" data-path="visualization.html"><a href="visualization.html#visual-packages"><i class="fa fa-check"></i><b>14.1</b> 可視化のためのパッケージ</a></li>
<li class="chapter" data-level="14.2" data-path="visualization.html"><a href="visualization.html#visual-principal"><i class="fa fa-check"></i><b>14.2</b> 良いグラフとは</a></li>
<li class="chapter" data-level="14.3" data-path="visualization.html"><a href="visualization.html#visual-ggplot"><i class="fa fa-check"></i><b>14.3</b> グラフィックの文法</a></li>
<li class="chapter" data-level="14.4" data-path="visualization.html"><a href="visualization.html#visual-data"><i class="fa fa-check"></i><b>14.4</b> 実習用データ</a></li>
<li class="chapter" data-level="14.5" data-path="visualization.html"><a href="visualization.html#visual-barplot"><i class="fa fa-check"></i><b>14.5</b> 棒グラフ</a></li>
<li class="chapter" data-level="14.6" data-path="visualization.html"><a href="visualization.html#visual-histogram"><i class="fa fa-check"></i><b>14.6</b> ヒストグラム</a></li>
<li class="chapter" data-level="14.7" data-path="visualization.html"><a href="visualization.html#visual-scatter"><i class="fa fa-check"></i><b>14.7</b> 散布図</a></li>
<li class="chapter" data-level="14.8" data-path="visualization.html"><a href="visualization.html#visual-customize"><i class="fa fa-check"></i><b>14.8</b> 図のカスタマイズ</a></li>
<li class="chapter" data-level="14.9" data-path="visualization.html"><a href="visualization.html#visual-excersie"><i class="fa fa-check"></i><b>14.9</b> 練習問題</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="datahandling3.html"><a href="datahandling3.html"><i class="fa fa-check"></i><b>15</b> データハンドリング[応用編]</a></li>
<li class="chapter" data-level="16" data-path="string.html"><a href="string.html"><i class="fa fa-check"></i><b>16</b> 文字列の処理</a></li>
<li class="chapter" data-level="17" data-path="scraping.html"><a href="scraping.html"><i class="fa fa-check"></i><b>17</b> スクレイピング</a></li>
<li class="chapter" data-level="18" data-path="rmarkdown.html"><a href="rmarkdown.html"><i class="fa fa-check"></i><b>18</b> R Markdown</a><ul>
<li class="chapter" data-level="18.1" data-path="rmarkdown.html"><a href="rmarkdown.html#rmarkdown-intro"><i class="fa fa-check"></i><b>18.1</b> R Markdown</a></li>
<li class="chapter" data-level="18.2" data-path="rmarkdown.html"><a href="rmarkdown.html#rmarkdown-grammar"><i class="fa fa-check"></i><b>18.2</b> Markdown文法の基本</a></li>
<li class="chapter" data-level="18.3" data-path="rmarkdown.html"><a href="rmarkdown.html#rmarkdown-chunk"><i class="fa fa-check"></i><b>18.3</b> チャンクのオプション</a></li>
<li class="chapter" data-level="18.4" data-path="rmarkdown.html"><a href="rmarkdown.html#rmarkdown-header"><i class="fa fa-check"></i><b>18.4</b> ヘッダーのオプション</a></li>
<li class="chapter" data-level="18.5" data-path="rmarkdown.html"><a href="rmarkdown.html#rmarkdown-japanese"><i class="fa fa-check"></i><b>18.5</b> 日本語が含まれているPDFの出力</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="solution.html"><a href="solution.html"><i class="fa fa-check"></i><b>19</b> 演習問題の回答</a><ul>
<li class="chapter" data-level="19.1" data-path="solution.html"><a href="solution.html#solution-rbasic"><i class="fa fa-check"></i><b>19.1</b> 基本的な操作</a></li>
<li class="chapter" data-level="19.2" data-path="solution.html"><a href="solution.html#solution-datastructure"><i class="fa fa-check"></i><b>19.2</b> データの構造</a><ul>
<li class="chapter" data-level="19.2.1" data-path="datastructure.html"><a href="datastructure.html#ベクトル"><i class="fa fa-check"></i><b>19.2.1</b> ベクトル</a></li>
<li class="chapter" data-level="19.2.2" data-path="datastructure.html"><a href="datastructure.html#行列"><i class="fa fa-check"></i><b>19.2.2</b> 行列</a></li>
<li class="chapter" data-level="19.2.3" data-path="datastructure.html"><a href="datastructure.html#データフレーム"><i class="fa fa-check"></i><b>19.2.3</b> データフレーム</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="solution.html"><a href="solution.html#rプログラミングの基礎"><i class="fa fa-check"></i><b>19.3</b> Rプログラミングの基礎</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="sessioninfo.html"><a href="sessioninfo.html"><i class="fa fa-check"></i><b>20</b> 本書の執筆環境</a></li>
<li class="chapter" data-level="21" data-path="reference.html"><a href="reference.html"><i class="fa fa-check"></i><b>21</b> 参考資料</a></li>
<li class="divider"></li>
<p style = "text-align:center;"><a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="クリエイティブ・コモンズ・ライセンス" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a></p>
<p style = "text-align:center;"><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></p>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">私たちのR: あなたのために書いたわけじゃない</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="datahandling2" class="section level1">
<h1><span class="header-section-number">11.</span> データハンドリング [基礎編: 拡張]</h1>
<p>前章ではデータの一部 (subset)を抽出する方法について説明しましたが、本章はデータを拡張する、あるいは全く別のデータが得られるような処理について解説します。後者は主に元のデータを要約し (記述統計量)、その結果を出力する方法で、前者はデータ内の変数に基づき、指定された計算を行った結果を新しい列として追加する方法です。今回も<a href="Data/Ramen.csv">前章と同じデータ</a>を使用します。</p>
<div class="sourceCode" id="cb843"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb843-1"><a href="datahandling2.html#cb843-1"></a><span class="co"># データのパスは適宜修正すること</span></span>
<span id="cb843-2"><a href="datahandling2.html#cb843-2"></a><span class="co"># 文字化けが生じる場合、以下のコードに書き換える。</span></span>
<span id="cb843-3"><a href="datahandling2.html#cb843-3"></a><span class="co"># df &lt;- read_csv(&quot;Data/Ramen.csv&quot;, locale = locale(encoding = &quot;utf8&quot;))</span></span>
<span id="cb843-4"><a href="datahandling2.html#cb843-4"></a>df &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;Data/Ramen.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   ID = col_character(),
##   Name = col_character(),
##   Pref = col_character(),
##   Zipcode = col_double(),
##   Latitude = col_double(),
##   Longitude = col_double(),
##   Line = col_character(),
##   Station = col_character(),
##   Walk = col_double(),
##   Bus = col_double(),
##   Car = col_double(),
##   Budget = col_double(),
##   ScoreN = col_double(),
##   Score = col_double()
## )</code></pre>
<p>データの詳細については第<a href="datahandling1.html#handling1-select">10.3</a>章を参照してください。</p>
<hr />
<div id="handling2-summarise" class="section level2">
<h2><span class="header-section-number">11.1</span> 記述統計量の計算</h2>
<div id="summariseによる記述統計量の計算" class="section level3">
<h3><span class="header-section-number">11.1.1</span> <code>summarise()</code>による記述統計量の計算</h3>
<p>ある変数の平均値や標準偏差、最小値、最大値などの記述統計量 (要約統計量)を計算することも可能です。これは<code>summarize()</code>または<code>summarise()</code>関数を使いますが、この関数は後で紹介する<code>group_by()</code>関数と組み合わせることで力を発揮します。ここではグルーピングを考えずに、全データの記述統計量を計算する方法を紹介します。</p>
<p><code>summarise()</code>関数の使い方は以下の通りです。</p>
<div class="sourceCode" id="cb845"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb845-1"><a href="datahandling2.html#cb845-1"></a><span class="co"># summarise()関数の使い方</span></span>
<span id="cb845-2"><a href="datahandling2.html#cb845-2"></a>データフレーム名 <span class="op">%&gt;%</span></span>
<span id="cb845-3"><a href="datahandling2.html#cb845-3"></a><span class="st">  </span><span class="kw">summarise</span>(新しい変数名 =<span class="st"> </span>関数名(計算の対象となる変数名))</span></code></pre></div>
<p>もし、<code>Score</code>変数の平均値を計算し、その結果を<code>Mean</code>という列にしたい場合は以下のようなコードになります。</p>
<div class="sourceCode" id="cb846"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb846-1"><a href="datahandling2.html#cb846-1"></a>df <span class="op">%&gt;%</span></span>
<span id="cb846-2"><a href="datahandling2.html#cb846-2"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Mean =</span> <span class="kw">mean</span>(Score))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##    Mean
##   &lt;dbl&gt;
## 1    NA</code></pre>
<p>ただし、<code>mean()</code>関数は欠損値が含まれるベクトルの場合、<code>NA</code>を返します。この場合方法は2つ考えられます。</p>
<ol style="list-style-type: decimal">
<li><code>filter()</code>関数を使って<code>Score</code>が欠損しているケースを予め除去する。</li>
<li><code>na.rm</code>引数を指定し、欠損値を除去した平均値を求める。</li>
</ol>
<p>ここでは2番目の方法を使います。</p>
<div class="sourceCode" id="cb848"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb848-1"><a href="datahandling2.html#cb848-1"></a>df <span class="op">%&gt;%</span></span>
<span id="cb848-2"><a href="datahandling2.html#cb848-2"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Mean =</span> <span class="kw">mean</span>(Score, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##    Mean
##   &lt;dbl&gt;
## 1  3.66</code></pre>
<p><code>df</code>の<code>Score</code>変数の平均値はNAであることが分かります。また、<code>summarise()</code>関数は複数の記述統計量を同時に計算することも可能です。以下は<code>Score</code>変数の平均値、中央値、標準偏差、最小値、最大値、第一四分位点、第三四分位点を計算し、<code>Score.Desc</code>という名のデータフレームに格納するコードです。</p>
<div class="sourceCode" id="cb850"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb850-1"><a href="datahandling2.html#cb850-1"></a>Score.Desc &lt;-<span class="st"> </span>df <span class="op">%&gt;%</span></span>
<span id="cb850-2"><a href="datahandling2.html#cb850-2"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">Mean   =</span>     <span class="kw">mean</span>(Score,       <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),  <span class="co"># 平均値</span></span>
<span id="cb850-3"><a href="datahandling2.html#cb850-3"></a>            <span class="dt">Median =</span>   <span class="kw">median</span>(Score,       <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),  <span class="co"># 中央値</span></span>
<span id="cb850-4"><a href="datahandling2.html#cb850-4"></a>            <span class="dt">SD     =</span>       <span class="kw">sd</span>(Score,       <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),  <span class="co"># 標準偏差</span></span>
<span id="cb850-5"><a href="datahandling2.html#cb850-5"></a>            <span class="dt">Min    =</span>      <span class="kw">min</span>(Score,       <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),  <span class="co"># 最小値</span></span>
<span id="cb850-6"><a href="datahandling2.html#cb850-6"></a>            <span class="dt">Max    =</span>      <span class="kw">max</span>(Score,       <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),  <span class="co"># 最大値</span></span>
<span id="cb850-7"><a href="datahandling2.html#cb850-7"></a>            <span class="dt">Q1     =</span> <span class="kw">quantile</span>(Score, <span class="fl">0.25</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),  <span class="co"># 第一四分位点</span></span>
<span id="cb850-8"><a href="datahandling2.html#cb850-8"></a>            <span class="dt">Q3     =</span> <span class="kw">quantile</span>(Score, <span class="fl">0.75</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))  <span class="co"># 第三四分位点</span></span></code></pre></div>
<div class="sourceCode" id="cb851"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb851-1"><a href="datahandling2.html#cb851-1"></a>Score.Desc</span></code></pre></div>
<pre><code>## # A tibble: 1 x 7
##    Mean Median    SD   Min   Max    Q1    Q3
##   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  3.66   3.58 0.719     1     5     3     4</code></pre>
<p>むろん、複数の変数に対して記述統計量を計算することも可能です。たとえば、平均予算 (<code>Budget</code>)、口コミ数 (<code>ScoreN</code>)、口コミ評価 (<code>Score</code>)の平均値を求めるとしたら、</p>
<div class="sourceCode" id="cb853"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb853-1"><a href="datahandling2.html#cb853-1"></a>df <span class="op">%&gt;%</span></span>
<span id="cb853-2"><a href="datahandling2.html#cb853-2"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">Budget_Mean =</span> <span class="kw">mean</span>(Budget, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="co"># 平均予算の平均値</span></span>
<span id="cb853-3"><a href="datahandling2.html#cb853-3"></a>            <span class="dt">SocreN_Mean =</span> <span class="kw">mean</span>(ScoreN, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="co"># 口コミ数の平均値</span></span>
<span id="cb853-4"><a href="datahandling2.html#cb853-4"></a>            <span class="dt">Score_Mean  =</span> <span class="kw">mean</span>(Score,  <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)) <span class="co"># 評価の平均値</span></span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   Budget_Mean SocreN_Mean Score_Mean
##         &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;
## 1       1232.       0.537       3.66</code></pre>
<p>のように書きます。実は<code>summarise()</code>はこれくらいで十分便利です。ただし、以上の操作はもっと簡単なコードに置換できます。ただし、ラムダ式など、やや高度な内容になるため、以下の内容は飛ばして、次の節 (グルーピング)を読んでいただいても構いません。</p>
<p>まずは、複数の変数に対して同じ記述統計量を求める例を考えてみましょう。たとえば、<code>Budget</code>、<code>ScoreN</code>、<code>Score</code>に対して平均値を求める例です。これは<code>across()</code>関数を使うとよりコードが短くなります。まずは<code>across()</code>関数の書き方から見ましょう。</p>
<div class="sourceCode" id="cb855"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb855-1"><a href="datahandling2.html#cb855-1"></a><span class="co"># across()の使い方</span></span>
<span id="cb855-2"><a href="datahandling2.html#cb855-2"></a>データフレーム名 <span class="op">%&gt;%</span></span>
<span id="cb855-3"><a href="datahandling2.html#cb855-3"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="kw">across</span>(変数名のベクトル, 記述統計を計算する関数名, 関数の引数))</span></code></pre></div>
<p><em>変数名のベクトル</em>は長さ1以上のベクトルです。たとえば、<code>Budget</code>、<code>ScoreN</code>、<code>Score</code>の場合<code>c(Budget, ScoreN, Score)</code>になります。これは<code>df</code>内で隣接する変数ですから<code>Budget:Score</code>の書き方も使えます。また、<code>where()</code>や<code>any_of()</code>、<code>starts_with()</code>のような関数を使って変数を指定することも可能です。<em>関数名</em>は<code>mean</code>や<code>sd</code>などの関数名です。ここは<code>関数名()</code>でななく、<code>関数名</code>であることに注意してください。<em>引数</em>は前の関数に必要な引数です。引数を必要としない関数なら省略可能ですが、<code>na.rm = TRUE</code>などの引数が必要な場合は指定する必要があります。それでは<code>Budget</code>、<code>ScoreN</code>、<code>Score</code>の平均値を計算してみましょう。</p>
<div class="sourceCode" id="cb856"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb856-1"><a href="datahandling2.html#cb856-1"></a>df <span class="op">%&gt;%</span></span>
<span id="cb856-2"><a href="datahandling2.html#cb856-2"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="kw">across</span>(Budget<span class="op">:</span>Score, mean, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   Budget ScoreN Score
##    &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
## 1  1232.  0.537  3.66</code></pre>
<p><code>across()</code>使わない場合、4行必要だったコードが2行になりました。変数が少ない場合は<code>across()</code>を使わない方が、可読性が高くなる場合もあります。しかし、変数が多くなる場合、可読性がやや落ちても<code>across()</code>を使った方が効率的でしょう。</p>
<p>次は、ある変数に対して複数の記述統計量を計算したい場合について考えます。<code>Budget</code>、<code>ScoreN</code>、<code>Score</code>変数の第一四分位点と第三四分位点を<code>across()</code>を使わずに計算すると家のような7行のコードになります。</p>
<div class="sourceCode" id="cb858"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb858-1"><a href="datahandling2.html#cb858-1"></a>df <span class="op">%&gt;%</span></span>
<span id="cb858-2"><a href="datahandling2.html#cb858-2"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">Budget_Q1 =</span> <span class="kw">quantile</span>(Budget, <span class="fl">0.25</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb858-3"><a href="datahandling2.html#cb858-3"></a>            <span class="dt">Budget_Q3 =</span> <span class="kw">quantile</span>(Budget, <span class="fl">0.75</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb858-4"><a href="datahandling2.html#cb858-4"></a>            <span class="dt">ScoreN_Q1 =</span> <span class="kw">quantile</span>(ScoreN, <span class="fl">0.25</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb858-5"><a href="datahandling2.html#cb858-5"></a>            <span class="dt">ScoreN_Q3 =</span> <span class="kw">quantile</span>(ScoreN, <span class="fl">0.75</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb858-6"><a href="datahandling2.html#cb858-6"></a>            <span class="dt">Score_Q1  =</span> <span class="kw">quantile</span>(Score,  <span class="fl">0.25</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb858-7"><a href="datahandling2.html#cb858-7"></a>            <span class="dt">Score_Q3  =</span> <span class="kw">quantile</span>(Score,  <span class="fl">0.75</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 6
##   Budget_Q1 Budget_Q3 ScoreN_Q1 ScoreN_Q3 Score_Q1 Score_Q3
##       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1       800      1000         0         0        3        4</code></pre>
<p>この作業も<code>across()</code>を使ってより短縮することができます。ここではラムダ式の知識が必要になります。ラムダ関数とは関数名を持たない<a href="https://ja.wikipedia.org/wiki/無名関数">無名関数 (anonymous functions)</a>を意味しますが、詳細は割愛します。興味のある読者は<a href="https://ja.wikipedia.org/wiki/無名関数">Wikipedia</a>などを参照してください。簡単にいうとその場で即席に関数を作成し、計算が終わったら破棄する関数です。ただ、Rは基本的にラムダ式を提供しているのではなく、<code>purrr</code>パッケージのラムダ式スタイルを使用します。まずは、書き方から確認します。</p>
<div class="sourceCode" id="cb860"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb860-1"><a href="datahandling2.html#cb860-1"></a><span class="co"># ラムダ式を用いたacross()の使い方</span></span>
<span id="cb860-2"><a href="datahandling2.html#cb860-2"></a>データフレーム名 <span class="op">%&gt;%</span></span>
<span id="cb860-3"><a href="datahandling2.html#cb860-3"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="kw">across</span>(変数名のベクトル, <span class="kw">list</span>(結果の変数名 =<span class="st"> </span>ラムダ式)))</span></code></pre></div>
<p>先ほどの書き方と似ていますが、関数を複数書く必要があるため、今回は関数名をlist型にまとめます。そして、<em>結果の変数名</em>は結果として出力されるデータフレームの列名を指定する引数です。たとえば、<code>Mean</code>にすると結果は<code>元の変数名1_Mean</code>、<code>元の変数名2_Mean</code>…のように出力されます。そして、ラムダ式が実際の関数が入る箇所です。とりあえず今回はコードを走らせ、結果から確認してみましょう。</p>
<div class="sourceCode" id="cb861"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb861-1"><a href="datahandling2.html#cb861-1"></a>df <span class="op">%&gt;%</span></span>
<span id="cb861-2"><a href="datahandling2.html#cb861-2"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="kw">across</span>(Budget<span class="op">:</span>Score, <span class="kw">list</span>(<span class="dt">Q1 =</span> <span class="op">~</span><span class="kw">quantile</span>(.x, <span class="fl">0.25</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb861-3"><a href="datahandling2.html#cb861-3"></a>                                      <span class="dt">Q3 =</span> <span class="op">~</span><span class="kw">quantile</span>(.x, <span class="fl">0.75</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 6
##   Budget_Q1 Budget_Q3 ScoreN_Q1 ScoreN_Q3 Score_Q1 Score_Q3
##       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1       800      1000         0         0        3        4</code></pre>
<p>結果の列名が<code>Budget_Q1</code>、<code>Budget_Q3</code>、<code>ScoreN_Q1</code>…のようになり、それぞれの変数の第一四分位点と第三四分位点が出力されます。問題はラムダ式の方ですが、普通の関数に非常に近いことが分かります。<code>across()</code>内のラムダ式は<code>~関数名(.x, その他の引数)</code>のような書き方になります。関数名の前に<code>~</code>が付いていることに注意してください。分位数を求める関数は<code>quantile()</code>であり、<code>quantile(ベクトル, 分位数)</code>であり、必要に応じて<code>na.rm</code>を付けます。この分位数が0.25なら第一四分位点、0.5なら第二四分位点 (=中央値)、0.75なら第三四分位点になります。それではラムダ式<code>~quantile(.x, 0.25, na.rm = TRUE)</code>はどういう意味でしょうか。これは<code>.x</code>の箇所に<code>Budget</code>や<code>ScoreN</code>、<code>Score</code>が入ることを意味します。<code>.x</code>という書き方は決まりです。<code>.y</code>とか<code>.Song-san-Daisuki</code>などはダメです。そして、<code>0.25</code>を付けることによって第一四分位点を出力するように指定します。また、<code>Budget</code>、<code>ScoreN</code>、<code>Score</code>に欠損値がある場合、無視するように<code>na.rm = TRUE</code>を付けます。</p>
<p>ラムダ式を第<a href="programming.html#programming">9</a>章で解説した自作関数で表現すると、以下のようになります。</p>
<div class="sourceCode" id="cb863"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb863-1"><a href="datahandling2.html#cb863-1"></a><span class="co"># 以下の3つは同じ機能をする関数である</span></span>
<span id="cb863-2"><a href="datahandling2.html#cb863-2"></a></span>
<span id="cb863-3"><a href="datahandling2.html#cb863-3"></a><span class="co"># ラムダ式</span></span>
<span id="cb863-4"><a href="datahandling2.html#cb863-4"></a><span class="op">~</span><span class="kw">quantile</span>(.x, <span class="fl">0.25</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span>
<span id="cb863-5"><a href="datahandling2.html#cb863-5"></a></span>
<span id="cb863-6"><a href="datahandling2.html#cb863-6"></a><span class="co"># 一般的な関数の書き方1</span></span>
<span id="cb863-7"><a href="datahandling2.html#cb863-7"></a>名無し関数 &lt;-<span class="st"> </span><span class="cf">function</span>(x) {</span>
<span id="cb863-8"><a href="datahandling2.html#cb863-8"></a>  <span class="kw">quantile</span>(x, <span class="fl">0.25</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span>
<span id="cb863-9"><a href="datahandling2.html#cb863-9"></a>}</span>
<span id="cb863-10"><a href="datahandling2.html#cb863-10"></a></span>
<span id="cb863-11"><a href="datahandling2.html#cb863-11"></a><span class="co"># 一般的な関数の書き方2</span></span>
<span id="cb863-12"><a href="datahandling2.html#cb863-12"></a>名無し関数 &lt;-<span class="st"> </span><span class="cf">function</span>(x) <span class="kw">quantile</span>(x, <span class="fl">0.25</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<p>この3つは全て同じですが、ラムダ式は関数名を持たず、その場で使い捨てる関数です。むろん、ラムダ式を使わずに事前に第一四分位点と第三四分位点を求める関数を予め作成し、ラムダ式の代わりに使うことも可能です。まずは第一四分位点と第三四分位点を求める自作関数<code>FuncQ1</code>と<code>FuncQ2</code>を作成します。</p>
<div class="sourceCode" id="cb864"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb864-1"><a href="datahandling2.html#cb864-1"></a><span class="co"># ラムダ式を使わない場合は事前に関数を定義しておく必要がある</span></span>
<span id="cb864-2"><a href="datahandling2.html#cb864-2"></a>FuncQ1 &lt;-<span class="st"> </span><span class="cf">function</span>(x) {</span>
<span id="cb864-3"><a href="datahandling2.html#cb864-3"></a>  <span class="kw">quantile</span>(x, <span class="fl">0.25</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span>
<span id="cb864-4"><a href="datahandling2.html#cb864-4"></a>}</span>
<span id="cb864-5"><a href="datahandling2.html#cb864-5"></a>FuncQ3 &lt;-<span class="st"> </span><span class="cf">function</span>(x) {</span>
<span id="cb864-6"><a href="datahandling2.html#cb864-6"></a>  <span class="kw">quantile</span>(x, <span class="fl">0.75</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span>
<span id="cb864-7"><a href="datahandling2.html#cb864-7"></a>}</span></code></pre></div>
<p>後は先ほどのほぼ同じ書き方ですが、今回はラムダ式を使わないため関数名に<code>~</code>を付けず、関数名のみで十分です。</p>
<div class="sourceCode" id="cb865"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb865-1"><a href="datahandling2.html#cb865-1"></a><span class="co"># やっておくと、summarise()文は簡潔になる</span></span>
<span id="cb865-2"><a href="datahandling2.html#cb865-2"></a>df <span class="op">%&gt;%</span></span>
<span id="cb865-3"><a href="datahandling2.html#cb865-3"></a><span class="st">  </span><span class="kw">summarize</span>(<span class="kw">across</span>(Budget<span class="op">:</span>Score, <span class="kw">list</span>(<span class="dt">Q1 =</span> FuncQ1, <span class="dt">Q3 =</span> FuncQ3)))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 6
##   Budget_Q1 Budget_Q3 ScoreN_Q1 ScoreN_Q3 Score_Q1 Score_Q3
##       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1       800      1000         0         0        3        4</code></pre>
<p>事前に関数を用意するのが面倒ですが、<code>across()</code>の中身はかなりスッキリしますね。もし、このような作業を何回も行うなら、ラムダ式を使わず、自作関数を用いることも可能です。ただし、自作関数であっても引数が2つ以上必要な場合はラムダ式を使います。</p>
</div>
<div id="summariseに使える便利な関数" class="section level3">
<h3><span class="header-section-number">11.1.2</span> <code>summarise()</code>に使える便利な関数</h3>
<p>以下の内容は後で説明する<code>group_by()</code>関数を使っているため、まだ<code>group_by()</code>に馴染みのない読者はまずはここを読み飛ばし、グルーピングの節にお進みください。</p>
<p><strong><code>IQR()</code>: 四分位範囲を求める</strong></p>
<p>四分位範囲は第三四分位点から第一四分位点を引いた値であり、Rの内蔵関数である<code>IQR()</code>を使えば便利です。この関数は<code>mean</code>や<code>sd()</code>関数と同じ使い方となります。</p>
<div class="sourceCode" id="cb867"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb867-1"><a href="datahandling2.html#cb867-1"></a>df <span class="op">%&gt;%</span></span>
<span id="cb867-2"><a href="datahandling2.html#cb867-2"></a><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(Walk)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># 予め欠損したケースを除くと、後でna.rm = TRUEが不要</span></span>
<span id="cb867-3"><a href="datahandling2.html#cb867-3"></a><span class="st">  </span><span class="kw">group_by</span>(Pref) <span class="op">%&gt;%</span></span>
<span id="cb867-4"><a href="datahandling2.html#cb867-4"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Mean    =</span> <span class="kw">mean</span>(Walk),</span>
<span id="cb867-5"><a href="datahandling2.html#cb867-5"></a>            <span class="dt">SD      =</span> <span class="kw">sd</span>(Walk),</span>
<span id="cb867-6"><a href="datahandling2.html#cb867-6"></a>            <span class="dt">IQR     =</span> <span class="kw">IQR</span>(Walk),</span>
<span id="cb867-7"><a href="datahandling2.html#cb867-7"></a>            <span class="dt">N       =</span> <span class="kw">n</span>(),</span>
<span id="cb867-8"><a href="datahandling2.html#cb867-8"></a>            <span class="dt">.groups =</span> <span class="st">&quot;drop&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb867-9"><a href="datahandling2.html#cb867-9"></a><span class="st">  </span><span class="kw">arrange</span>(Mean)</span></code></pre></div>
<pre><code>## # A tibble: 9 x 5
##   Pref      Mean    SD   IQR     N
##   &lt;chr&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
## 1 東京都    4.29  4.49     4   919
## 2 大阪府    5.92  6.08     6   932
## 3 神奈川県  8.21  7.91    10   878
## 4 京都府    8.38  6.95     9   339
## 5 兵庫県    8.52  7.27    10   484
## 6 奈良県   10.6   6.59    10   123
## 7 千葉県   10.6   8.21    12   776
## 8 埼玉県   11.6   8.99    14   817
## 9 和歌山県 12.8   6.83     9   107</code></pre>
<p><strong><code>first()</code>、<code>last()</code>、<code>nth()</code>: n番目の要素を求める</strong></p>
<p>稀なケースかも知れませんが、データ内、またはグループ内の<code>n</code>番目の行を抽出する時があります。たとえば、市区町村の情報が格納されているデータセットで、人口が大きい順でデータがソートされているとします。各都道府県ごとに最も人口が大きい市区町村のデータ、あるいは最も少ない市区町村のデータが必要な際、<code>first()</code>と<code>last()</code>関数が有効です。</p>
<p>それでは各都道府県ごとに「最も駅から遠いラーメン屋」の店舗名と最寄りの駅からの徒歩距離を出力したいとします。まずは、徒歩距離のデータが欠損しているケースを除去し、データを徒歩距離順でソートします。これは<code>filter()</code>と<code>arrange()</code>関数を使えば簡単です。続いて、<code>group_by()</code>を使って都府県単位でデータをグループ化します。最後に<code>summarise()</code>関数内に<code>last()</code>関数を使います。データは駅から近い順に鳴っているため、各都府県内の最後の行は駅から最も遠い店舗になるからです。</p>
<div class="sourceCode" id="cb869"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb869-1"><a href="datahandling2.html#cb869-1"></a>df <span class="op">%&gt;%</span></span>
<span id="cb869-2"><a href="datahandling2.html#cb869-2"></a><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(Walk)) <span class="op">%&gt;%</span></span>
<span id="cb869-3"><a href="datahandling2.html#cb869-3"></a><span class="st">  </span><span class="kw">arrange</span>(Walk) <span class="op">%&gt;%</span></span>
<span id="cb869-4"><a href="datahandling2.html#cb869-4"></a><span class="st">  </span><span class="kw">group_by</span>(Pref) <span class="op">%&gt;%</span></span>
<span id="cb869-5"><a href="datahandling2.html#cb869-5"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Farthest  =</span> <span class="kw">last</span>(Name),</span>
<span id="cb869-6"><a href="datahandling2.html#cb869-6"></a>            <span class="dt">Distance  =</span> <span class="kw">last</span>(Walk))</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 9 x 3
##   Pref     Farthest                           Distance
##   &lt;chr&gt;    &lt;chr&gt;                                 &lt;dbl&gt;
## 1 京都府   熱烈らぁめん                             30
## 2 埼玉県   札幌ラーメン どさん子 小鹿野店          116
## 3 神奈川県 札幌ラーメン どさん子 中津店             73
## 4 千葉県   札幌ラーメン どさん子 佐原51号店         59
## 5 大阪府   河童ラーメン本舗 岸和田店                38
## 6 東京都   てんがら 青梅新町店                      30
## 7 奈良県   博多長浜らーめん 夢街道 四条大路店       29
## 8 兵庫県   濃厚醤油 中華そば いせや 玉津店          43
## 9 和歌山県 中華そば まる乃                          30</code></pre>
<p>この<code>last()</code>を<code>first()</code>に変えると、最寄りの駅から最も近い店舗情報が表示されます。また、「<code>n</code>番目の情報」が必要な際は<code>nth()</code>関数を使います。<code>nth(Name, 2)</code>に変えることで2番目の店舗名が抽出できます。</p>
<p><strong><code>n_distinct()</code>: ユニーク値の個数を求める</strong></p>
<p><code>n_distinct()</code>は何種類の要素が含まれているかを計算する関数であり、<code>length(unique())</code>関数と同じ機能をします。たとえば、以下の<code>myVec1</code>に対して何種類の要素があるかを確認してみましょう。</p>
<div class="sourceCode" id="cb872"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb872-1"><a href="datahandling2.html#cb872-1"></a>myVec1 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;D&quot;</span>, <span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;D&quot;</span>, <span class="st">&quot;C&quot;</span>, <span class="st">&quot;A&quot;</span>)</span>
<span id="cb872-2"><a href="datahandling2.html#cb872-2"></a></span>
<span id="cb872-3"><a href="datahandling2.html#cb872-3"></a><span class="kw">unique</span>(myVec1)</span></code></pre></div>
<pre><code>## [1] &quot;A&quot; &quot;B&quot; &quot;D&quot; &quot;C&quot;</code></pre>
<p><code>myVec1</code>は<code>"A"</code>、<code>"B"</code>、<code>"D"</code>、<code>"C"</code>の要素で構成されていることが分かります。これが<code>myVec1</code>の<strong>ユニーク値 (unique values)</strong>です。そして、このユニーク値の個数を調べるために<code>length()</code>を使います。</p>
<div class="sourceCode" id="cb874"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb874-1"><a href="datahandling2.html#cb874-1"></a><span class="kw">length</span>(<span class="kw">unique</span>(myVec1))</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<p>これで<code>myVec1</code>は4種類の値が存在することが分かります。これと全く同じ機能をする関数が<code>n_distinct()</code>です。</p>
<div class="sourceCode" id="cb876"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb876-1"><a href="datahandling2.html#cb876-1"></a><span class="kw">n_distinct</span>(myVec1)</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<p>この関数を<code>summarise()</code>に使うことで、都府県ごとに駅の個数が分かります。あるいは「東京都内の選挙区に、これまでの衆院選において何人の候補者が存在したか」も分かります。ここでは<code>df</code>内の都府県ごとに駅の個数を計算してみましょう。最後の駅数が多い順でソートします。</p>
<div class="sourceCode" id="cb878"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb878-1"><a href="datahandling2.html#cb878-1"></a>df <span class="op">%&gt;%</span></span>
<span id="cb878-2"><a href="datahandling2.html#cb878-2"></a><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(Station)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># 最寄りの駅が欠損しているケースを除去</span></span>
<span id="cb878-3"><a href="datahandling2.html#cb878-3"></a><span class="st">  </span><span class="kw">group_by</span>(Pref) <span class="op">%&gt;%</span></span>
<span id="cb878-4"><a href="datahandling2.html#cb878-4"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">N_Station =</span> <span class="kw">n_distinct</span>(Station),</span>
<span id="cb878-5"><a href="datahandling2.html#cb878-5"></a>            <span class="dt">.groups   =</span> <span class="st">&quot;drop&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb878-6"><a href="datahandling2.html#cb878-6"></a><span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(N_Station))</span></code></pre></div>
<pre><code>## # A tibble: 9 x 2
##   Pref     N_Station
##   &lt;chr&gt;        &lt;int&gt;
## 1 東京都         368
## 2 大阪府         341
## 3 千葉県         241
## 4 神奈川県       240
## 5 兵庫県         199
## 6 埼玉県         185
## 7 京都府         123
## 8 奈良県          52
## 9 和歌山県        46</code></pre>
<p>当たり前かも知れませんが、駅数が最も多いのは東京都で次が大阪府であることが分かります。</p>
<p><strong><code>any()</code>、<code>all()</code>: 条件に合致するか否かを求める</strong></p>
<p><code>any()</code>と<code>all()</code>はベクトル内の全要素に対して条件に合致するか否かを判定する関数です。ただし、<code>any()</code>は一つの要素でも条件に合致すれば<code>TRUE</code>を、全要素が合致しない場合<code>FALSE</code>を返します。一方、<code>all()</code>は全要素に対して条件を満たせば<code>TRUE</code>、一つでも満たさない要素があれば<code>FALSE</code>を返します。以下は<code>any()</code>と<code>all()</code>の例です。</p>
<div class="sourceCode" id="cb880"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb880-1"><a href="datahandling2.html#cb880-1"></a>myVec1 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>)</span>
<span id="cb880-2"><a href="datahandling2.html#cb880-2"></a>myVec2 &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">11</span>)</span>
<span id="cb880-3"><a href="datahandling2.html#cb880-3"></a></span>
<span id="cb880-4"><a href="datahandling2.html#cb880-4"></a><span class="kw">any</span>(myVec1 <span class="op">%%</span><span class="st"> </span><span class="dv">2</span> <span class="op">==</span><span class="st"> </span><span class="dv">0</span>) <span class="co"># myVec1を2で割った場合、一つでも余りが0か</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb882"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb882-1"><a href="datahandling2.html#cb882-1"></a><span class="kw">all</span>(myVec1 <span class="op">%%</span><span class="st"> </span><span class="dv">2</span> <span class="op">==</span><span class="st"> </span><span class="dv">0</span>) <span class="co"># myVec1を2で割った場合、全ての余りが0か</span></span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb884"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb884-1"><a href="datahandling2.html#cb884-1"></a><span class="kw">all</span>(myVec2 <span class="op">%%</span><span class="st"> </span><span class="dv">2</span> <span class="op">!=</span><span class="st"> </span><span class="dv">0</span>) <span class="co"># myVec2を2で割った場合、全ての余りが0ではないか</span></span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>それでは実際に<code>df</code>に対して<code>any()</code>と<code>all()</code>関数を使ってみましょう。一つ目は「ある都府県に最寄りの駅から徒歩60分以上の店舗が<strong>一つでも</strong>あるか」であり、二つ目は「ある都府県の店舗は<strong>全て</strong>最寄りの駅から徒歩30分以下か」です。それぞれの結果を<code>Over60</code>と<code>Within30</code>という列で出力してみましょう。</p>
<div class="sourceCode" id="cb886"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb886-1"><a href="datahandling2.html#cb886-1"></a>df <span class="op">%&gt;%</span></span>
<span id="cb886-2"><a href="datahandling2.html#cb886-2"></a><span class="st">  </span><span class="kw">group_by</span>(Pref) <span class="op">%&gt;%</span></span>
<span id="cb886-3"><a href="datahandling2.html#cb886-3"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Over60   =</span> <span class="kw">any</span>(Walk <span class="op">&gt;=</span><span class="st"> </span><span class="dv">60</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb886-4"><a href="datahandling2.html#cb886-4"></a>            <span class="dt">Within30 =</span> <span class="kw">all</span>(Walk <span class="op">&lt;=</span><span class="st"> </span><span class="dv">30</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb886-5"><a href="datahandling2.html#cb886-5"></a>            <span class="dt">.groups  =</span> <span class="st">&quot;drop&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 9 x 3
##   Pref     Over60 Within30
##   &lt;chr&gt;    &lt;lgl&gt;  &lt;lgl&gt;   
## 1 京都府   FALSE  TRUE    
## 2 埼玉県   TRUE   FALSE   
## 3 神奈川県 TRUE   FALSE   
## 4 千葉県   FALSE  FALSE   
## 5 大阪府   FALSE  FALSE   
## 6 東京都   FALSE  TRUE    
## 7 奈良県   FALSE  TRUE    
## 8 兵庫県   FALSE  FALSE   
## 9 和歌山県 FALSE  TRUE</code></pre>
<p>埼玉県と神奈川県において、最寄りの駅から徒歩60以上の店がありました。また、京都府、東京都、奈良県、和歌山県の場合、全店舗が最寄りの駅から徒歩30分以下ということが分かります。当たり前ですが<code>Over60</code>が<code>TRUE</code>なら<code>Within30</code>は必ず<code>FALSE</code>になりますね。</p>
<hr />
</div>
</div>
<div id="handling2-group" class="section level2">
<h2><span class="header-section-number">11.2</span> グルーピング</h2>
<div id="group_byによるグループ化" class="section level3">
<h3><span class="header-section-number">11.2.1</span> <code>group_by()</code>によるグループ化</h3>
<p>先ほどの<code>summarise()</code>関数は確かに便利ですが、特段に便利とも言いにくいです。<code>df</code>の<code>Score</code>の平均値を計算するだけなら、<code>summarise()</code>関数を使わない方が楽です。</p>
<div class="sourceCode" id="cb888"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb888-1"><a href="datahandling2.html#cb888-1"></a><span class="co"># これまでのやり方</span></span>
<span id="cb888-2"><a href="datahandling2.html#cb888-2"></a>df <span class="op">%&gt;%</span></span>
<span id="cb888-3"><a href="datahandling2.html#cb888-3"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Mean =</span> <span class="kw">mean</span>(Score, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##    Mean
##   &lt;dbl&gt;
## 1  3.66</code></pre>
<div class="sourceCode" id="cb890"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb890-1"><a href="datahandling2.html#cb890-1"></a><span class="co"># 普通にこれでええんちゃう?</span></span>
<span id="cb890-2"><a href="datahandling2.html#cb890-2"></a><span class="kw">mean</span>(df<span class="op">$</span>Score, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 3.663457</code></pre>
<p>しかし、これをグループごとに計算するならどうでしょう。たとえば、<code>Score</code>の平均値を都府県ごとに計算するとします。この場合、以下のようなコードになります。</p>
<div class="sourceCode" id="cb892"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb892-1"><a href="datahandling2.html#cb892-1"></a><span class="kw">mean</span>(df<span class="op">$</span>Score[df<span class="op">$</span>Pref <span class="op">==</span><span class="st"> &quot;東京都&quot;</span>],   <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 3.674256</code></pre>
<div class="sourceCode" id="cb894"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb894-1"><a href="datahandling2.html#cb894-1"></a><span class="kw">mean</span>(df<span class="op">$</span>Score[df<span class="op">$</span>Pref <span class="op">==</span><span class="st"> &quot;神奈川県&quot;</span>], <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 3.533931</code></pre>
<div class="sourceCode" id="cb896"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb896-1"><a href="datahandling2.html#cb896-1"></a><span class="kw">mean</span>(df<span class="op">$</span>Score[df<span class="op">$</span>Pref <span class="op">==</span><span class="st"> &quot;千葉県&quot;</span>],   <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 3.715983</code></pre>
<div class="sourceCode" id="cb898"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb898-1"><a href="datahandling2.html#cb898-1"></a><span class="kw">mean</span>(df<span class="op">$</span>Score[df<span class="op">$</span>Pref <span class="op">==</span><span class="st"> &quot;埼玉県&quot;</span>],   <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 3.641573</code></pre>
<div class="sourceCode" id="cb900"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb900-1"><a href="datahandling2.html#cb900-1"></a><span class="kw">mean</span>(df<span class="op">$</span>Score[df<span class="op">$</span>Pref <span class="op">==</span><span class="st"> &quot;大阪府&quot;</span>],   <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 3.765194</code></pre>
<div class="sourceCode" id="cb902"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb902-1"><a href="datahandling2.html#cb902-1"></a><span class="kw">mean</span>(df<span class="op">$</span>Score[df<span class="op">$</span>Pref <span class="op">==</span><span class="st"> &quot;京都府&quot;</span>],   <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 3.684976</code></pre>
<div class="sourceCode" id="cb904"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb904-1"><a href="datahandling2.html#cb904-1"></a><span class="kw">mean</span>(df<span class="op">$</span>Score[df<span class="op">$</span>Pref <span class="op">==</span><span class="st"> &quot;兵庫県&quot;</span>],   <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 3.543936</code></pre>
<div class="sourceCode" id="cb906"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb906-1"><a href="datahandling2.html#cb906-1"></a><span class="kw">mean</span>(df<span class="op">$</span>Score[df<span class="op">$</span>Pref <span class="op">==</span><span class="st"> &quot;奈良県&quot;</span>],   <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 3.854762</code></pre>
<div class="sourceCode" id="cb908"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb908-1"><a href="datahandling2.html#cb908-1"></a><span class="kw">mean</span>(df<span class="op">$</span>Score[df<span class="op">$</span>Pref <span class="op">==</span><span class="st"> &quot;和歌山県&quot;</span>], <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 3.96999</code></pre>
<p>変わったのは<code>df$Score</code>が<code>df$Score[df$Pref == "東京都"]</code>に変わっただけです。<code>df$Pref</code>が<code>"東京都"</code>であるか否かを<code>TRUE</code>と<code>FALSE</code>で判定し、これを基準に<code>df$Score</code>を抽出する仕組みです。<code>df$Score</code>と<code>df$Pref</code>は同じデータフレームですから、このような書き方で問題ありません。</p>
<p>これだけでもかなり書くのが面倒ですが、これが47都道府県なら、あるいは200ヶ国ならかなり骨の折れる作業でしょう。ここで大活躍するのが<code>dplyr</code>パッケージの<code>group_by()</code>関数です。引数はグループ化する変数名だけです。先ほどの作業を<code>dplyr</code>を使うなら<code>Pref</code>変数でグループ化し、<code>summarise()</code>関数で平均値を求めるだけです。今回は<code>Score</code>だけでなく、<code>ScoreN</code>の平均値も求めてみましょう。そして、評価が高い順にソートもしてみます。</p>
<div class="sourceCode" id="cb910"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb910-1"><a href="datahandling2.html#cb910-1"></a><span class="co"># ScoreNとScoreの平均値をPrefごとに求める</span></span>
<span id="cb910-2"><a href="datahandling2.html#cb910-2"></a>df <span class="op">%&gt;%</span></span>
<span id="cb910-3"><a href="datahandling2.html#cb910-3"></a><span class="st">  </span><span class="kw">group_by</span>(Pref) <span class="op">%&gt;%</span></span>
<span id="cb910-4"><a href="datahandling2.html#cb910-4"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">ScoreN_Mean =</span> <span class="kw">mean</span>(ScoreN, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb910-5"><a href="datahandling2.html#cb910-5"></a>            <span class="dt">Score_Mean  =</span> <span class="kw">mean</span>(Score,  <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)) <span class="op">%&gt;%</span></span>
<span id="cb910-6"><a href="datahandling2.html#cb910-6"></a><span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(Score_Mean))</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 9 x 3
##   Pref     ScoreN_Mean Score_Mean
##   &lt;chr&gt;          &lt;dbl&gt;      &lt;dbl&gt;
## 1 和歌山県       0.593       3.97
## 2 奈良県         0.306       3.85
## 3 大阪府         0.516       3.77
## 4 千葉県         0.259       3.72
## 5 京都府         0.522       3.68
## 6 東京都         1.16        3.67
## 7 埼玉県         0.278       3.64
## 8 兵庫県         0.389       3.54
## 9 神奈川県       0.587       3.53</code></pre>
<p>評判が最も高い都府県は和歌山県、最も低いのは神奈川県ですね。Songも和歌山ラーメンは井出系も車庫前系も好きです。しかし、大事なのは「井出系」と「車庫前系」といった分類が正しいかどうかではありません。コードが非常に簡潔となり、ソートなども自由自在であることです。都府県ごとに<code>ScoreN</code>と<code>Score</code>の平均値を求める場合、<code>dplyr()</code>を使わなかったら18行のコードとなり、ソートも自分でやる必要があります。一方、<code>group_by()</code>関数を使うことによってコードが5行になりました。</p>
<p>また、これは2020年6月に公開された<code>dplyr</code>1.0.0からの問題ですが、<code>group_by()</code>の後に<code>summarise()</code>を使うと以下のようなメッセージが出力されます。</p>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<p>これは<code>group_by()</code>で指定された変数のグループ化が自動的に解除されたことを意味します。なぜなら<code>summarise()</code>をする際は<code>Pref</code>をグループ変数として使いましたが、出力された結果の<code>Pref</code>変数はもはやグループとして機能できなくなるからです。元の<code>df</code>には<code>Pref</code>が<code>"東京都"</code>だったケースが1000行、<code>"京都府"</code>だったのが414行あったので、<code>Pref</code>変数でグループ化する意味がありました。しかし、<code>summarise()</code>から得られたデータフレームは<code>Pref == "東京都"</code>の行が1つしかありません。これはグループ化する意味がなくなったことを意味します。したがって、自動的にグループを解除してくれます。自動的にやってくれるのはありがたいことですが、可能ならば関数内に自分で明記することが推奨されます。そこで使う引数が<code>.groups</code>であり、<code>"drop"</code>を指定すると<strong>全ての</strong>グループ化変数を解除します。以下のようなコードだと先ほどのメッセージが表示されません。今後、意識的に入れるようにしましょう。</p>
<div class="sourceCode" id="cb914"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb914-1"><a href="datahandling2.html#cb914-1"></a><span class="co"># ScoreNとScoreの平均値をPrefごとに求める</span></span>
<span id="cb914-2"><a href="datahandling2.html#cb914-2"></a>df <span class="op">%&gt;%</span></span>
<span id="cb914-3"><a href="datahandling2.html#cb914-3"></a><span class="st">  </span><span class="kw">group_by</span>(Pref) <span class="op">%&gt;%</span></span>
<span id="cb914-4"><a href="datahandling2.html#cb914-4"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">ScoreN_Mean =</span> <span class="kw">mean</span>(ScoreN, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb914-5"><a href="datahandling2.html#cb914-5"></a>            <span class="dt">Score_Mean  =</span> <span class="kw">mean</span>(Score,  <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb914-6"><a href="datahandling2.html#cb914-6"></a>            <span class="dt">.groups     =</span> <span class="st">&quot;drop&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb914-7"><a href="datahandling2.html#cb914-7"></a><span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(Score_Mean))</span></code></pre></div>
<pre><code>## # A tibble: 9 x 3
##   Pref     ScoreN_Mean Score_Mean
##   &lt;chr&gt;          &lt;dbl&gt;      &lt;dbl&gt;
## 1 和歌山県       0.593       3.97
## 2 奈良県         0.306       3.85
## 3 大阪府         0.516       3.77
## 4 千葉県         0.259       3.72
## 5 京都府         0.522       3.68
## 6 東京都         1.16        3.67
## 7 埼玉県         0.278       3.64
## 8 兵庫県         0.389       3.54
## 9 神奈川県       0.587       3.53</code></pre>
<p>続いて、一つ便利な関数を紹介します。それはグループのサイズを計算する関数、<code>n()</code>です。この関数を<code>summarise()</code>内に使うと、各グループに属するケース数を出力します。先ほどのコードを修正し、各グループのサイズを<code>N</code>という名の列として追加してみましょう。そしてソートの順番は<code>N</code>を最優先とし、同じ場合は<code>Score_Mean</code>が高い方を上に出力させます。また、<code>ScoreN_Mean</code>の前に、口コミ数の合計も出してみましょう。</p>
<div class="sourceCode" id="cb916"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb916-1"><a href="datahandling2.html#cb916-1"></a><span class="co"># Prefごとに口コミ数の合計、口コミ数の平均値、評価の平均値、店舗数を求める</span></span>
<span id="cb916-2"><a href="datahandling2.html#cb916-2"></a><span class="co"># 店舗数-評価の平均値順でソートする</span></span>
<span id="cb916-3"><a href="datahandling2.html#cb916-3"></a>df <span class="op">%&gt;%</span></span>
<span id="cb916-4"><a href="datahandling2.html#cb916-4"></a><span class="st">  </span><span class="kw">group_by</span>(Pref) <span class="op">%&gt;%</span></span>
<span id="cb916-5"><a href="datahandling2.html#cb916-5"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">ScoreN_Sum  =</span> <span class="kw">sum</span>(ScoreN,  <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb916-6"><a href="datahandling2.html#cb916-6"></a>            <span class="dt">ScoreN_Mean =</span> <span class="kw">mean</span>(ScoreN, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb916-7"><a href="datahandling2.html#cb916-7"></a>            <span class="dt">Score_Mean  =</span> <span class="kw">mean</span>(Score,  <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb916-8"><a href="datahandling2.html#cb916-8"></a>            <span class="dt">N           =</span> <span class="kw">n</span>(),</span>
<span id="cb916-9"><a href="datahandling2.html#cb916-9"></a>            <span class="dt">.groups     =</span> <span class="st">&quot;drop&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb916-10"><a href="datahandling2.html#cb916-10"></a><span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(N), <span class="kw">desc</span>(Score_Mean))</span></code></pre></div>
<pre><code>## # A tibble: 9 x 5
##   Pref     ScoreN_Sum ScoreN_Mean Score_Mean     N
##   &lt;chr&gt;         &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;
## 1 大阪府          516       0.516       3.77  1000
## 2 千葉県          259       0.259       3.72  1000
## 3 東京都         1165       1.16        3.67  1000
## 4 埼玉県          278       0.278       3.64  1000
## 5 神奈川県        587       0.587       3.53  1000
## 6 兵庫県          230       0.389       3.54   591
## 7 京都府          216       0.522       3.68   414
## 8 奈良県           45       0.306       3.85   147
## 9 和歌山県         83       0.593       3.97   140</code></pre>
<p>記述統計をグループごとに求めるのは普通にあり得るケースですし、実験データの場合はほぼ必須の作業でう。統制群と処置群間においてグループサイズが均一か、共変量のバラツキが十分に小さいかなどを判断する際に<code>group_by()</code>と<code>summarise()</code>関数の組み合わせは非常に便利です。</p>
</div>
<div id="複数の変数を用いたグループ化" class="section level3">
<h3><span class="header-section-number">11.2.2</span> 複数の変数を用いたグループ化</h3>
<p>グループ化変数は2つ以上指定することも可能です。たとえば、都府県 (<code>Pref</code>)と最寄りの駅の路線 (<code>Line</code>)でグループ化することも可能です。それでは<code>Pref</code>と<code>Line</code>でグループ化し、店舗数と口コミ数、評価の平均値を計算し、ソートの順番は店舗数、店舗数が同じなら評価の平均値が高い順にしましょう。今回も<code>summarise()</code>内に<code>.group = "drop"</code>を指定し、グループ化を解除します。今回はTop 20まで出してみましょう。</p>
<div class="sourceCode" id="cb918"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb918-1"><a href="datahandling2.html#cb918-1"></a><span class="co"># ScoreNとScoreの平均値をPrefごとに求める</span></span>
<span id="cb918-2"><a href="datahandling2.html#cb918-2"></a>df <span class="op">%&gt;%</span></span>
<span id="cb918-3"><a href="datahandling2.html#cb918-3"></a><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(Line)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># Lineが欠損していないケースのみ残す</span></span>
<span id="cb918-4"><a href="datahandling2.html#cb918-4"></a><span class="st">  </span><span class="kw">group_by</span>(Pref, Line) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># PrefとLineでグループ化</span></span>
<span id="cb918-5"><a href="datahandling2.html#cb918-5"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">N           =</span> <span class="kw">n</span>(),</span>
<span id="cb918-6"><a href="datahandling2.html#cb918-6"></a>            <span class="dt">ScoreN_Sum  =</span> <span class="kw">sum</span>(ScoreN,  <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb918-7"><a href="datahandling2.html#cb918-7"></a>            <span class="dt">Score_Mean  =</span> <span class="kw">mean</span>(Score,  <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb918-8"><a href="datahandling2.html#cb918-8"></a>            <span class="dt">.groups     =</span> <span class="st">&quot;drop&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb918-9"><a href="datahandling2.html#cb918-9"></a><span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(N), <span class="kw">desc</span>(Score_Mean)) <span class="op">%&gt;%</span></span>
<span id="cb918-10"><a href="datahandling2.html#cb918-10"></a><span class="st">  </span><span class="kw">print</span>(<span class="dt">n =</span> <span class="dv">20</span>)</span></code></pre></div>
<pre><code>## # A tibble: 523 x 5
##    Pref     Line                        N ScoreN_Sum Score_Mean
##    &lt;chr&gt;    &lt;chr&gt;                   &lt;int&gt;      &lt;dbl&gt;      &lt;dbl&gt;
##  1 埼玉県   東武東上線                122         27       3.68
##  2 東京都   ＪＲ                      104        231       3.56
##  3 神奈川県 小田急小田原線             96         31       3.59
##  4 埼玉県   東武伊勢崎線               96         18       3.51
##  5 神奈川県 横浜市営ブルーライン       82         77       3.66
##  6 千葉県   京成本線                   82         29       3.34
##  7 神奈川県 京急本線                   68         40       3.33
##  8 千葉県   東武野田線                 63          2       4.75
##  9 神奈川県 小田急江ノ島線             62          8       3.79
## 10 大阪府   阪急京都本線               53         32       3.67
## 11 大阪府   南海本線                   52         11       4.22
## 12 兵庫県   阪神本線                   52         23       3.80
## 13 埼玉県   JR高崎線                   51          5       4   
## 14 兵庫県   山陽電鉄本線               51         15       2.98
## 15 千葉県   JR総武本線（東京-銚子）    47          8       4   
## 16 埼玉県   西武新宿線                 45          8       4.17
## 17 埼玉県   秩父鉄道線                 43         10       3.82
## 18 大阪府   京阪本線                   43         10       3.69
## 19 千葉県   新京成電鉄                 43          6       3.6 
## 20 京都府   阪急京都本線               43         27       3.5 
## # … with 503 more rows</code></pre>
<p>ぐるなびに登録されているラーメン屋が最も多い路線は埼玉県内の東武東上線で122店舗があります。東武東上線は東京都と埼玉県をまたがる路線ですので、東武東上線だけならもっと多いかも知れませんね。</p>
<p>ここで一つ考えたいのは<code>summarise()</code>内の<code>.groups</code>引数です。前回はグループ化に使った変数ごとに1行しか残っていなかったのでグループ化を全て解除しました。しかし、今回は状況がやや異なります。グループ化変数に使った<code>Pref</code>を考えると、まだ<code>Pref == "東京都"</code>であるケースがいくつかあります。やろうとすればまだグループ化出来る状態です。これは<code>Line</code>についても同じです。<code>Line == "東武東上線"</code>の行はここには表示されていないものの、まだデータに残っています。もし、これ以上グループ化しないなら今のように<code>.groups = "drop"</code>が正しいですが、もしもう一回グループ化したい場合はどうすればよいでしょうか。方法は2つ考えられます。</p>
<ol style="list-style-type: decimal">
<li>もう一度パイプ演算子を使って<code>group_by()</code>関数を使う (以下の9行目)。
<ul>
<li>結果を見ると<code>## # Groups:   Pref, Line [523]</code>で、ちゃんとグループ化されていることが分かります。</li>
</ul></li>
</ol>
<div class="sourceCode" id="cb920"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb920-1"><a href="datahandling2.html#cb920-1"></a>df <span class="op">%&gt;%</span></span>
<span id="cb920-2"><a href="datahandling2.html#cb920-2"></a><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(Line)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb920-3"><a href="datahandling2.html#cb920-3"></a><span class="st">  </span><span class="kw">group_by</span>(Pref, Line) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb920-4"><a href="datahandling2.html#cb920-4"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">N           =</span> <span class="kw">n</span>(),</span>
<span id="cb920-5"><a href="datahandling2.html#cb920-5"></a>            <span class="dt">ScoreN_Sum  =</span> <span class="kw">sum</span>(ScoreN,  <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb920-6"><a href="datahandling2.html#cb920-6"></a>            <span class="dt">Score_Mean  =</span> <span class="kw">mean</span>(Score,  <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb920-7"><a href="datahandling2.html#cb920-7"></a>            <span class="dt">.groups     =</span> <span class="st">&quot;drop&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb920-8"><a href="datahandling2.html#cb920-8"></a><span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(N), <span class="kw">desc</span>(Score_Mean)) <span class="op">%&gt;%</span></span>
<span id="cb920-9"><a href="datahandling2.html#cb920-9"></a><span class="st">  </span><span class="kw">group_by</span>(Pref, Line) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># group_by()、もう一度</span></span>
<span id="cb920-10"><a href="datahandling2.html#cb920-10"></a><span class="st">  </span><span class="kw">print</span>(<span class="dt">n =</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## # A tibble: 523 x 5
## # Groups:   Pref, Line [523]
##   Pref     Line                     N ScoreN_Sum Score_Mean
##   &lt;chr&gt;    &lt;chr&gt;                &lt;int&gt;      &lt;dbl&gt;      &lt;dbl&gt;
## 1 埼玉県   東武東上線             122         27       3.68
## 2 東京都   ＪＲ                   104        231       3.56
## 3 神奈川県 小田急小田原線          96         31       3.59
## 4 埼玉県   東武伊勢崎線            96         18       3.51
## 5 神奈川県 横浜市営ブルーライン    82         77       3.66
## # … with 518 more rows</code></pre>
<ol start="2" style="list-style-type: decimal">
<li><code>.groups</code>引数を何とかする。</li>
</ol>
<p>推奨される方法は2番です。具体的には<code>.groups = "keep"</code>を指定するだけであり、こっちの方が無駄なコードを省けることができます。</p>
<div class="sourceCode" id="cb922"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb922-1"><a href="datahandling2.html#cb922-1"></a>df <span class="op">%&gt;%</span></span>
<span id="cb922-2"><a href="datahandling2.html#cb922-2"></a><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(Line)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb922-3"><a href="datahandling2.html#cb922-3"></a><span class="st">  </span><span class="kw">group_by</span>(Pref, Line) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb922-4"><a href="datahandling2.html#cb922-4"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">N           =</span> <span class="kw">n</span>(),</span>
<span id="cb922-5"><a href="datahandling2.html#cb922-5"></a>            <span class="dt">ScoreN_Sum  =</span> <span class="kw">sum</span>(ScoreN,  <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb922-6"><a href="datahandling2.html#cb922-6"></a>            <span class="dt">Score_Mean  =</span> <span class="kw">mean</span>(Score,  <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb922-7"><a href="datahandling2.html#cb922-7"></a>            <span class="dt">.groups     =</span> <span class="st">&quot;keep&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb922-8"><a href="datahandling2.html#cb922-8"></a><span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(N), <span class="kw">desc</span>(Score_Mean)) <span class="op">%&gt;%</span></span>
<span id="cb922-9"><a href="datahandling2.html#cb922-9"></a><span class="st">  </span><span class="kw">print</span>(<span class="dt">n =</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## # A tibble: 523 x 5
## # Groups:   Pref, Line [523]
##   Pref     Line                     N ScoreN_Sum Score_Mean
##   &lt;chr&gt;    &lt;chr&gt;                &lt;int&gt;      &lt;dbl&gt;      &lt;dbl&gt;
## 1 埼玉県   東武東上線             122         27       3.68
## 2 東京都   ＪＲ                   104        231       3.56
## 3 神奈川県 小田急小田原線          96         31       3.59
## 4 埼玉県   東武伊勢崎線            96         18       3.51
## 5 神奈川県 横浜市営ブルーライン    82         77       3.66
## # … with 518 more rows</code></pre>
<p><code>.groups</code>引数は<code>"drop"</code>と<code>"keep"</code>以外にも<code>"drop_last"</code>があります。実は<code>summarise()</code>に<code>.groups</code>引数を指定したい場合のデフォルト値は<code>.groups == "drop_last"</code>または<code>"keep"</code>ですが、ここがややこしいです。主なケースにおいてデフォルト値は<code>"drop"</code>となりますとなります。<code>.groups == "drop_last"</code>これは最後のグループ化変数のみ解除する意味です。今回の例だと、2番目のグループ化変数である<code>Line</code>がグループ化変数から外され、<code>Pref</code>のみがグループ化変数として残る仕組みです。</p>
<p>それではデフォルト値が<code>"keep"</code>になるのはいつでしょうか。それは記述統計量の結果が長さ2以上のベクトルである場合です。平均値を求める<code>mean()</code>、標準偏差を求める<code>sd()</code>などは、結果として長さ1のベクトルを返します。しかし、長さ2以上ののベクトルを返す関数もあります。たとえば、分位数を求める<code>quantile()</code>関数があります。<code>quantile(ベクトル名, 0.25)</code>の場合、第一四分位点のみ返すため、結果は長さ1のベクトルです。しかし、<code>quantile(ベクトル名, c(0.25, 0.5, 0.75))</code>のように第一四分位点から第三四分位点を同時に計算し、長さ3のベクトルが返されるケースもありますし、第二引数を省略すると、最小値・第一四分位点・第二四分位点・第三四分位点・最大値、つまり、長さ5のベクトルが返される場合があります。</p>
<div class="sourceCode" id="cb924"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb924-1"><a href="datahandling2.html#cb924-1"></a><span class="co"># 第一四分位点のみを求める (長さ1のベクトル)</span></span>
<span id="cb924-2"><a href="datahandling2.html#cb924-2"></a><span class="kw">quantile</span>(df<span class="op">$</span>Walk, <span class="fl">0.25</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## 25% 
##   2</code></pre>
<div class="sourceCode" id="cb926"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb926-1"><a href="datahandling2.html#cb926-1"></a><span class="co"># 引数を省略する (長さ5のベクトル)</span></span>
<span id="cb926-2"><a href="datahandling2.html#cb926-2"></a><span class="kw">quantile</span>(df<span class="op">$</span>Walk, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>##   0%  25%  50%  75% 100% 
##    1    2    5   12  116</code></pre>
<p><code>.groups</code>のデフォルト値が<code>"keep"</code>になるのは、このように長さ2以上のベクトルが返されるケースです。たとえば、都府県と最寄りの駅の路線でグループ化し、店舗までの徒歩距離の平均値を求めるとします。デフォルト値の変化を見るために、ここではあえて<code>.groups</code>引数を省略しました。</p>
<div class="sourceCode" id="cb928"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb928-1"><a href="datahandling2.html#cb928-1"></a>df <span class="op">%&gt;%</span></span>
<span id="cb928-2"><a href="datahandling2.html#cb928-2"></a><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(Walk)) <span class="op">%&gt;%</span></span>
<span id="cb928-3"><a href="datahandling2.html#cb928-3"></a><span class="st">  </span><span class="kw">group_by</span>(Pref, Line) <span class="op">%&gt;%</span></span>
<span id="cb928-4"><a href="datahandling2.html#cb928-4"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Mean =</span> <span class="kw">mean</span>(Walk))</span></code></pre></div>
<pre><code>## `summarise()` regrouping output by &#39;Pref&#39; (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 509 x 3
## # Groups:   Pref [9]
##    Pref   Line                         Mean
##    &lt;chr&gt;  &lt;chr&gt;                       &lt;dbl&gt;
##  1 京都府 ＪＲ                         4   
##  2 京都府 ＪＲ京都線                  10   
##  3 京都府 ＪＲ嵯峨野線                 5   
##  4 京都府 ＪＲ山陰本線                19   
##  5 京都府 ＪＲ山陰本線（京都-米子）    9.23
##  6 京都府 JR山陰本線（京都-米子）      8.67
##  7 京都府 JR小浜線                    16.5 
##  8 京都府 ＪＲ小浜線                   9   
##  9 京都府 ＪＲ東海道本線（米原-神戸） 11.2 
## 10 京都府 JR東海道本線（米原-神戸）   16.3 
## # … with 499 more rows</code></pre>
<p>最初は<code>Pref</code>と<code>Line</code>でグループ化しましたが、<code>summarise()</code>の後、<code>Line</code>がグループ化変数から外されました。つまり、引数が<code>"drop_last"</code>になっていることです。</p>
<p>それでは、平均値に加えて、第一四分位点と第三四分位点も計算し、<code>Quantile</code>という名で格納してみましょう。</p>
<div class="sourceCode" id="cb931"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb931-1"><a href="datahandling2.html#cb931-1"></a>df <span class="op">%&gt;%</span></span>
<span id="cb931-2"><a href="datahandling2.html#cb931-2"></a><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(Walk)) <span class="op">%&gt;%</span></span>
<span id="cb931-3"><a href="datahandling2.html#cb931-3"></a><span class="st">  </span><span class="kw">group_by</span>(Pref, Line) <span class="op">%&gt;%</span></span>
<span id="cb931-4"><a href="datahandling2.html#cb931-4"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Mean     =</span> <span class="kw">mean</span>(Walk),</span>
<span id="cb931-5"><a href="datahandling2.html#cb931-5"></a>            <span class="dt">Quantile =</span> <span class="kw">quantile</span>(Walk, <span class="kw">c</span>(<span class="fl">0.25</span>, <span class="fl">0.75</span>)))</span></code></pre></div>
<pre><code>## `summarise()` regrouping output by &#39;Pref&#39;, &#39;Line&#39; (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 1,018 x 4
## # Groups:   Pref, Line [509]
##    Pref   Line                       Mean Quantile
##    &lt;chr&gt;  &lt;chr&gt;                     &lt;dbl&gt;    &lt;dbl&gt;
##  1 京都府 ＪＲ                       4        1.25
##  2 京都府 ＪＲ                       4        5   
##  3 京都府 ＪＲ京都線                10       10   
##  4 京都府 ＪＲ京都線                10       10   
##  5 京都府 ＪＲ嵯峨野線               5        4.5 
##  6 京都府 ＪＲ嵯峨野線               5        6   
##  7 京都府 ＪＲ山陰本線              19       19   
##  8 京都府 ＪＲ山陰本線              19       19   
##  9 京都府 ＪＲ山陰本線（京都-米子）  9.23     3   
## 10 京都府 ＪＲ山陰本線（京都-米子）  9.23    13   
## # … with 1,008 more rows</code></pre>
<p>同じ<code>Pref</code>、<code>Line</code>のケースが2つずつ出来ています。最初に来る数値は第一四分位点、次に来るのが第三四分位点です。そして最初のグループ化変数であった<code>Pref</code>と<code>Line</code>が、<code>summarise()</code>後もグループ化変数として残っていることが分かります。</p>
<p><code>.groups</code>引数は記述統計量だけを計算する意味ではあまり意識する必要がありません。しかし、得られた記述統計量から何らかの計算をしたり、さらにもう一回記述統計量を求めたりする際、予期せぬ結果が得られる可能性があるため注意する必要があります。出来る限り<code>.groups</code>引数は指定するようにしましょう。</p>
<hr />
</div>
</div>
<div id="handling2-mutate" class="section level2">
<h2><span class="header-section-number">11.3</span> 変数の計算</h2>
<div id="mutate関数の使い方" class="section level3">
<h3><span class="header-section-number">11.3.1</span> <code>mutate()</code>関数の使い方</h3>
<p>続いて、データフレーム内の変数を用いて計算を行い、その結果を新しい列として格納する<code>mutate()</code>関数について紹介します。まず、<code>mutate()</code>関数の書き方からです。</p>
<div class="sourceCode" id="cb934"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb934-1"><a href="datahandling2.html#cb934-1"></a><span class="co"># mutate()関数の使い方</span></span>
<span id="cb934-2"><a href="datahandling2.html#cb934-2"></a>データフレーム名 <span class="op">%&gt;%</span></span>
<span id="cb934-3"><a href="datahandling2.html#cb934-3"></a><span class="st">  </span><span class="kw">mutate</span>(新しい変数名 =<span class="st"> </span>処理内容)</span></code></pre></div>
<p>これは何らかの処理を行い、その結果を新しい変数としてデータフレームに追加することを意味します。新しく出来た変数は、基本的に最後の列になります。ここでは分単位である<code>Walk</code>を時間単位に変換した<code>Walk_Hour</code>変数を作成するとします。処理内容は<code>Walk / 60</code>です。最後に、都府県名、店舗名、徒歩距離 (分)、徒歩距離 (時間)のみを残し、遠い順にソートします。</p>
<div class="sourceCode" id="cb935"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb935-1"><a href="datahandling2.html#cb935-1"></a>df <span class="op">%&gt;%</span></span>
<span id="cb935-2"><a href="datahandling2.html#cb935-2"></a><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(Walk)) <span class="op">%&gt;%</span></span>
<span id="cb935-3"><a href="datahandling2.html#cb935-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Walk_Hour =</span> Walk <span class="op">/</span><span class="st"> </span><span class="dv">60</span>) <span class="op">%&gt;%</span></span>
<span id="cb935-4"><a href="datahandling2.html#cb935-4"></a><span class="st">  </span><span class="kw">select</span>(Pref, Name, Walk, Walk_Hour) <span class="op">%&gt;%</span></span>
<span id="cb935-5"><a href="datahandling2.html#cb935-5"></a><span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(Walk_Hour))</span></code></pre></div>
<pre><code>## # A tibble: 5,375 x 4
##    Pref     Name                               Walk Walk_Hour
##    &lt;chr&gt;    &lt;chr&gt;                             &lt;dbl&gt;     &lt;dbl&gt;
##  1 埼玉県   札幌ラーメン どさん子 小鹿野店      116     1.93 
##  2 神奈川県 札幌ラーメン どさん子 中津店         73     1.22 
##  3 千葉県   札幌ラーメン どさん子 佐原51号店     59     0.983
##  4 神奈川県 札幌ラーメン どさん子 山際店         50     0.833
##  5 千葉県   札幌ラーメン どさん子 関宿店         49     0.817
##  6 兵庫県   濃厚醤油 中華そば いせや 玉津店      43     0.717
##  7 大阪府   河童ラーメン本舗 岸和田店            38     0.633
##  8 埼玉県   ラーメン山岡家 上尾店                35     0.583
##  9 兵庫県   濃厚醤油 中華そば いせや 大蔵谷店    35     0.583
## 10 大阪府   河童ラーメン本舗 松原店              31     0.517
## # … with 5,365 more rows</code></pre>
<p><code>mutate()</code>は3行目に登場しますが、これは<code>Walk</code>を60に割った結果を<code>Walk_Hour</code>としてデータフレームの最後の列として格納することを意味します。もし、最後の列でなく、ある変数の前、または後にしたい場合は、<code>.before</code>または<code>.after</code>引数を追加します。これは<code>select()</code>関数の<code>.before</code>と<code>.after</code>と同じ使い方です。たとえば、新しく出来た<code>Walk_Hour</code>を<code>ID</code>と<code>Name</code>の間に入れたい場合は</p>
<div class="sourceCode" id="cb937"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb937-1"><a href="datahandling2.html#cb937-1"></a><span class="co"># コードの3行名を修正 (.before使用)</span></span>
<span id="cb937-2"><a href="datahandling2.html#cb937-2"></a><span class="kw">mutate</span>(<span class="dt">Walk_Hour =</span> Walk <span class="op">/</span><span class="st"> </span><span class="dv">60</span>,</span>
<span id="cb937-3"><a href="datahandling2.html#cb937-3"></a>       <span class="dt">.before   =</span> Name)</span>
<span id="cb937-4"><a href="datahandling2.html#cb937-4"></a></span>
<span id="cb937-5"><a href="datahandling2.html#cb937-5"></a><span class="co"># コードの3行名を修正 (.after使用)</span></span>
<span id="cb937-6"><a href="datahandling2.html#cb937-6"></a><span class="kw">mutate</span>(<span class="dt">Walk_Hour =</span> Walk <span class="op">/</span><span class="st"> </span><span class="dv">60</span>,</span>
<span id="cb937-7"><a href="datahandling2.html#cb937-7"></a>       <span class="dt">.after    =</span> ID)</span></code></pre></div>
<p>のようにコードを修正します。</p>
<p>むろん、変数間同士の計算も可能です。たとえば、以下のような<code>df2</code>があり、1店舗当たりの平均口コミ数を計算し、<code>ScoreN_Mean</code>という変数名で<code>ScoreN_Sum</code>の後に格納うするとします。この場合、<code>ScoreN_Sum</code>変数を<code>N</code>で割るだけです。</p>
<div class="sourceCode" id="cb938"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb938-1"><a href="datahandling2.html#cb938-1"></a>df2 &lt;-<span class="st"> </span>df <span class="op">%&gt;%</span></span>
<span id="cb938-2"><a href="datahandling2.html#cb938-2"></a><span class="st">  </span><span class="kw">group_by</span>(Pref) <span class="op">%&gt;%</span></span>
<span id="cb938-3"><a href="datahandling2.html#cb938-3"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Budget_Mean =</span> <span class="kw">mean</span>(Budget, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb938-4"><a href="datahandling2.html#cb938-4"></a>            <span class="dt">ScoreN_Sum  =</span> <span class="kw">sum</span>(ScoreN, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb938-5"><a href="datahandling2.html#cb938-5"></a>            <span class="dt">Score_Mean  =</span> <span class="kw">mean</span>(Score, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb938-6"><a href="datahandling2.html#cb938-6"></a>            <span class="dt">N           =</span> <span class="kw">n</span>(),</span>
<span id="cb938-7"><a href="datahandling2.html#cb938-7"></a>            <span class="dt">.groups     =</span> <span class="st">&quot;drop&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb939"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb939-1"><a href="datahandling2.html#cb939-1"></a>df2 <span class="op">%&gt;%</span></span>
<span id="cb939-2"><a href="datahandling2.html#cb939-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">ScoreN_Mean =</span> ScoreN_Sum <span class="op">/</span><span class="st"> </span>N,</span>
<span id="cb939-3"><a href="datahandling2.html#cb939-3"></a>         <span class="dt">.after      =</span> ScoreN_Sum)</span></code></pre></div>
<pre><code>## # A tibble: 9 x 6
##   Pref     Budget_Mean ScoreN_Sum ScoreN_Mean Score_Mean     N
##   &lt;chr&gt;          &lt;dbl&gt;      &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;
## 1 京都府         1399.        216       0.522       3.68   414
## 2 埼玉県         1147.        278       0.278       3.64  1000
## 3 神奈川県       1239.        587       0.587       3.53  1000
## 4 千葉県         1124.        259       0.259       3.72  1000
## 5 大阪府         1203.        516       0.516       3.77  1000
## 6 東京都         1283.       1165       1.16        3.67  1000
## 7 奈良県         1169.         45       0.306       3.85   147
## 8 兵庫県         1197.        230       0.389       3.54   591
## 9 和歌山県       1252          83       0.593       3.97   140</code></pre>
<p>このように、データ内の変数を用いた計算結果を新しい列として追加する場合は、<code>mutate()</code>が便利です。これを<code>mutate()</code>を使わずに処理する場合、以下のようなコードになりますが、可読性が相対的に低いことが分かります。</p>
<div class="sourceCode" id="cb941"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb941-1"><a href="datahandling2.html#cb941-1"></a>df2<span class="op">$</span>ScoreN_Mean &lt;-<span class="st"> </span>df2<span class="op">$</span>ScoreN_Sum <span class="op">/</span><span class="st"> </span>df2<span class="op">$</span>N</span>
<span id="cb941-2"><a href="datahandling2.html#cb941-2"></a>df2 &lt;-<span class="st"> </span>df2[, <span class="kw">c</span>(<span class="st">&quot;Pref&quot;</span>, <span class="st">&quot;Budget_Mean&quot;</span>, <span class="st">&quot;Walk_Mean&quot;</span>, </span>
<span id="cb941-3"><a href="datahandling2.html#cb941-3"></a>               <span class="st">&quot;ScoreN_Sum&quot;</span>, <span class="st">&quot;ScoreN_Mean&quot;</span>, <span class="st">&quot;Score_Mean&quot;</span>, <span class="st">&quot;N&quot;</span>)]</span></code></pre></div>
<p>むろんですが、計算には<code>+</code>や<code>/</code>のような演算子だけでなく、関数を使うことも可能です。たとえば、<code>Budget</code>が1000円未満なら<code>"Cheap"</code>、1000円以上なら<code>"Expensive"</code>と示す変数<code>Budget2</code>を作成する場合は<code>ifelse()</code>関数が使えます。</p>
<div class="sourceCode" id="cb942"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb942-1"><a href="datahandling2.html#cb942-1"></a>df <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb942-2"><a href="datahandling2.html#cb942-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Budget2 =</span> <span class="kw">ifelse</span>(Budget <span class="op">&lt;</span><span class="st"> </span><span class="dv">1000</span>, <span class="st">&quot;Cheap&quot;</span>, <span class="st">&quot;Expensive&quot;</span>)) <span class="op">%&gt;%</span></span>
<span id="cb942-3"><a href="datahandling2.html#cb942-3"></a><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(Budget2)) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># Budget2が欠損した店舗を除外</span></span>
<span id="cb942-4"><a href="datahandling2.html#cb942-4"></a><span class="st">  </span><span class="kw">group_by</span>(Pref, Budget2) <span class="op">%&gt;%</span><span class="st"> </span><span class="co"># PrefとBudget2でグループ化</span></span>
<span id="cb942-5"><a href="datahandling2.html#cb942-5"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">N =</span> <span class="kw">n</span>(),          <span class="co"># 店舗数を表示</span></span>
<span id="cb942-6"><a href="datahandling2.html#cb942-6"></a>            <span class="dt">.groups =</span> <span class="st">&quot;drop&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 18 x 3
##    Pref     Budget2       N
##    &lt;chr&gt;    &lt;chr&gt;     &lt;int&gt;
##  1 京都府   Cheap        22
##  2 京都府   Expensive    28
##  3 埼玉県   Cheap        37
##  4 埼玉県   Expensive    45
##  5 神奈川県 Cheap        66
##  6 神奈川県 Expensive    54
##  7 千葉県   Cheap        64
##  8 千葉県   Expensive    72
##  9 大阪府   Cheap       104
## 10 大阪府   Expensive   115
## 11 東京都   Cheap       206
## 12 東京都   Expensive   236
## 13 奈良県   Cheap        11
## 14 奈良県   Expensive    10
## 15 兵庫県   Cheap        39
## 16 兵庫県   Expensive    27
## 17 和歌山県 Cheap        10
## 18 和歌山県 Expensive     5</code></pre>
<p>これは各都府県ごとの予算1000円未満の店と以上の店の店舗数をまとめた表となります。もし、500円未満なら<code>"Cheap"</code>、500円以上~1000円未満なら<code>"Reasonable"</code>、1000円以上なら<code>"Expensive"</code>になる<code>Budget3</code>変数を作るにはどうすればよいでしょうか。第<a href="programming.html#programming">9</a>章で紹介しました<code>ifelse()</code>を重ねることも出来ますが、ここでは<code>case_when()</code>関数が便利です。まずは、<code>ifelse()</code>を使ったコードは以下の通りです。</p>
<div class="sourceCode" id="cb944"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb944-1"><a href="datahandling2.html#cb944-1"></a><span class="co"># ifelse()を使う場合</span></span>
<span id="cb944-2"><a href="datahandling2.html#cb944-2"></a>df <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb944-3"><a href="datahandling2.html#cb944-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Budget3 =</span> <span class="kw">ifelse</span>(Budget <span class="op">&lt;</span><span class="st"> </span><span class="dv">500</span>, <span class="st">&quot;Cheap&quot;</span>, </span>
<span id="cb944-4"><a href="datahandling2.html#cb944-4"></a>                          <span class="kw">ifelse</span>(Budget <span class="op">&gt;=</span><span class="st"> </span><span class="dv">500</span> <span class="op">&amp;</span><span class="st"> </span>Budget <span class="op">&lt;</span><span class="st"> </span><span class="dv">1000</span>, <span class="st">&quot;Reasonable&quot;</span>,</span>
<span id="cb944-5"><a href="datahandling2.html#cb944-5"></a>                                 <span class="st">&quot;Expensive&quot;</span>))) <span class="op">%&gt;%</span></span>
<span id="cb944-6"><a href="datahandling2.html#cb944-6"></a><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(Budget3)) <span class="op">%&gt;%</span></span>
<span id="cb944-7"><a href="datahandling2.html#cb944-7"></a><span class="st">  </span><span class="kw">group_by</span>(Pref, Budget3) <span class="op">%&gt;%</span></span>
<span id="cb944-8"><a href="datahandling2.html#cb944-8"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">N =</span> <span class="kw">n</span>(),         </span>
<span id="cb944-9"><a href="datahandling2.html#cb944-9"></a>            <span class="dt">.groups =</span> <span class="st">&quot;drop&quot;</span>)</span></code></pre></div>
<p><code>case_when()</code>を使うと以下のような書き方になります。</p>
<div class="sourceCode" id="cb945"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb945-1"><a href="datahandling2.html#cb945-1"></a><span class="co"># ifelse()を使う場合</span></span>
<span id="cb945-2"><a href="datahandling2.html#cb945-2"></a>df <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb945-3"><a href="datahandling2.html#cb945-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Budget3 =</span> <span class="kw">case_when</span>(Budget <span class="op">&lt;</span><span class="st"> </span><span class="dv">500</span>                  <span class="op">~</span><span class="st"> &quot;Cheap&quot;</span>,</span>
<span id="cb945-4"><a href="datahandling2.html#cb945-4"></a>                             Budget <span class="op">&gt;=</span><span class="st"> </span><span class="dv">500</span> <span class="op">&amp;</span><span class="st"> </span>Budget <span class="op">&lt;</span><span class="st"> </span><span class="dv">1000</span> <span class="op">~</span><span class="st"> &quot;Reasonable&quot;</span>,</span>
<span id="cb945-5"><a href="datahandling2.html#cb945-5"></a>                             Budget <span class="op">&gt;=</span><span class="st"> </span><span class="dv">1000</span>                <span class="op">~</span><span class="st"> &quot;Expensive&quot;</span>),</span>
<span id="cb945-6"><a href="datahandling2.html#cb945-6"></a>         <span class="co"># 新しく出来た変数をfactor型にその場で変換することも可能</span></span>
<span id="cb945-7"><a href="datahandling2.html#cb945-7"></a>         <span class="dt">Budget3 =</span> <span class="kw">factor</span>(Budget3, </span>
<span id="cb945-8"><a href="datahandling2.html#cb945-8"></a>                          <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;Cheap&quot;</span>, <span class="st">&quot;Reasonable&quot;</span>, <span class="st">&quot;Expensive&quot;</span>))) <span class="op">%&gt;%</span></span>
<span id="cb945-9"><a href="datahandling2.html#cb945-9"></a><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(Budget3)) <span class="op">%&gt;%</span></span>
<span id="cb945-10"><a href="datahandling2.html#cb945-10"></a><span class="st">  </span><span class="kw">group_by</span>(Pref, Budget3) <span class="op">%&gt;%</span></span>
<span id="cb945-11"><a href="datahandling2.html#cb945-11"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">N =</span> <span class="kw">n</span>(),         </span>
<span id="cb945-12"><a href="datahandling2.html#cb945-12"></a>            <span class="dt">.groups =</span> <span class="st">&quot;drop&quot;</span>)</span></code></pre></div>
<p>書く手間の観点では<code>case_when()</code>は<code>ifelse()</code>と大きく違いはないかも知れませんが、コードが非常に読みやすくなっています。<code>case_when()</code>関数の書き方は以下の通りです。</p>
<div class="sourceCode" id="cb946"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb946-1"><a href="datahandling2.html#cb946-1"></a><span class="co"># case_when()の使い方</span></span>
<span id="cb946-2"><a href="datahandling2.html#cb946-2"></a>データフレーム名 <span class="op">%&gt;%</span></span>
<span id="cb946-3"><a href="datahandling2.html#cb946-3"></a><span class="st">  </span><span class="kw">mutate</span>(新変数名 =<span class="st"> </span><span class="kw">case_when</span>(条件1 <span class="op">~</span><span class="st"> </span>条件1を満たす場合の結果値, </span>
<span id="cb946-4"><a href="datahandling2.html#cb946-4"></a>                             条件2 <span class="op">~</span><span class="st"> </span>条件2を満たす場合の結果値, </span>
<span id="cb946-5"><a href="datahandling2.html#cb946-5"></a>                             条件3 <span class="op">~</span><span class="st"> </span>条件3を満たす場合の結果値, </span>
<span id="cb946-6"><a href="datahandling2.html#cb946-6"></a>                             ...))</span></code></pre></div>
<p>似たような機能をする関数として<code>recode()</code>関数があります。これは変数の値を単純に置換したい場合に便利な関数です。たとえば、都府県名をローマ字に変換するケースを考えてみましょう。</p>
<div class="sourceCode" id="cb947"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb947-1"><a href="datahandling2.html#cb947-1"></a><span class="co"># recode()を使う場合</span></span>
<span id="cb947-2"><a href="datahandling2.html#cb947-2"></a>df2 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb947-3"><a href="datahandling2.html#cb947-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Pref2 =</span> <span class="kw">recode</span>(Pref,</span>
<span id="cb947-4"><a href="datahandling2.html#cb947-4"></a>                        <span class="st">&quot;東京都&quot;</span>   =<span class="st"> &quot;Tokyo&quot;</span>,</span>
<span id="cb947-5"><a href="datahandling2.html#cb947-5"></a>                        <span class="st">&quot;神奈川県&quot;</span> =<span class="st"> &quot;Kanagawa&quot;</span>,</span>
<span id="cb947-6"><a href="datahandling2.html#cb947-6"></a>                        <span class="st">&quot;千葉県&quot;</span>   =<span class="st"> &quot;Chiba&quot;</span>,</span>
<span id="cb947-7"><a href="datahandling2.html#cb947-7"></a>                        <span class="st">&quot;埼玉県&quot;</span>   =<span class="st"> &quot;Saitama&quot;</span>,</span>
<span id="cb947-8"><a href="datahandling2.html#cb947-8"></a>                        <span class="st">&quot;大阪府&quot;</span>   =<span class="st"> &quot;Osaka&quot;</span>,</span>
<span id="cb947-9"><a href="datahandling2.html#cb947-9"></a>                        <span class="st">&quot;京都府&quot;</span>   =<span class="st"> &quot;Kyoto&quot;</span>,</span>
<span id="cb947-10"><a href="datahandling2.html#cb947-10"></a>                        <span class="st">&quot;兵庫県&quot;</span>   =<span class="st"> &quot;Hyogo&quot;</span>,</span>
<span id="cb947-11"><a href="datahandling2.html#cb947-11"></a>                        <span class="st">&quot;奈良県&quot;</span>   =<span class="st"> &quot;Nara&quot;</span>,</span>
<span id="cb947-12"><a href="datahandling2.html#cb947-12"></a>                        <span class="st">&quot;和歌山県&quot;</span> =<span class="st"> &quot;Wakayama&quot;</span>,</span>
<span id="cb947-13"><a href="datahandling2.html#cb947-13"></a>                        <span class="dt">.default  =</span> <span class="st">&quot;NA&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 9 x 6
##   Pref     Budget_Mean ScoreN_Sum Score_Mean     N Pref2   
##   &lt;chr&gt;          &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt; &lt;chr&gt;   
## 1 京都府         1399.        216       3.68   414 Kyoto   
## 2 埼玉県         1147.        278       3.64  1000 Saitama 
## 3 神奈川県       1239.        587       3.53  1000 Kanagawa
## 4 千葉県         1124.        259       3.72  1000 Chiba   
## 5 大阪府         1203.        516       3.77  1000 Osaka   
## 6 東京都         1283.       1165       3.67  1000 Tokyo   
## 7 奈良県         1169.         45       3.85   147 Nara    
## 8 兵庫県         1197.        230       3.54   591 Hyogo   
## 9 和歌山県       1252          83       3.97   140 Wakayama</code></pre>
<p>使い方は非常に直感的です。</p>
<div class="sourceCode" id="cb949"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb949-1"><a href="datahandling2.html#cb949-1"></a><span class="co"># case_when()の使い方</span></span>
<span id="cb949-2"><a href="datahandling2.html#cb949-2"></a>データフレーム名 <span class="op">%&gt;%</span></span>
<span id="cb949-3"><a href="datahandling2.html#cb949-3"></a><span class="st">  </span><span class="kw">mutate</span>(新変数名 =<span class="st"> </span><span class="kw">recode</span>(元の変数名,</span>
<span id="cb949-4"><a href="datahandling2.html#cb949-4"></a>                            元の値1 =<span class="st">  </span>新しい値1, </span>
<span id="cb949-5"><a href="datahandling2.html#cb949-5"></a>                            元の値2 =<span class="st">  </span>新しい値2, </span>
<span id="cb949-6"><a href="datahandling2.html#cb949-6"></a>                            元の値3 =<span class="st">  </span>新しい値3, </span>
<span id="cb949-7"><a href="datahandling2.html#cb949-7"></a>                            ...,</span>
<span id="cb949-8"><a href="datahandling2.html#cb949-8"></a>                            <span class="dt">.default =</span> 該当しない場合の値))</span></code></pre></div>
<p>最後の<code>.default</code>引数は、もし該当する値がない場合に返す値を意味し、長さ1のベクトルを指定します。もし、指定しない場合は<code>NA</code>が表示されます。また、ここには紹介しておりませんでしたが、<code>.missing</code>引数もあり、これは欠損値の場合に返す値を意味します。</p>
<p>もう一つ注意すべきところは、今回はcharacter型変数をcharacter型へ変換したため、「<code>"東京都" = "Tokyo"</code>」のような書き方をしました。しかし、numeric型からcharacter型に変換する場合は数字の部分を<code>`</code>で囲む必要があります。たとえば、「<code>`1` = "Tokyo"</code>」といった形式です。ただし、character型からnumeric型への場合は「<code>"東京都" = 1</code>」で構いません。</p>
<p><code>recode()</code>は値をまとめる際にも便利です。たとえば、<code>EastJapan</code>という変数を作成し、関東なら<code>1</code>を、それ以外なら<code>0</code>を付けるとします。そして、これは<code>Pref</code>変数の後に位置づけます。</p>
<div class="sourceCode" id="cb950"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb950-1"><a href="datahandling2.html#cb950-1"></a><span class="co"># 都府県を関東か否かでまとめる</span></span>
<span id="cb950-2"><a href="datahandling2.html#cb950-2"></a>df2 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb950-3"><a href="datahandling2.html#cb950-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">EastJapan =</span> <span class="kw">recode</span>(Pref,</span>
<span id="cb950-4"><a href="datahandling2.html#cb950-4"></a>                            <span class="st">&quot;東京都&quot;</span>   =<span class="st"> </span><span class="dv">1</span>,</span>
<span id="cb950-5"><a href="datahandling2.html#cb950-5"></a>                            <span class="st">&quot;神奈川県&quot;</span> =<span class="st"> </span><span class="dv">1</span>,</span>
<span id="cb950-6"><a href="datahandling2.html#cb950-6"></a>                            <span class="st">&quot;千葉県&quot;</span>   =<span class="st"> </span><span class="dv">1</span>,</span>
<span id="cb950-7"><a href="datahandling2.html#cb950-7"></a>                            <span class="st">&quot;埼玉県&quot;</span>   =<span class="st"> </span><span class="dv">1</span>,</span>
<span id="cb950-8"><a href="datahandling2.html#cb950-8"></a>                            <span class="st">&quot;大阪府&quot;</span>   =<span class="st"> </span><span class="dv">0</span>,</span>
<span id="cb950-9"><a href="datahandling2.html#cb950-9"></a>                            <span class="st">&quot;京都府&quot;</span>   =<span class="st"> </span><span class="dv">0</span>,</span>
<span id="cb950-10"><a href="datahandling2.html#cb950-10"></a>                            <span class="st">&quot;兵庫県&quot;</span>   =<span class="st"> </span><span class="dv">0</span>,</span>
<span id="cb950-11"><a href="datahandling2.html#cb950-11"></a>                            <span class="st">&quot;奈良県&quot;</span>   =<span class="st"> </span><span class="dv">0</span>,</span>
<span id="cb950-12"><a href="datahandling2.html#cb950-12"></a>                            <span class="st">&quot;和歌山県&quot;</span> =<span class="st"> </span><span class="dv">0</span>,</span>
<span id="cb950-13"><a href="datahandling2.html#cb950-13"></a>                            <span class="dt">.default  =</span> <span class="dv">0</span>),</span>
<span id="cb950-14"><a href="datahandling2.html#cb950-14"></a>         <span class="dt">.after =</span> Pref)</span></code></pre></div>
<pre><code>## # A tibble: 9 x 6
##   Pref     EastJapan Budget_Mean ScoreN_Sum Score_Mean     N
##   &lt;chr&gt;        &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;
## 1 京都府           0       1399.        216       3.68   414
## 2 埼玉県           1       1147.        278       3.64  1000
## 3 神奈川県         1       1239.        587       3.53  1000
## 4 千葉県           1       1124.        259       3.72  1000
## 5 大阪府           0       1203.        516       3.77  1000
## 6 東京都           1       1283.       1165       3.67  1000
## 7 奈良県           0       1169.         45       3.85   147
## 8 兵庫県           0       1197.        230       3.54   591
## 9 和歌山県         0       1252          83       3.97   140</code></pre>
<p>ただし、関東以外は全て0になるため、以下のように省略することも可能です。</p>
<div class="sourceCode" id="cb952"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb952-1"><a href="datahandling2.html#cb952-1"></a><span class="co"># .default引数を指定する場合</span></span>
<span id="cb952-2"><a href="datahandling2.html#cb952-2"></a>df3 &lt;-<span class="st"> </span>df2 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb952-3"><a href="datahandling2.html#cb952-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">EastJapan =</span> <span class="kw">recode</span>(Pref,</span>
<span id="cb952-4"><a href="datahandling2.html#cb952-4"></a>                            <span class="st">&quot;東京都&quot;</span>   =<span class="st"> </span><span class="dv">1</span>,</span>
<span id="cb952-5"><a href="datahandling2.html#cb952-5"></a>                            <span class="st">&quot;神奈川県&quot;</span> =<span class="st"> </span><span class="dv">1</span>,</span>
<span id="cb952-6"><a href="datahandling2.html#cb952-6"></a>                            <span class="st">&quot;千葉県&quot;</span>   =<span class="st"> </span><span class="dv">1</span>,</span>
<span id="cb952-7"><a href="datahandling2.html#cb952-7"></a>                            <span class="st">&quot;埼玉県&quot;</span>   =<span class="st"> </span><span class="dv">1</span>,</span>
<span id="cb952-8"><a href="datahandling2.html#cb952-8"></a>                            <span class="dt">.default  =</span> <span class="dv">0</span>),</span>
<span id="cb952-9"><a href="datahandling2.html#cb952-9"></a>         <span class="dt">.after =</span> Pref)</span>
<span id="cb952-10"><a href="datahandling2.html#cb952-10"></a></span>
<span id="cb952-11"><a href="datahandling2.html#cb952-11"></a>df3</span></code></pre></div>
<pre><code>## # A tibble: 9 x 6
##   Pref     EastJapan Budget_Mean ScoreN_Sum Score_Mean     N
##   &lt;chr&gt;        &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;
## 1 京都府           0       1399.        216       3.68   414
## 2 埼玉県           1       1147.        278       3.64  1000
## 3 神奈川県         1       1239.        587       3.53  1000
## 4 千葉県           1       1124.        259       3.72  1000
## 5 大阪府           0       1203.        516       3.77  1000
## 6 東京都           1       1283.       1165       3.67  1000
## 7 奈良県           0       1169.         45       3.85   147
## 8 兵庫県           0       1197.        230       3.54   591
## 9 和歌山県         0       1252          83       3.97   140</code></pre>
<p>新しく出来た<code>EastJapan</code>のデータ型はなんでしょうか。</p>
<div class="sourceCode" id="cb954"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb954-1"><a href="datahandling2.html#cb954-1"></a><span class="kw">class</span>(df3<span class="op">$</span>EastJapan)</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p><code>EastJapan</code>はnumeric型ですね。もし、これをfactor型にしたい場合はどうすればよいでしょうか。それは<code>mutate()</code>内で<code>EastJapan</code>を生成した後に<code>factor()</code>関数を使うだけです。</p>
<div class="sourceCode" id="cb956"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb956-1"><a href="datahandling2.html#cb956-1"></a><span class="co"># EastJapan変数をfactor型にする</span></span>
<span id="cb956-2"><a href="datahandling2.html#cb956-2"></a>df3 &lt;-<span class="st"> </span>df2 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb956-3"><a href="datahandling2.html#cb956-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">EastJapan =</span> <span class="kw">recode</span>(Pref,</span>
<span id="cb956-4"><a href="datahandling2.html#cb956-4"></a>                            <span class="st">&quot;東京都&quot;</span>   =<span class="st"> </span><span class="dv">1</span>,</span>
<span id="cb956-5"><a href="datahandling2.html#cb956-5"></a>                            <span class="st">&quot;神奈川県&quot;</span> =<span class="st"> </span><span class="dv">1</span>,</span>
<span id="cb956-6"><a href="datahandling2.html#cb956-6"></a>                            <span class="st">&quot;千葉県&quot;</span>   =<span class="st"> </span><span class="dv">1</span>,</span>
<span id="cb956-7"><a href="datahandling2.html#cb956-7"></a>                            <span class="st">&quot;埼玉県&quot;</span>   =<span class="st"> </span><span class="dv">1</span>,</span>
<span id="cb956-8"><a href="datahandling2.html#cb956-8"></a>                            <span class="dt">.default  =</span> <span class="dv">0</span>),</span>
<span id="cb956-9"><a href="datahandling2.html#cb956-9"></a>         <span class="dt">EastJapan =</span> <span class="kw">factor</span>(EastJapan, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)),</span>
<span id="cb956-10"><a href="datahandling2.html#cb956-10"></a>         <span class="dt">.after =</span> Pref)</span>
<span id="cb956-11"><a href="datahandling2.html#cb956-11"></a></span>
<span id="cb956-12"><a href="datahandling2.html#cb956-12"></a>df3<span class="op">$</span>EastJapan</span></code></pre></div>
<pre><code>## [1] 0 1 1 1 0 1 0 0 0
## Levels: 0 1</code></pre>
<p><code>EastJapan</code>がfactor型になりました。実は、<code>recode</code>は再コーディングと同時にfactor化をしてくれる機能があります。ただし、<code>recode()</code>関数でなく、<code>recode_factor()</code>関数を使います。</p>
<div class="sourceCode" id="cb958"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb958-1"><a href="datahandling2.html#cb958-1"></a><span class="co"># recode_factor()を使う方法</span></span>
<span id="cb958-2"><a href="datahandling2.html#cb958-2"></a>df3 &lt;-<span class="st"> </span>df2 <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb958-3"><a href="datahandling2.html#cb958-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">EastJapan =</span> <span class="kw">recode_factor</span>(Pref,</span>
<span id="cb958-4"><a href="datahandling2.html#cb958-4"></a>                                   <span class="st">&quot;東京都&quot;</span>   =<span class="st"> </span><span class="dv">1</span>,</span>
<span id="cb958-5"><a href="datahandling2.html#cb958-5"></a>                                   <span class="st">&quot;神奈川県&quot;</span> =<span class="st"> </span><span class="dv">1</span>,</span>
<span id="cb958-6"><a href="datahandling2.html#cb958-6"></a>                                   <span class="st">&quot;千葉県&quot;</span>   =<span class="st"> </span><span class="dv">1</span>,</span>
<span id="cb958-7"><a href="datahandling2.html#cb958-7"></a>                                   <span class="st">&quot;埼玉県&quot;</span>   =<span class="st"> </span><span class="dv">1</span>,</span>
<span id="cb958-8"><a href="datahandling2.html#cb958-8"></a>                                   <span class="dt">.default  =</span> <span class="dv">0</span>),</span>
<span id="cb958-9"><a href="datahandling2.html#cb958-9"></a>         <span class="dt">.after =</span> Pref)</span>
<span id="cb958-10"><a href="datahandling2.html#cb958-10"></a></span>
<span id="cb958-11"><a href="datahandling2.html#cb958-11"></a>df3<span class="op">$</span>EastJapan</span></code></pre></div>
<pre><code>## [1] 0 1 1 1 0 1 0 0 0
## Levels: 1 0</code></pre>
<p>ただし、levelの順番は<code>recode_factor()</code>内で定義された順番になることに注意してください。factor型のより詳細な扱いについては第<a href="factor.html#factor">12</a>章で解説します。</p>
<hr />
</div>
</div>
<div id="handling2-rowwise" class="section level2">
<h2><span class="header-section-number">11.4</span> 行単位の操作</h2>
<p>ここでは行単位の操作について考えたいと思います。第<a href="datahandling1.html#handling1-select">10.3</a>章で使った<code>myDF1</code>を見てみましょう。</p>
<div class="sourceCode" id="cb960"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb960-1"><a href="datahandling2.html#cb960-1"></a>myDF1 &lt;-<span class="st"> </span><span class="kw">data.frame</span>(</span>
<span id="cb960-2"><a href="datahandling2.html#cb960-2"></a>  <span class="dt">ID  =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">5</span>,</span>
<span id="cb960-3"><a href="datahandling2.html#cb960-3"></a>  <span class="dt">X1  =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">2</span>, <span class="dv">7</span>),</span>
<span id="cb960-4"><a href="datahandling2.html#cb960-4"></a>  <span class="dt">Y1  =</span> <span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb960-5"><a href="datahandling2.html#cb960-5"></a>  <span class="dt">X1D =</span> <span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">6</span>, <span class="dv">9</span>),</span>
<span id="cb960-6"><a href="datahandling2.html#cb960-6"></a>  <span class="dt">X2  =</span> <span class="kw">c</span>(<span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">0</span>, <span class="dv">2</span>),</span>
<span id="cb960-7"><a href="datahandling2.html#cb960-7"></a>  <span class="dt">Y2  =</span> <span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">1</span>),</span>
<span id="cb960-8"><a href="datahandling2.html#cb960-8"></a>  <span class="dt">X2D =</span> <span class="kw">c</span>(<span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">5</span>, <span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb960-9"><a href="datahandling2.html#cb960-9"></a>  <span class="dt">X3  =</span> <span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">0</span>, <span class="dv">2</span>),</span>
<span id="cb960-10"><a href="datahandling2.html#cb960-10"></a>  <span class="dt">Y3  =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">9</span>, <span class="dv">1</span>, <span class="dv">3</span>),</span>
<span id="cb960-11"><a href="datahandling2.html#cb960-11"></a>  <span class="dt">X3D =</span> <span class="kw">c</span>(<span class="dv">9</span>, <span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">8</span>)</span>
<span id="cb960-12"><a href="datahandling2.html#cb960-12"></a>)</span>
<span id="cb960-13"><a href="datahandling2.html#cb960-13"></a></span>
<span id="cb960-14"><a href="datahandling2.html#cb960-14"></a>myDF1</span></code></pre></div>
<pre><code>##   ID X1 Y1 X1D X2 Y2 X2D X3 Y3 X3D
## 1  1  2  3   4  5  3   8  3  1   9
## 2  2  4  5   2  5  3   9  0  5   1
## 3  3  6  1   1  6  2   5  3  9   3
## 4  4  2  1   6  0  3   0  0  1   3
## 5  5  7  0   9  2  1   1  2  3   8</code></pre>
<p>ここで<code>X1</code>と<code>X2</code>と<code>X3</code>の平均値を計算し、<code>X_Mean</code>という名の変数にする場合、以下のような書き方が普通でしょう。</p>
<div class="sourceCode" id="cb962"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb962-1"><a href="datahandling2.html#cb962-1"></a>myDF1 <span class="op">%&gt;%</span></span>
<span id="cb962-2"><a href="datahandling2.html#cb962-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">X_Mean =</span> <span class="kw">mean</span>(<span class="kw">c</span>(X1, X2, X3)))</span></code></pre></div>
<pre><code>##   ID X1 Y1 X1D X2 Y2 X2D X3 Y3 X3D   X_Mean
## 1  1  2  3   4  5  3   8  3  1   9 3.133333
## 2  2  4  5   2  5  3   9  0  5   1 3.133333
## 3  3  6  1   1  6  2   5  3  9   3 3.133333
## 4  4  2  1   6  0  3   0  0  1   3 3.133333
## 5  5  7  0   9  2  1   1  2  3   8 3.133333</code></pre>
<p>あら、なんかおかしくありませんか。1行目の場合、<code>X1</code>と<code>X2</code>、<code>X3</code>それぞれ2、5、3であり、平均値は3.333であるはずなのに3.133になりました。これは2行目以降も同じです。なぜでしょうか。</p>
<p>実は<code>dplyr</code>は行単位の計算が苦手です。実際、データフレームというのは既に説明したとおり、縦ベクトルを横に並べたものです。列をまたがる場合、データ型が異なる場合も多いため、そもそも使う場面も多くありません。したがって、以下のような書き方が必要でした。</p>
<div class="sourceCode" id="cb964"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb964-1"><a href="datahandling2.html#cb964-1"></a>myDF1 <span class="op">%&gt;%</span></span>
<span id="cb964-2"><a href="datahandling2.html#cb964-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">X_Mean =</span> (X1 <span class="op">+</span><span class="st"> </span>X2 <span class="op">+</span><span class="st"> </span>X3) <span class="op">/</span><span class="st"> </span><span class="dv">3</span>)</span></code></pre></div>
<pre><code>##   ID X1 Y1 X1D X2 Y2 X2D X3 Y3 X3D    X_Mean
## 1  1  2  3   4  5  3   8  3  1   9 3.3333333
## 2  2  4  5   2  5  3   9  0  5   1 3.0000000
## 3  3  6  1   1  6  2   5  3  9   3 5.0000000
## 4  4  2  1   6  0  3   0  0  1   3 0.6666667
## 5  5  7  0   9  2  1   1  2  3   8 3.6666667</code></pre>
<p>先ほどの<code>mean(c(X1, X2, X3))</code>は(<code>X1</code>列と<code>X2</code>列、<code>X3</code>列)の平均値です。<code>X1</code>は長さ1のベクトルではなく、その列全体を指すものです。つまり、<code>mean(c(X1, X2, X3))</code>は<code>mean(c(myD1F$X1, myDF1$X2, myDF1$X3))</code>と同じことになります。だから全て3.133という結果が得られました。ただし、後者はベクトル同士の加減乗除になるため問題ありません。実際<code>c(1, 2, 3) + c(3, 5, 0)</code>は同じ位置の要素同士の計算になることを既に第<a href="datastructure.html#structure-vector">8.2</a>章で説明しました。</p>
<p>ここで<code>mean()</code>関数を使う場合には全ての演算を、一行一行に分けて行う必要があります。ある一行のみに限定する場合、<code>mean(c(X1, X2, X3))</code>の<code>X1</code>などは長さ1のベクトルになるため、<code>(X1 + X2 + X3) / 3</code>と同じことになります。この「一行単位で処理を行う」ことを指定する関数が<code>rowwise()</code>関数です。これは行単位の作業を行う前に指定するだけです。</p>
<div class="sourceCode" id="cb966"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb966-1"><a href="datahandling2.html#cb966-1"></a>myDF1 <span class="op">%&gt;%</span></span>
<span id="cb966-2"><a href="datahandling2.html#cb966-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span></span>
<span id="cb966-3"><a href="datahandling2.html#cb966-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">X_Mean =</span> <span class="kw">mean</span>(<span class="kw">c</span>(X1, X2, X3)))</span></code></pre></div>
<pre><code>## # A tibble: 5 x 11
## # Rowwise: 
##      ID    X1    Y1   X1D    X2    Y2   X2D    X3    Y3   X3D X_Mean
##   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1     1     2     3     4     5     3     8     3     1     9  3.33 
## 2     2     4     5     2     5     3     9     0     5     1  3    
## 3     3     6     1     1     6     2     5     3     9     3  5    
## 4     4     2     1     6     0     3     0     0     1     3  0.667
## 5     5     7     0     9     2     1     1     2     3     8  3.67</code></pre>
<p>これで問題なく行単位の処理ができるようになりました。今回は変数が3つのみだったので、これで問題ありませんが、変数が多くなると<code>:</code>や<code>starts_with()</code>、<code>num_range()</code>などを使って変数を選択したくなります。この場合は計算する関数内に<code>c_across()</code>を入れます。ここでは<code>X1</code>列から<code>X3D</code>列までの平均値を求めてみましょう。</p>
<div class="sourceCode" id="cb968"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb968-1"><a href="datahandling2.html#cb968-1"></a>myDF1 <span class="op">%&gt;%</span></span>
<span id="cb968-2"><a href="datahandling2.html#cb968-2"></a><span class="st">  </span><span class="kw">rowwise</span>() <span class="op">%&gt;%</span></span>
<span id="cb968-3"><a href="datahandling2.html#cb968-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">X_Mean =</span> <span class="kw">mean</span>(X1<span class="op">:</span>X3D))</span></code></pre></div>
<pre><code>## # A tibble: 5 x 11
## # Rowwise: 
##      ID    X1    Y1   X1D    X2    Y2   X2D    X3    Y3   X3D X_Mean
##   &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1     1     2     3     4     5     3     8     3     1     9    5.5
## 2     2     4     5     2     5     3     9     0     5     1    2.5
## 3     3     6     1     1     6     2     5     3     9     3    4.5
## 4     4     2     1     6     0     3     0     0     1     3    2.5
## 5     5     7     0     9     2     1     1     2     3     8    7.5</code></pre>
<p>実は<code>rowwise()</code>関数、2020年6月に公開されたdplyr 1.0.0で注目された関数ですが、昔のdplyrにも<code>rowwise()</code>関数はありました。ただし、<code>purrr</code>パッケージや<code>tidyr</code>パッケージの<code>nest()</code>関数などにより使い道がなくなりましたが、なぜか華麗に復活しました。データ分析に使うデータは基本単位は列であるため、実際に<code>rowwise()</code>が使われる場面は今の段階では多くないでしょう。また、簡単な作業なら<code>X1 + X2</code>のような演算でも対応できます。それでも、覚えておけば便利な関数であることには間違いありません。</p>
<hr />
</div>
<div id="handling2-merge" class="section level2">
<h2><span class="header-section-number">11.5</span> データの結合</h2>
<div id="行の結合" class="section level3">
<h3><span class="header-section-number">11.5.1</span> 行の結合</h3>
<p>まずは、複数のデータフレームまたはtibbleを縦に結合する方法について解説します。イメージとしては図<a href="datahandling2.html#fig:merge-row">11.1</a>のようなものです。</p>
<div class="figure" style="text-align: center"><span id="fig:merge-row"></span>
<img src="Figures/Handling2/Merge1.png" alt="行の結合" width="80%" />
<p class="caption">
図 11.1: 行の結合
</p>
</div>
<p>行を結合する際には<code>dplyr</code>パッケージの<code>bind_rows()</code>関数を使います。この関数の使い方は以下の通りです。</p>
<div class="sourceCode" id="cb970"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb970-1"><a href="datahandling2.html#cb970-1"></a><span class="co"># 新しいデータ名ではなく、既にあるデータ名にすると上書きとなる</span></span>
<span id="cb970-2"><a href="datahandling2.html#cb970-2"></a>新しいデータ名 &lt;-<span class="st">  </span><span class="kw">bind_rows</span>(データ1, データ2, ...)</span></code></pre></div>
<p>それでは早速実際に使ってみましょう。実習のために、4つのtibbleを作成します (tibbleでなくデータフレームでも問題ありません)。</p>
<div class="sourceCode" id="cb971"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb971-1"><a href="datahandling2.html#cb971-1"></a><span class="co"># tibble()の代わりにdata.frame()も可</span></span>
<span id="cb971-2"><a href="datahandling2.html#cb971-2"></a>rbind_df1 &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">X1 =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">3</span>,</span>
<span id="cb971-3"><a href="datahandling2.html#cb971-3"></a>                    <span class="dt">X2 =</span> <span class="kw">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;C&quot;</span>),</span>
<span id="cb971-4"><a href="datahandling2.html#cb971-4"></a>                    <span class="dt">X3 =</span> <span class="kw">c</span>(T, T, F)) <span class="co"># TRUEとFALSEはTはFと省略可能</span></span>
<span id="cb971-5"><a href="datahandling2.html#cb971-5"></a></span>
<span id="cb971-6"><a href="datahandling2.html#cb971-6"></a>rbind_df2 &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">X1 =</span> <span class="dv">4</span><span class="op">:</span><span class="dv">6</span>,</span>
<span id="cb971-7"><a href="datahandling2.html#cb971-7"></a>                    <span class="dt">X2 =</span> <span class="kw">c</span>(<span class="st">&quot;D&quot;</span>, <span class="st">&quot;E&quot;</span>, <span class="st">&quot;F&quot;</span>),</span>
<span id="cb971-8"><a href="datahandling2.html#cb971-8"></a>                    <span class="dt">X3 =</span> <span class="kw">c</span>(F, T, F))</span>
<span id="cb971-9"><a href="datahandling2.html#cb971-9"></a></span>
<span id="cb971-10"><a href="datahandling2.html#cb971-10"></a>rbind_df3 &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">X1 =</span> <span class="dv">7</span><span class="op">:</span><span class="dv">9</span>,</span>
<span id="cb971-11"><a href="datahandling2.html#cb971-11"></a>                    <span class="dt">X3 =</span> <span class="kw">c</span>(T, T, T),</span>
<span id="cb971-12"><a href="datahandling2.html#cb971-12"></a>                    <span class="dt">X2 =</span> <span class="kw">c</span>(<span class="st">&quot;G&quot;</span>, <span class="st">&quot;H&quot;</span>, <span class="st">&quot;I&quot;</span>))</span>
<span id="cb971-13"><a href="datahandling2.html#cb971-13"></a></span>
<span id="cb971-14"><a href="datahandling2.html#cb971-14"></a>rbind_df4 &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">X1 =</span> <span class="dv">10</span><span class="op">:</span><span class="dv">12</span>,</span>
<span id="cb971-15"><a href="datahandling2.html#cb971-15"></a>                    <span class="dt">X2 =</span> <span class="kw">c</span>(<span class="st">&quot;J&quot;</span>, <span class="st">&quot;K&quot;</span>, <span class="st">&quot;L&quot;</span>),</span>
<span id="cb971-16"><a href="datahandling2.html#cb971-16"></a>                    <span class="dt">X5 =</span> <span class="kw">c</span>(<span class="st">&quot;Song&quot;</span>, <span class="st">&quot;Yanai&quot;</span>, <span class="st">&quot;Hadley&quot;</span>))</span>
<span id="cb971-17"><a href="datahandling2.html#cb971-17"></a></span>
<span id="cb971-18"><a href="datahandling2.html#cb971-18"></a>rbind_df1 <span class="co"># rbind_df1を出力</span></span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##      X1 X2    X3   
##   &lt;int&gt; &lt;chr&gt; &lt;lgl&gt;
## 1     1 A     TRUE 
## 2     2 B     TRUE 
## 3     3 C     FALSE</code></pre>
<div class="sourceCode" id="cb973"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb973-1"><a href="datahandling2.html#cb973-1"></a>rbind_df2 <span class="co"># rbind_df2を出力</span></span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##      X1 X2    X3   
##   &lt;int&gt; &lt;chr&gt; &lt;lgl&gt;
## 1     4 D     FALSE
## 2     5 E     TRUE 
## 3     6 F     FALSE</code></pre>
<div class="sourceCode" id="cb975"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb975-1"><a href="datahandling2.html#cb975-1"></a>rbind_df3 <span class="co"># rbind_df3を出力</span></span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##      X1 X3    X2   
##   &lt;int&gt; &lt;lgl&gt; &lt;chr&gt;
## 1     7 TRUE  G    
## 2     8 TRUE  H    
## 3     9 TRUE  I</code></pre>
<div class="sourceCode" id="cb977"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb977-1"><a href="datahandling2.html#cb977-1"></a>rbind_df4 <span class="co"># rbind_df4を出力</span></span></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##      X1 X2    X5    
##   &lt;int&gt; &lt;chr&gt; &lt;chr&gt; 
## 1    10 J     Song  
## 2    11 K     Yanai 
## 3    12 L     Hadley</code></pre>
<p>まずは、<code>rbind_df1</code>と<code>rbind_df2</code>を結合してみます。この2つのデータは同じ変数が同じ順番で並んでいますね。</p>
<div class="sourceCode" id="cb979"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb979-1"><a href="datahandling2.html#cb979-1"></a>Binded_df1 &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(rbind_df1, rbind_df2)</span>
<span id="cb979-2"><a href="datahandling2.html#cb979-2"></a>Binded_df1</span></code></pre></div>
<pre><code>## # A tibble: 6 x 3
##      X1 X2    X3   
##   &lt;int&gt; &lt;chr&gt; &lt;lgl&gt;
## 1     1 A     TRUE 
## 2     2 B     TRUE 
## 3     3 C     FALSE
## 4     4 D     FALSE
## 5     5 E     TRUE 
## 6     6 F     FALSE</code></pre>
<p>2つのデータが結合されたことが確認できます。それでは<code>rbind_df1</code>と<code>rbind_df2</code>、<code>rbind_df3</code>はどうでしょうか。確かに3つのデータは同じ変数を持ちますが、<code>rbind_df3</code>は変数の順番が<code>X1</code>、<code>X3</code>、<code>X2</code>になっています。このまま結合するとエラーが出るでしょうか。とりあえず、やってみます。</p>
<div class="sourceCode" id="cb981"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb981-1"><a href="datahandling2.html#cb981-1"></a>Binded_df2 &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(rbind_df1, rbind_df2, rbind_df3)</span>
<span id="cb981-2"><a href="datahandling2.html#cb981-2"></a>Binded_df2</span></code></pre></div>
<pre><code>## # A tibble: 9 x 3
##      X1 X2    X3   
##   &lt;int&gt; &lt;chr&gt; &lt;lgl&gt;
## 1     1 A     TRUE 
## 2     2 B     TRUE 
## 3     3 C     FALSE
## 4     4 D     FALSE
## 5     5 E     TRUE 
## 6     6 F     FALSE
## 7     7 G     TRUE 
## 8     8 H     TRUE 
## 9     9 I     TRUE</code></pre>
<p>このように変数の順番が異なっても、先に指定したデータの変数順で問題なく結合できました。これまでの作業は<code>dplyr</code>パッケージの<code>bind_rows()</code>を使わずに、R内蔵関数の<code>rbind()</code>でも同じやり方でできます。<code>bind_rows()</code>の特徴は、変数名が一致しない場合、つまり今回の例だと<code>rbind_df4</code>が含まれる場合です。<code>rbind_df1</code>から<code>rbind_df3</code>までは順番が違っても<code>X1</code>、<code>X2</code>、<code>X3</code>変数で構成されていました。一方、<code>rbind_dr4</code>には<code>X3</code>がなく、新たに<code>X4</code>という変数があります。これを<code>rbind()</code>関数で結合するとエラーが出力されます。</p>
<div class="sourceCode" id="cb983"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb983-1"><a href="datahandling2.html#cb983-1"></a><span class="co"># rbind()を使う場合</span></span>
<span id="cb983-2"><a href="datahandling2.html#cb983-2"></a><span class="kw">rbind</span>(rbind_df1, rbind_df2, rbind_df3, rbind_df4)</span></code></pre></div>
<pre><code>## Error in match.names(clabs, names(xi)): names do not match previous names</code></pre>
<p>一方、<code>bind_rows()</code>はどうでしょうか。</p>
<div class="sourceCode" id="cb985"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb985-1"><a href="datahandling2.html#cb985-1"></a>Binded_df3 &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(rbind_df1, rbind_df2, rbind_df3, rbind_df4)</span>
<span id="cb985-2"><a href="datahandling2.html#cb985-2"></a>Binded_df3</span></code></pre></div>
<pre><code>## # A tibble: 12 x 4
##       X1 X2    X3    X5    
##    &lt;int&gt; &lt;chr&gt; &lt;lgl&gt; &lt;chr&gt; 
##  1     1 A     TRUE  &lt;NA&gt;  
##  2     2 B     TRUE  &lt;NA&gt;  
##  3     3 C     FALSE &lt;NA&gt;  
##  4     4 D     FALSE &lt;NA&gt;  
##  5     5 E     TRUE  &lt;NA&gt;  
##  6     6 F     FALSE &lt;NA&gt;  
##  7     7 G     TRUE  &lt;NA&gt;  
##  8     8 H     TRUE  &lt;NA&gt;  
##  9     9 I     TRUE  &lt;NA&gt;  
## 10    10 J     NA    Song  
## 11    11 K     NA    Yanai 
## 12    12 L     NA    Hadley</code></pre>
<p><code>X1</code>から<code>X4</code>まで全ての列が生成され、元のデータにはなかった列に関しては<code>NA</code>で埋められています。</p>
<p>ならば、<code>bind_rows()</code>の完全勝利かというと、そうとは限りません。自分で架空した複数のデータフレーム、またはtibbleを結合する際、「このデータは全て同じ変数を持っているはず」と事前に分かっているなら<code>rbind()</code>の方が効果的です。なぜなら、変数名が異なる場合、エラーが出力されるからです。<code>bind_rows()</code>を使うと、コーディングミスなどにより、列名の相違がある場合でも結合してくれてしまうので、分析の結果を歪ませる可能性があります。</p>
</div>
<div id="列の結合" class="section level3">
<h3><span class="header-section-number">11.5.2</span> 列の結合</h3>
<p>実はデータ分析においてデータの結合といえば、列の結合が一般的です。これは図<a href="datahandling2.html#fig:merge-col">11.2</a>のような操作を意味します。</p>
<div class="figure" style="text-align: center"><span id="fig:merge-col"></span>
<img src="Figures/Handling2/Merge2.png" alt="列の結合" width="80%" />
<p class="caption">
図 11.2: 列の結合
</p>
</div>
<p>まずは、本章で作成した<code>df2</code>をもう一回作ってみます。</p>
<div class="sourceCode" id="cb987"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb987-1"><a href="datahandling2.html#cb987-1"></a>df2 &lt;-<span class="st"> </span>df <span class="op">%&gt;%</span></span>
<span id="cb987-2"><a href="datahandling2.html#cb987-2"></a><span class="st">  </span><span class="kw">group_by</span>(Pref) <span class="op">%&gt;%</span></span>
<span id="cb987-3"><a href="datahandling2.html#cb987-3"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">Budget_Mean =</span> <span class="kw">mean</span>(Budget, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb987-4"><a href="datahandling2.html#cb987-4"></a>            <span class="dt">ScoreN_Sum  =</span> <span class="kw">sum</span>(ScoreN, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb987-5"><a href="datahandling2.html#cb987-5"></a>            <span class="dt">Score_Mean  =</span> <span class="kw">mean</span>(Score, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</span>
<span id="cb987-6"><a href="datahandling2.html#cb987-6"></a>            <span class="dt">N           =</span> <span class="kw">n</span>(),</span>
<span id="cb987-7"><a href="datahandling2.html#cb987-7"></a>            <span class="dt">.groups     =</span> <span class="st">&quot;drop&quot;</span>)</span>
<span id="cb987-8"><a href="datahandling2.html#cb987-8"></a></span>
<span id="cb987-9"><a href="datahandling2.html#cb987-9"></a>df2</span></code></pre></div>
<pre><code>## # A tibble: 9 x 5
##   Pref     Budget_Mean ScoreN_Sum Score_Mean     N
##   &lt;chr&gt;          &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;
## 1 京都府         1399.        216       3.68   414
## 2 埼玉県         1147.        278       3.64  1000
## 3 神奈川県       1239.        587       3.53  1000
## 4 千葉県         1124.        259       3.72  1000
## 5 大阪府         1203.        516       3.77  1000
## 6 東京都         1283.       1165       3.67  1000
## 7 奈良県         1169.         45       3.85   147
## 8 兵庫県         1197.        230       3.54   591
## 9 和歌山県       1252          83       3.97   140</code></pre>
<p>ラーメン屋の店舗ですが、たしかにデータには埼玉、東京、大阪などは1000店舗しか入っておりません。実はもっと多いですが、ぐるなびAPIの仕様上、最大1000店舗しか情報取得が出来ないからです。ここに実際の店舗数が入っている新しいデータセット、<a href="Data/Ramen2.csv">Ramen2.csv</a>があります。これを読み込み、<code>df3</code>という名で格納しましょう。</p>
<div class="sourceCode" id="cb989"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb989-1"><a href="datahandling2.html#cb989-1"></a>df3 &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;Data/Ramen2.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Parsed with column specification:
## cols(
##   Pref = col_character(),
##   Pop = col_number(),
##   Area = col_number(),
##   RamenN = col_double(),
##   Turnout = col_double(),
##   LDP = col_double(),
##   CDP = col_double(),
##   DPFP = col_double(),
##   Komei = col_double(),
##   JIP = col_double(),
##   JCP = col_double(),
##   SDP = col_double(),
##   Reiwa = col_double(),
##   NHK = col_double(),
##   HRP = col_double()
## )</code></pre>
<div class="sourceCode" id="cb991"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb991-1"><a href="datahandling2.html#cb991-1"></a>df3</span></code></pre></div>
<pre><code>## # A tibble: 47 x 15
##    Pref     Pop   Area RamenN Turnout   LDP   CDP  DPFP Komei   JIP   JCP   SDP Reiwa
##    &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 北海道… 5.38e6 83424.   1454    53.8  32.3  20.8  6.65 11.7   7.78 11.6   1.31  3.85
##  2 青森県… 1.31e6  9646.    336    42.9  39.8  22.0  7.24 11.3   3.4   8.31  2.36  3.23
##  3 岩手県… 1.28e6 15275.    285    56.5  35.5  17.8 12.5   8.22  4.36 10.4   3.83  4.1 
##  4 宮城県… 2.33e6  7282.    557    51.2  39.6  17.8  9.02 11.1   4.6   7.89  2.1   4.41
##  5 秋田県… 1.02e6 11638.    301    56.3  44.5  13.5  8.64 10.6   4.48  8.09  3.77  3.33
##  6 山形県… 1.12e6  9323.    512    60.7  45.2  14.9  7.37  9.87  4.28  6.51  5.08  3.88
##  7 福島県… 1.91e6 13784.    550    52.4  38.2  13.6 12.1  12.8   5.31  7.99  3.01  4.04
##  8 茨城県… 2.92e6  6097.    663    45.0  39.3  15.2  7.15 15.1   6.73  7.73  1.46  4.09
##  9 栃木県… 1.97e6  6408.    595    44.1  40.3  18.9  9.94 12.8   4.9   5.04  1.03  3.82
## 10 群馬県… 1.97e6  6362.    488    48.2  40.6  16.4  9.76 12.4   4.67  7.58  1.87  3.71
## # … with 37 more rows, and 2 more variables: NHK &lt;dbl&gt;, HRP &lt;dbl&gt;</code></pre>
<table class="table table-striped table-hover table-condensed table-responsive" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;text-align: center;">
変数名
</th>
<th style="text-align:left;text-align: center;">
説明
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<code>Pref</code>
</td>
<td style="text-align:left;">
都道府県名
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Pop</code>
</td>
<td style="text-align:left;">
日本人人口 (2015年国勢調査)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Area</code>
</td>
<td style="text-align:left;">
面積 (2015年国勢調査)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>RamenN</code>
</td>
<td style="text-align:left;">
ぐるなびに登録されたラーメン屋の店舗数
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Turnout</code>
</td>
<td style="text-align:left;">
2019年参院選: 投票率 (比例)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>LDP</code>
</td>
<td style="text-align:left;">
2019年参院選: 自民党の得票率 (比例)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>CDP</code>
</td>
<td style="text-align:left;">
2019年参院選: 立憲民主党の得票率 (比例)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>DPFP</code>
</td>
<td style="text-align:left;">
2019年参院選: 国民民主党の得票率 (比例)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Komei</code>
</td>
<td style="text-align:left;">
2019年参院選: 公明党の得票率 (比例)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>JIP</code>
</td>
<td style="text-align:left;">
2019年参院選: 日本維新の会の得票率 (比例)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>JCP</code>
</td>
<td style="text-align:left;">
2019年参院選: 日本共産党の得票率 (比例)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>SDP</code>
</td>
<td style="text-align:left;">
2019年参院選: 社会民主党の得票率 (比例)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>Reiwa</code>
</td>
<td style="text-align:left;">
2019年参院選: れいわ新選組の得票率 (比例)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>NHK</code>
</td>
<td style="text-align:left;">
2019年参院選: NHKから国民を守る党の得票率 (比例)
</td>
</tr>
<tr>
<td style="text-align:left;">
<code>HRP</code>
</td>
<td style="text-align:left;">
2019年参院選: 幸福実現党の得票率 (比例)
</td>
</tr>
</tbody>
</table>
<p>本データは都道府県ごとの人口、面積、ぐるなびに登録されたラーメン屋の店舗数、2019年参議院議員通常選挙の結果が格納されています。人口と面積は2015年国勢調査、ぐるなびの情報は2020年6月時点での情報です。</p>
<p><code>df2</code>にデータ上の店舗数ではなく、実際の店舗数を新しい列として追加したい場合はどうすれば良いでしょうか。簡単な方法としては<code>df3</code>から情報を取得し、それを自分で入れる方法です。</p>
<div class="sourceCode" id="cb993"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb993-1"><a href="datahandling2.html#cb993-1"></a>df3 <span class="op">%&gt;%</span></span>
<span id="cb993-2"><a href="datahandling2.html#cb993-2"></a><span class="st">  </span><span class="co"># df2のPrefベクトルの要素と一致するものに絞る</span></span>
<span id="cb993-3"><a href="datahandling2.html#cb993-3"></a><span class="st">  </span><span class="kw">filter</span>(Pref <span class="op">%in%</span><span class="st"> </span>df2<span class="op">$</span>Pref) <span class="op">%&gt;%</span></span>
<span id="cb993-4"><a href="datahandling2.html#cb993-4"></a><span class="st">  </span><span class="co"># 都道府県名とラーメン屋の店舗数のみ抽出</span></span>
<span id="cb993-5"><a href="datahandling2.html#cb993-5"></a><span class="st">  </span><span class="kw">select</span>(Pref, RamenN)</span></code></pre></div>
<pre><code>## # A tibble: 9 x 2
##   Pref     RamenN
##   &lt;chr&gt;     &lt;dbl&gt;
## 1 埼玉県     1106
## 2 千葉県     1098
## 3 東京都     3220
## 4 神奈川県   1254
## 5 京都府      415
## 6 大阪府     1325
## 7 兵庫県      591
## 8 奈良県      147
## 9 和歌山県    140</code></pre>
<p>そして、この情報を<code>df2$RamenN &lt;- c(415, 1106, 1254, ...)</code>のように追加すればいいですね。</p>
<p>しかし、このような方法は非効率的です。そもそも<code>df3</code>から得られた結果の順番と<code>df2</code>の順番も一致しないので、一々対照しながらベクトルを作ることになります。ここで登場する関数が<code>dplyr</code>の<code>*_join()</code>関数群です。この関数群には4つの関数が含まれており、以下のような使い方になります。</p>
<div class="sourceCode" id="cb995"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb995-1"><a href="datahandling2.html#cb995-1"></a><span class="co"># 新しいデータ名ではなく、データ1またはデータ2の名前に格納すると上書きとなる</span></span>
<span id="cb995-2"><a href="datahandling2.html#cb995-2"></a></span>
<span id="cb995-3"><a href="datahandling2.html#cb995-3"></a><span class="co"># 1. データ1を基準に結合</span></span>
<span id="cb995-4"><a href="datahandling2.html#cb995-4"></a>新しいデータ名 &lt;-<span class="st">  </span><span class="kw">left_join</span>(データ1, データ2, <span class="dt">by =</span> <span class="st">&quot;共通変数名&quot;</span>)</span>
<span id="cb995-5"><a href="datahandling2.html#cb995-5"></a></span>
<span id="cb995-6"><a href="datahandling2.html#cb995-6"></a><span class="co"># 2. データ2を基準に結合</span></span>
<span id="cb995-7"><a href="datahandling2.html#cb995-7"></a>新しいデータ名 &lt;-<span class="st"> </span><span class="kw">right_join</span>(データ1, データ2, <span class="dt">by =</span> <span class="st">&quot;共通変数名&quot;</span>)</span>
<span id="cb995-8"><a href="datahandling2.html#cb995-8"></a></span>
<span id="cb995-9"><a href="datahandling2.html#cb995-9"></a><span class="co"># 3. データ1とデータ2両方に共通するケースのみ結合</span></span>
<span id="cb995-10"><a href="datahandling2.html#cb995-10"></a>新しいデータ名 &lt;-<span class="st"> </span><span class="kw">inner_join</span>(データ1, データ2, <span class="dt">by =</span> <span class="st">&quot;共通変数名&quot;</span>)</span>
<span id="cb995-11"><a href="datahandling2.html#cb995-11"></a></span>
<span id="cb995-12"><a href="datahandling2.html#cb995-12"></a><span class="co"># 4. データ1とデータ2、どれかに存在するケースを結合</span></span>
<span id="cb995-13"><a href="datahandling2.html#cb995-13"></a>新しいデータ名 &lt;-<span class="st">  </span><span class="kw">full_join</span>(データ1, データ2, <span class="dt">by =</span> <span class="st">&quot;共通変数名&quot;</span>)</span></code></pre></div>
<p>4つの関数の違いについて説明する前に、<code>by</code>引数について話したいと思います。これは主にキー (key)変数と呼ばれる変数で、それぞれのデータに同じ名前の変数がある必要があります。<code>df2</code>と<code>df3</code>だとそれが<code>Pref</code>変数です。どの<code>*_join()</code>関数でも、<code>Pref</code>の値が同じもの同士を結合することになります。</p>
<p>データのキー変数名が異なる場合もあります。たとえば、データ1の都道府県名は<code>Pref</code>という列に、データ2の都道府県名は<code>Prefecture</code>という列になっている場合、<code>by = "Pref"</code>でなく、<code>by = c("データ1のキー変数名" = "データ2のキー変数名")</code>、つまり、<code>by = c("Pref" = "Prefecture")</code>と指定します。</p>
<p>それでは、<code>df3</code>から都道府県名とラーメン屋の店舗数だけ抽出し、<code>df4</code>として格納しておきます。</p>
<div class="sourceCode" id="cb996"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb996-1"><a href="datahandling2.html#cb996-1"></a>df4 &lt;-<span class="st"> </span>df3 <span class="op">%&gt;%</span></span>
<span id="cb996-2"><a href="datahandling2.html#cb996-2"></a><span class="st">  </span><span class="kw">select</span>(Pref, RamenN)</span>
<span id="cb996-3"><a href="datahandling2.html#cb996-3"></a></span>
<span id="cb996-4"><a href="datahandling2.html#cb996-4"></a>df4</span></code></pre></div>
<pre><code>## # A tibble: 47 x 2
##    Pref   RamenN
##    &lt;chr&gt;   &lt;dbl&gt;
##  1 北海道   1454
##  2 青森県    336
##  3 岩手県    285
##  4 宮城県    557
##  5 秋田県    301
##  6 山形県    512
##  7 福島県    550
##  8 茨城県    663
##  9 栃木県    595
## 10 群馬県    488
## # … with 37 more rows</code></pre>
<p>これから共通変数名の値をキー (key)と呼びます。今回の例だと<code>Pref</code>が<code>df2</code>と<code>df4</code>のキー変数であり、その値である<code>"東京都"</code>、<code>"北海道"</code>などがキーです。</p>
<p>まずは、<code>inner_join()</code>の仕組みについて考えます。これは<code>df2</code>と<code>df4</code>に共通するキーを持つケースのみ結合する関数です。<code>df4</code>には<code>"北海道"</code>というキーがありますが、<code>df2</code>にはありません。したがって、キーが<code>"北海道"</code>のケースは結合から除外されます。これをイメージにしたものが図<a href="datahandling2.html#fig:inner-join">11.3</a>です<a href="#fn57" class="footnote-ref" id="fnref57"><sup>57</sup></a>。それぞれ3 <span class="math inline">\(\times\)</span> 2 (3行2列)のデータですが、キーが一致するケースは2つしかないため、結合後のデータは3 <span class="math inline">\(\times\)</span> 2となります。</p>
<div class="figure" style="text-align: center"><span id="fig:inner-join"></span>
<img src="Figures/Handling2/Merge_Inner.png" alt="`inner_join()`の仕組み" width="80%" />
<p class="caption">
図 11.3: <code>inner_join()</code>の仕組み
</p>
</div>
<p>実際にやってみましょう。</p>
<div class="sourceCode" id="cb998"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb998-1"><a href="datahandling2.html#cb998-1"></a><span class="kw">inner_join</span>(df2, df4, <span class="dt">by =</span> <span class="st">&quot;Pref&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 9 x 6
##   Pref     Budget_Mean ScoreN_Sum Score_Mean     N RamenN
##   &lt;chr&gt;          &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;
## 1 京都府         1399.        216       3.68   414    415
## 2 埼玉県         1147.        278       3.64  1000   1106
## 3 神奈川県       1239.        587       3.53  1000   1254
## 4 千葉県         1124.        259       3.72  1000   1098
## 5 大阪府         1203.        516       3.77  1000   1325
## 6 東京都         1283.       1165       3.67  1000   3220
## 7 奈良県         1169.         45       3.85   147    147
## 8 兵庫県         1197.        230       3.54   591    591
## 9 和歌山県       1252          83       3.97   140    140</code></pre>
<p>共通するキーは9つのみであり、結果として返されたデータの大きさも9 <span class="math inline">\(\times\)</span> 6です。<code>df2</code>に足された<code>df4</code>は2列のデータですが、キー変数である<code>Pref</code>は共通するため、1列のみ足されました。キー変数を両方残す場合は<code>keep = TRUE</code>引数を追加してください。</p>
<p>一方、<code>full_join()</code>は、すべてのキーに対して結合を行います (図<a href="datahandling2.html#fig:full-join">11.4</a>)。たとえば、<code>df2</code>には<code>"北海道"</code>というキーがありません。それでも新しく出来上がるデータには北海道の列が追加されます。ただし、道内店舗の平均予算、口コミ数などの情報はないため、欠損値が代入されます。</p>
<div class="figure" style="text-align: center"><span id="fig:full-join"></span>
<img src="Figures/Handling2/Merge_Full.png" alt="`full_join()`の仕組み" width="80%" />
<p class="caption">
図 11.4: <code>full_join()</code>の仕組み
</p>
</div>
<p>それでは実際、結果を確認してみましょう。今回は結合後、<code>RamenN</code>が大きい順で出力します。</p>
<div class="sourceCode" id="cb1000"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1000-1"><a href="datahandling2.html#cb1000-1"></a><span class="kw">full_join</span>(df2, df4, <span class="dt">by =</span> <span class="st">&quot;Pref&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb1000-2"><a href="datahandling2.html#cb1000-2"></a><span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(RamenN)) <span class="co"># ぐるなびに登録された店舗の多い都道府県から出力</span></span></code></pre></div>
<pre><code>## # A tibble: 47 x 6
##    Pref     Budget_Mean ScoreN_Sum Score_Mean     N RamenN
##    &lt;chr&gt;          &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;
##  1 東京都         1283.       1165       3.67  1000   3220
##  2 北海道           NA          NA      NA       NA   1454
##  3 大阪府         1203.        516       3.77  1000   1325
##  4 愛知県           NA          NA      NA       NA   1255
##  5 神奈川県       1239.        587       3.53  1000   1254
##  6 埼玉県         1147.        278       3.64  1000   1106
##  7 千葉県         1124.        259       3.72  1000   1098
##  8 福岡県           NA          NA      NA       NA    985
##  9 新潟県           NA          NA      NA       NA    705
## 10 静岡県           NA          NA      NA       NA    679
## # … with 37 more rows</code></pre>
<p><code>df2</code>にはなかった北海道や愛知県などの行ができました。そして、<code>df2</code>にはない情報はすべて欠損値 (<code>NA</code>)となりました。</p>
<p>続いて、<code>left_join()</code>ですが、これは先に指定したデータに存在するキーのみで結合を行います (図<a href="datahandling2.html#fig:left-join">11.5</a>)。今回は<code>df2</code>が先に指定されていますが、<code>df2</code>のキーは<code>df4</code>のキーの部分集合であるため、<code>inner_join()</code>と同じ結果が得られます。</p>
<div class="figure" style="text-align: center"><span id="fig:left-join"></span>
<img src="Figures/Handling2/Merge_Left.png" alt="`left_join()`の仕組み" width="80%" />
<p class="caption">
図 11.5: <code>left_join()</code>の仕組み
</p>
</div>
<p>一方、<code>right_join()</code>は<code>left_join()</code>と逆の関数であり、後に指定したデータに存在するキーを基準に結合を行います (図<a href="datahandling2.html#fig:right-join">11.6</a>)。後に指定された<code>df4</code>のキーは<code>df2</code>のキーを完全に含むので、<code>full_join()</code>と同じ結果が得られます。</p>
<div class="figure" style="text-align: center"><span id="fig:right-join"></span>
<img src="Figures/Handling2/Merge_Right.png" alt="`right_join()`の仕組み" width="80%" />
<p class="caption">
図 11.6: <code>right_join()</code>の仕組み
</p>
</div>
<p>これからは<code>df2</code>と<code>df4</code>を結合することになりますが、この2つのtibbleの大きさが異なります。<code>df2</code>は9つの都府県のみであるに対し、<code>df4</code>は47都道府県全てのデータが入っているからです。</p>
<p>ここまではキー変数が一つである場合についてのみ考えましたが、複数のキー変数が必要な場合もあります。たとえば、市区町村の人口・面積データと市区町村の投票率データを結合するとします。各自治体に与えられている「<a href="https://www.soumu.go.jp/denshijiti/code.html">全国地方公共団体コード</a>」が両データに含まれている場合は、このコードをキー変数として使えば問題ありませんが、市区町村名をキー変数として使わざる得ないケースもあるでしょう。しかし、キー変数が複数ある場合もあります。たとえば、府中市は東京都と広島県にありますし、太子町は大阪府と兵庫県にあります。この場合、市区町村名のみでケースをマッチングすると、重複されてマッチングされる恐れがあります。この場合はキー変数を増やすことで対処できます。たとえば、同じ都道府県なら同じ市区町村は存在しないでしょう<a href="#fn58" class="footnote-ref" id="fnref58"><sup>58</sup></a>。キー変数を複数指定する方法は簡単です。たとえば、市区町村名変数が<code>Munip</code>、都道府県名変数が<code>Pref</code>なら<code>by = c("Munip", "Pref")</code>と指定するだけです。</p>
<p>最後に、キー変数以外の変数名が重複する場合について考えましょう。これはパネルデータを結合する時によく直面する問題です。同じ回答者に2回の調査を行った場合、回答者のIDでデータを結合することになります。ただし、それぞれのデータにおいて回答者の性別に関する変数が<code>F1</code>という名前の場合、どうなるでしょうか。同じデータの同じ名前の変数が複数あると、非常に扱いにくくなります。実際の結果を見てみましょう。</p>
<div class="sourceCode" id="cb1002"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1002-1"><a href="datahandling2.html#cb1002-1"></a>Wave1_df &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">ID =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>),</span>
<span id="cb1002-2"><a href="datahandling2.html#cb1002-2"></a>                   <span class="dt">F1 =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb1002-3"><a href="datahandling2.html#cb1002-3"></a>                   <span class="dt">F2 =</span> <span class="kw">c</span>(<span class="dv">18</span>, <span class="dv">77</span>, <span class="dv">37</span>, <span class="dv">50</span>, <span class="dv">41</span>),</span>
<span id="cb1002-4"><a href="datahandling2.html#cb1002-4"></a>                   <span class="dt">Q1 =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>))</span>
<span id="cb1002-5"><a href="datahandling2.html#cb1002-5"></a></span>
<span id="cb1002-6"><a href="datahandling2.html#cb1002-6"></a>Wave2_df &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">ID =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">7</span>),</span>
<span id="cb1002-7"><a href="datahandling2.html#cb1002-7"></a>                   <span class="dt">F1 =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb1002-8"><a href="datahandling2.html#cb1002-8"></a>                   <span class="dt">F2 =</span> <span class="kw">c</span>(<span class="dv">18</span>, <span class="dv">37</span>, <span class="dv">50</span>, <span class="dv">20</span>, <span class="dv">62</span>),</span>
<span id="cb1002-9"><a href="datahandling2.html#cb1002-9"></a>                   <span class="dt">Q1 =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">4</span>))</span>
<span id="cb1002-10"><a href="datahandling2.html#cb1002-10"></a></span>
<span id="cb1002-11"><a href="datahandling2.html#cb1002-11"></a><span class="kw">full_join</span>(Wave1_df, Wave2_df, <span class="dt">by =</span> <span class="st">&quot;ID&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 7 x 7
##      ID  F1.x  F2.x  Q1.x  F1.y  F2.y  Q1.y
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     1     1    18     1     1    18     1
## 2     2     1    77     5    NA    NA    NA
## 3     3     0    37     2     0    37     2
## 4     4     0    50     2     0    50     2
## 5     5     1    41     3    NA    NA    NA
## 6     6    NA    NA    NA     0    20     5
## 7     7    NA    NA    NA     1    62     4</code></pre>
<p>それぞれの変数名の後に<code>.x</code>と<code>.y</code>が付きます。この接尾辞 (suffix)は<code>suffix</code>引数を指定することで、分析側からカスタマイズ可能です。たとえば、接尾辞を<code>_W1</code>、<code>_W2</code>にしたい場合は</p>
<div class="sourceCode" id="cb1004"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1004-1"><a href="datahandling2.html#cb1004-1"></a><span class="kw">full_join</span>(Wave1_df, Wave2_df, <span class="dt">by =</span> <span class="st">&quot;ID&quot;</span>, <span class="dt">suffix =</span> <span class="kw">c</span>(<span class="st">&quot;_W1&quot;</span>, <span class="st">&quot;_W2&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 7 x 7
##      ID F1_W1 F2_W1 Q1_W1 F1_W2 F2_W2 Q1_W2
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     1     1    18     1     1    18     1
## 2     2     1    77     5    NA    NA    NA
## 3     3     0    37     2     0    37     2
## 4     4     0    50     2     0    50     2
## 5     5     1    41     3    NA    NA    NA
## 6     6    NA    NA    NA     0    20     5
## 7     7    NA    NA    NA     1    62     4</code></pre>
<p>のように、データ1とデータ2それぞれの接尾辞を指定するだけです。</p>
<hr />
</div>
</div>
<div id="handling2-exercise" class="section level2">
<h2><span class="header-section-number">11.6</span> 練習問題</h2>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="57">
<li id="fn57"><p>これらの図は<a href="https://r4ds.had.co.nz">Garrett Grolemund and Hadley Wickham. 2017. <em>R for Data Science: Import, Tidy, Transform, Visualize, and Model Data.</em> O’Reilly.</a>を参考にしました。<a href="datahandling2.html#fnref57" class="footnote-back">↩︎</a></p></li>
<li id="fn58"><p>行政区も含むなら多くの政令指定都市にある「南区」とか「北区」が重複しますが、ここでは考えないことにしましょう。<a href="datahandling2.html#fnref58" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://aruaruaru.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
            </section>

          </div>
        </div>
      </div>
<a href="datahandling1.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="factor.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["R_Not_for_Everyone.pdf", "R_Not_for_Everyone.epub"],
"toc": {
"collapse": "section"
},
"toolbar": {
"position": "fixed"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
