# オブジェクト指向型プログラミング (S4) {#oop2}

```{r, echo = FALSE, message = FALSE}
rm(list = ls())
library(knitr)
opts_chunk$set(attr.source = '.numberLines', fig.align = "center", 
               message = FALSE, warning = FALSE)
```

---

```{r}
library(tidyverse)
setClass("My_S4_Object", 
         representation(
           data     = "data.frame", 
           var_name = "character", 
           cor      = "numeric",
           cor_ci   = "numeric"
           )
         )

My_Cor_S4 <- function(x, y, x.name, y.name) {
  if (!is.numeric(x) | !is.numeric(y)) {
    stop("xまたはyがnumeric型ではありません。")
  }
  if (length(x) != length(y)) {
    stop("xとyは同じ長さでなかればなりません。")
  }
  if (!is.character(x.name) | !is.character(y.name)) {
    stop("x.nameまたはy.nameがcharacter型ではありません。")
  }
  
  data     <- data.frame(x = x, y = y)
  var_name <- c(x.name, y.name)
  cor      <- cor.test(x, y)$estimate
  cor_ci   <- cor.test(x, y)$conf.int
  
  new("My_S4_Object",
      data     = data, 
      var_name = var_name, 
      cor      = cor,
      cor_ci   = cor_ci)
}

setValidity("My_S4_Object", function(x) {
  invalids <- c()
  if (length(x@var_name)     != 2 ||
      length(x@cor)   != 1 ||
      length(x@cor_ci)  != 2) {
    invalids <- "@var_name, @cor, @cor_ci must be of length 2, 1, and 2"
  } 
  
  if (length(invalids) > 0) {
    return(invalids)  
  }
  
  TRUE
})

setMethod("plot", "My_S4_Object",
          function(x) {
            x@data %>%
              ggplot(aes(x = x, y = y)) +
              geom_point() +
              labs(x = x@var_name[1], y = x@var_name[2]) +
              ggtitle(sprintf("相関係数 = %.3f", x@cor)) +
              theme_minimal(base_family = "HiraKakuProN-W3")
          })

setMethod("print", "My_S4_Object",
          function(x) {
            cat(sprintf("%sの平均値: %.3f\n", 
                        x@var_name[1],
                        mean(x@data$x)))
            cat(sprintf("%sの平均値: %.3f\n", 
                        x@var_name[2],
                        mean(x@data$y)))
            cat(sprintf("相関係数: %.3f [%.3f, %.3f]\n", 
                        x@cor, 
                        x@cor_ci[1],
                        x@cor_ci[2]))
          })

setMethod("summary", "My_S4_Object",
          function(object) {
            print(object)
          })
```

```{r}
formals("plot")
formals("print")
formals("summary")
```

```{r}
library(tidyverse)

Cor_Obj_S4 <- My_Cor_S4(x      = rnorm(20, 2, 0.5), 
                        y      = rnorm(20, 165, 6), 
                        x.name = "1日当たりゲーム時間", 
                        y.name = "身長")

Cor_Obj_S4

class(Cor_Obj_S4)

plot(Cor_Obj_S4)

print(Cor_Obj_S4)

summary(Cor_Obj_S4)
```
