# Quarto [3]

:::{.callout-important}
## 本項目は執筆途中です！

本章は完成後、既存のR MarkdownとQuartoの内容の一部を代替しますが、現時点では参考程度にしてください。
:::

## YAML header

### HTML（reveal.js）

`format: revealjs`

### PDF（Beamer）

```yaml
---
title: "討論：社会的動乱と分極化のメカニズムを探る"
subtitle: "日本比較政治学会2024年度大会"
date: "2024/6/22"
author: "\\ltjruby{宋財泫}{そん じぇひょん}"
institute: "関西大学　総合情報学部"
knitr: 
  opts_chunk: 
    dev: "ragg_png"
    dpi: 300
    fig.align: "center"
    echo: false
    message: false
    warning: false
format: 
  beamer:
    pdf-engine: lualatex
    theme: metropolis
    classoption:
      - 10pt
    mainfont: "Noto Sans JP"
    CJKmainfont: "Noto Sans JP"
    include-in-header: 
      text: |
        \usepackage{luatexja-ruby}
---
```

`mainfont`と`CJKmainfont`のフォント名は適宜修正。UbuntuでNotoフォントを入れた場合、高確率で`"Noto Sans CJK JP"`。macOSなら`"Hiragino Sans"`でOK。

## スライドの作り方

### ページ区切り

`##`

### セクションの区切り

`#`

## 各種機能

* ホワイトボード
* ペン機能
* スピーカービュー

## スライドの配付

　Quartoで作成可能なスライドのフォーマットは[reveal.js](https://revealjs.com/)ベースの`.html`、$\LaTeX$（Beamer）ベースの`.pdf`、Microsoft Powerpointの`.pptx`である。`.pdf`や`.pptx`は図表を含む全ての内容が一つのファイルに保存されているため、そのファイルだけ共有すれば良い。しかし、多くの人が利用するであろう`.html`ファイルを他の人に共有したり、学会発表のためにUSBメモリに入れる際は注意が必要だ。

`ほにゃほにゃ_files`フォルダーも忘れずに共有する

ネットにアップロードして共有する（Quarto Pub、GitHub Pagesなど）。

### 一つのHTMLファイルにまとめる

自己完結型（self-contained）HTML

```yaml
format:
  html:
    embed-resources: true
```

数式をレンダリングする数式ライブラリ（MathJaxとKaTeX）がサイズが大きいため、`embed-resources: true`でも自己完結型HTMLに含まれず、ネット経由で取得することになる。しかし、インターネットが使えない環境になるとせっかくの数式がレンダリングされない。この場合、`self-contained-math: true`を追加すると、数式ライブラリもHTMLファイルに保存される。

```yaml
format:
  html:
    embed-resources: true
    self-contained-math: true
```

### PDF出力

　HTMLファイルを一つにまとめた場合、ファイルのサイズが大きくなる。大量の図が使用されたり、数式ライブラリまでHTMLファイルに含めると数十MBになる可能性もある。この場合、PDF形式で出力すればサイズを大幅に減らせることができよう。この場合、タブセット[^pdf-tabset]、スクロールのような**インタラクティブ（動的）な機能はすべて無効になる**が、そういった要素がないスライドであれば、自己完結型HTMLよりもPDFの方が合理的だろう。

[^pdf-tabset]: 2つ以上のタブで構成されたタブセットの場合、最初のタブのみが印刷される。

　しかし、残念ながら2024年5月現在、HTML形式スライドをPDFに変換する方法は限られており、見た目もお世辞でも綺麗とは言えない。むろん、内容が変わったり、本来見えたものが見えなくなったりすることはない。それでも構わないという読者は以下のやり方でHTMLスライドをPDFに変換できる。用意するものはBlinkベースのウェブブラウザーだ。代表的にはGoogle社のChromeとChromiumがあり、Microsoft EdgeやOperaもBlinkエンジンを使用している。

　HTMLファイルのPDF変換は言い換えれば、PDF形式で印刷することを意味する。

1. Blinkエンジンを使用するブラウザーでスライドを開く。
2. スライドが表示されたらキーボードの「E」、または「e」キーを押す。
3. macOSならCommand（⌘） + P、WindowsならControl（Ctrl）+ Pを押す。
4. 出力先をPDFにする。
5. 用紙のレイアウトを横向き（Landscape）に指定する。
6. 余白をなしにする。
7. 背景画像のオプションにチェックを入れる。
8. 「保存」をクリックする（ブラウザーによっては「印刷」と表示される）。

　このやり方だと最後に余計な白紙のページが現れるが、これは手動で消そう（無害なのでほっといてもOK）。

### まとめ

* PDF形式にこだわりたい：最初からBeamer
* 