# 分析環境のカスタマイズ {#R-Customize}

```{r customize-common, include = FALSE}
source("_common.R")
```

## .Rprofileの設定 {#Customize-rprofile}

## RStudioのカスタマイズ {#Customize-rstudio}

1. Tools > Global Options
2. General
  1. Basicタブ
    * Restore .RData into workspace at startupのチェックを**消す**。
    * Save workspace to .RData on exit:を**Never**に変更する。
    * Always save history (even when not saving .RData)のチェックを**消す**。
3. Code
  1. Editingタブ
    * Insert spaces for tabのチェックを**付ける**。
      * Tab widthは2か4
    * Auto-detect code indentationのチェックを**付ける**。
    * Insert matching parens/quotesのチェックを**付ける**。
    * Auto-indent code after pasteのチェックを**付ける**。
    * Vertically align arguments in auto-indentのチェックを**付ける**。
    * Always save R scripts before sourcingのチェックを**付ける**。
    * Ctrl + Return executes:を**Multi-line R statement**に変更する。
  2. Displayタブ
    * Highlight selected wordのチェックを**付ける**。
    * Highlight selected lineのチェックを**付ける**。
    * Show line numbersのチェックを**付ける**。
    * Show syntax highlighting in console inputのチェックを**付ける**。
    * Highlight R function callsのチェックを**付ける**。
    * Rainbow parenthesesのチェックを**付ける**。
  3. Savingタブ
    * Default text encoding:のChangeをクリックし、**UTF-8**を選択する。
  4. Completionタブ
    * Show code completion:を**Automatically**に変更する。
    * Allow automatic completions in consoleのチェックを**付ける**。
    * Insert parentheses after function completionsのチェックを**付ける**。
    * Show help tooltip after function completionsのチェックを**付ける**。
    * Insert spaces around equals for argument completionsのチェックを**付ける**。
    * Use tab for autocompletionのチェックを**付ける**。
4. Appearance
   * 自分の好みのものを選択する。
5. Pane Layout
   * 左上: Source
   * 右上: Console
   * 左下: 全てチェックを**消す**。
   * 左下: 全てチェックを**付ける**。
6. 左下のApplyをクリック